TBT::Client Class Reference
#include <Client.h>
Public Member Functions
Client (ClientInterface *pInterface)
virtual ~Client ()
ClientInterface * getInterface (void)
virtual void broadcastPowerStateChange (bool newState)=0
virtual void broadcastLocInfoChanged (LocDecoder *pLoc)=0
virtual void broadcastEmergencyStop (void)=0
Protected Attributes
ClientInterface * m_pInterface
Constructor & Destructor Documentation
Client()
TBT::Client::Client (ClientInterface * pInterface)
 Client()
TBT::Client::~Client () [virtual]
Member Function Documentation
broadcastEmergencyStop()
virtual void TBT::Client::broadcastEmergencyStop (void) [pure virtual]
Implemented in TBT::XpressNetClient, and TBT::UDPClient.
Referenced by getInterface().
broadcastLocInfoChanged()
virtual void TBT::Client::broadcastLocInfoChanged (LocDecoder * pLoc) [pure virtual]
Implemented in TBT::XpressNetClient, and TBT::UDPClient.
Referenced by getInterface().
broadcastPowerStateChange()
virtual void TBT::Client::broadcastPowerStateChange (bool newState) [pure virtual]
Implemented in TBT::XpressNetClient, and TBT::UDPClient.
Referenced by getInterface().
getInterface()
ClientInterface* TBT::Client::getInterface (void) [inline]
References broadcastEmergencyStop(), broadcastLocInfoChanged(), broadcastPowerStateChange(), and m_pInterface.
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
Member Data Documentation
m_pInterface
ClientInterface* TBT::Client::m_pInterface [protected]
Referenced by getInterface(), and TBT::UDPClient::UDPClient().
The documentation for this class was generated from the following files:
Client.h
Client.cpp