TBT::UDPClient Class Reference
#include <UDPClient.h>
Public Member Functions
UDPClient (UDPClientInterface *pinterface, const sockaddr_in &address)
virtual ~UDPClient ()
virtual void broadcastPowerStateChange (bool newState)
virtual void broadcastLocInfoChanged (LocDecoder *pLoc)
virtual void broadcastEmergencyStop (void)
const sockaddr_in & getAddress (void)
uint32_t getBroadcastFlags (void)
void setBroadcastFlags (uint32_t newFlags)
Protected Attributes
const sockaddr_in m_Address
int m_MySocket
uint32_t m_BroadcastFlags
Constructor & Destructor Documentation
UDPClient()
TBT::UDPClient::UDPClient (UDPClientInterface * pinterface, const sockaddr_in & address)
References m_MySocket, and TBT::Client::m_pInterface.
 UDPClient()
TBT::UDPClient::~UDPClient () [virtual]
Member Function Documentation
broadcastEmergencyStop()
void TBT::UDPClient::broadcastEmergencyStop (void) [virtual]
response: LAN_X_BC_STOPPED
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
    0x81 0x00 0x81
Implements TBT::Client.
References m_Address, and m_MySocket.
broadcastLocInfoChanged()
void TBT::UDPClient::broadcastLocInfoChanged (LocDecoder * pLoc) [virtual]
Implements TBT::Client.
References TBT::LocDecoder::getLANLocInfo(), m_Address, and m_MySocket.
broadcastPowerStateChange()
void TBT::UDPClient::broadcastPowerStateChange (bool newState) [virtual]
response: LAN_X_BC_TRACK_POWER_ON
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
    0x61 0x01 0x60
response: LAN_X_BC_TRACK_POWER_OFF
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
    0x61 0x00 0x61
Implements TBT::Client.
References m_Address, and m_MySocket.
getAddress()
const sockaddr_in& TBT::UDPClient::getAddress (void) [inline]
References getBroadcastFlags(), and m_Address.
getBroadcastFlags()
uint32_t TBT::UDPClient::getBroadcastFlags (void)
Broadcast flags is an OR combination of the following values:
 Value Meaning
 Value Meaning
0x00000001 Automatically generated broadcasts and messages about driving and switching are delivered to the registered client. The following messages are subscribed here:
LAN_X_BC_TRACK_POWER_OFF
LAN_X_BC_TRACK_POWER_ON
LAN_X_BC_PROGRAMMING_MODE
LAN_X_BC_TRACK_SHORT_CIRCUIT
LAN_X_BC_STOPPED
LAN_X_LOCO_INFO (the relevant locomotive address must also be subscribed)
LAN_X_TURNOUT_INFO
0x00000002 Changes to the feedback on the R-Bus are sent automatically. Broadcast message of Z21 see LAN_RMBUS_DATACHANGED
0x00000004 Changes to RailCom data of the subscribed locomotives will be sent automatically. Broadcast message of Z21 see LAN_RAILCOM_DATACHANGED
0x00000100 Changes to the Z21 system state are sent automatically. Broadcast message of Z21 see LAN_SYSTEMSTATE_DATACHANGED
From Z21 FW Version 1.20:
0x00010000 Replaces flag 0x00000001; Client now gets LAN_X_LOCO_INFO without first having to subscribe to the corresponding loco addresses, i.e. for all controlled locomotives! Due to the high network traffic, this flag may only be used in full PC controlled applications and is by no means intended for mobile handheld controllers.
From FW V1.20 to V1.23: LAN_X_LOCO_INFO is sent for all locomotives.
From FW V1.24: LAN_X_LOCO_INFO will be sent for all modified locos.
0x01000000 Forward messages from the LocoNet bus to the LAN client without locos and points.
0x02000000 Forward Loco-Specific LocoNet Messages to LAN Client: OPC_LOCO_SPD, OPC_LOCO_DIRF, OPC_LOCO_SND, OPC_LOCO_F912, OPC_EXP_CMD
0x04000000 Route turnout-specific LocoNet messages to LAN client: OPC_SW_REQ, OPC_SW_REP, OPC_SW_ACK, OPC_SW_STATE
From Z21 FW Version 1.22:
0x08000000 Send status messages from track occupancy detectors on the LocoNet bus to the LAN client. See LAN_LOCONET_DETECTOR
From Z21 FW Version 1.29:
0x00040000 Changes to RailCom data are sent automatically. Client gets LAN_RAILCOM_DATACHANGED, even without having to subscribe to the locomotive addresses beforehand, i.e. for all controlled locomotives! Due to the high network traffic, this flag may only be used in full PC controlled applications and is by no means intended for mobile handheld controllers. Broadcast message of Z21 see LAN_RAILCOM_DATACHANGED
From Z21 FW Version 1.30:
0x00080000 Send status messages from track occupancy detectors on the CAN bus to the LAN client. See LAN_CAN_DETECTOR
References m_BroadcastFlags.
Referenced by getAddress(), and TBT::UDPClientInterface::threadFunc().
setBroadcastFlags()
void TBT::UDPClient::setBroadcastFlags (uint32_t newFlags) [inline]
References m_BroadcastFlags.
Referenced by TBT::UDPClientInterface::threadFunc().
Member Data Documentation
m_Address
const sockaddr_in TBT::UDPClient::m_Address [protected]
Referenced by broadcastEmergencyStop(), broadcastLocInfoChanged(), broadcastPowerStateChange(), and getAddress().
m_BroadcastFlags
uint32_t TBT::UDPClient::m_BroadcastFlags [protected]
Referenced by getBroadcastFlags(), and setBroadcastFlags().
m_MySocket
int TBT::UDPClient::m_MySocket [protected]
Referenced by broadcastEmergencyStop(), broadcastLocInfoChanged(), broadcastPowerStateChange(), and UDPClient().
The documentation for this class was generated from the following files:
UDPClient.h
UDPClient.cpp