TBT::XpressNetClient Class Reference
#include <XpressNetClient.h>
Public Member Functions
XpressNetClient (ClientInterface *pInterface, uint8_t XpressNetAddress)
virtual ~XpressNetClient ()
const uint8_t & getAddress (void)
virtual void broadcastPowerStateChange (bool newState)
virtual void broadcastLocInfoChanged (LocDecoder *pLoc)
virtual void broadcastEmergencyStop (void)
Protected Attributes
uint8_t m_XpressNetAddress
Constructor & Destructor Documentation
XpressNetClient()
TBT::XpressNetClient::XpressNetClient (ClientInterface * pInterface, uint8_t XpressNetAddress)
 XpressNetClient()
TBT::XpressNetClient::~XpressNetClient () [virtual]
Member Function Documentation
broadcastEmergencyStop()
virtual void TBT::XpressNetClient::broadcastEmergencyStop (void) [inline], [virtual]
Implements TBT::Client.
broadcastLocInfoChanged()
void TBT::XpressNetClient::broadcastLocInfoChanged (LocDecoder * pLoc) [virtual]
Implements TBT::Client.
Referenced by getAddress().
broadcastPowerStateChange()
void TBT::XpressNetClient::broadcastPowerStateChange (bool newState) [virtual]
Implements TBT::Client.
Referenced by getAddress().
getAddress()
const uint8_t& TBT::XpressNetClient::getAddress (void) [inline]
References broadcastLocInfoChanged(), broadcastPowerStateChange(), and m_XpressNetAddress.
Member Data Documentation
m_XpressNetAddress
uint8_t TBT::XpressNetClient::m_XpressNetAddress [protected]
Referenced by getAddress().
The documentation for this class was generated from the following files:
XpressNetClient.h
XpressNetClient.cpp