Json::Features Class Reference
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
#include <json.h>
Public Member Functions
Features ()
Initialize the configuration like JsonConfig::allFeatures;.
Static Public Member Functions
static Features all ()
A configuration that allows all features and assumes all strings are UTF-8.
static Features strictMode ()
A configuration that is strictly compatible with the JSON specification.
Public Attributes
bool allowComments_
true if comments are allowed. Default: true.
bool strictRoot_
bool allowDroppedNullPlaceholders_
true if dropped null placeholders are allowed. Default: false.
bool allowNumericKeys_
true if numeric object key are allowed. Default: false.
Detailed Description
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
Constructor & Destructor Documentation
Features()
Json::Features::Features ()
Initialize the configuration like JsonConfig::allFeatures;.
Referenced by all().
Member Function Documentation
all()
Features Json::Features::all () [static]
A configuration that allows all features and assumes all strings are UTF-8.
C & C++ comments are allowed
Root object can be any JSON value
Assumes Value strings are encoded in UTF-8
References Features().
Referenced by strictMode().
strictMode()
Features Json::Features::strictMode () [static]
A configuration that is strictly compatible with the JSON specification.
Comments are forbidden.
Root object must be either an array or an object value.
Assumes Value strings are encoded in UTF-8
References all(), allowComments_, allowDroppedNullPlaceholders_, allowNumericKeys_, Json::arrayValue, Json::Value::asCString(), Json::codePointToUTF8(), Json::commentAfter, Json::commentAfterOnSameLine, Json::commentBefore, Json::Value::getOffsetLimit(), Json::Value::getOffsetStart(), Json::Value::isArray(), Json::Value::isObject(), JSONCPP_ISTRINGSTREAM, JSONCPP_STRING, Json::Value::maxInt, Json::Value::maxLargestInt, Json::Value::maxLargestUInt, Json::Value::minLargestInt, Json::objectValue, Json::Value::setComment(), stackLimit_g, strictRoot_, Json::Value::swapPayload(), and Json::throwRuntimeError().
Member Data Documentation
allowComments_
bool Json::Features::allowComments_
true if comments are allowed. Default: true.
Referenced by strictMode().
allowDroppedNullPlaceholders_
bool Json::Features::allowDroppedNullPlaceholders_
true if dropped null placeholders are allowed. Default: false.
Referenced by strictMode().
allowNumericKeys_
bool Json::Features::allowNumericKeys_
true if numeric object key are allowed. Default: false.
Referenced by strictMode().
strictRoot_
bool Json::Features::strictRoot_
true if root must be either an array or an object value. Default: false.
Referenced by strictMode().
The documentation for this class was generated from the following files:
json/json.h
jsoncpp.cpp