TBT::LocDecoder Class Reference
#include <LocDecoder.h>
Public Member Functions
LocDecoder (Manager *pManager, uint16_t dccAddress)
virtual ~LocDecoder ()
virtual bool getDccMessage (uint8_t *pMsg)
uint8_t getLocMode (void)
void getLANLocInfo (uint8_t *pMsg)
uint8_t setLocMode (uint8_t newMode)
bool getBusy ()
uint8_t getSpeedsteps ()
bool getDirection ()
uint8_t getSpeed ()
bool getDualTraction ()
bool getSmartSearch ()
bool getLight ()
uint8_t getFunctionGroup1 ()
bool getF0 ()
bool getF1 ()
bool getF2 ()
bool getF3 ()
bool getF4 ()
uint8_t getFunctionGroup2 ()
bool getF5 ()
bool getF6 ()
bool getF7 ()
bool getF8 ()
uint8_t getFunctionGroup3 ()
bool getF9 ()
bool getF10 ()
bool getF11 ()
bool getF12 ()
uint8_t getFunctionGroup4 ()
bool getF13 ()
bool getF14 ()
bool getF15 ()
bool getF16 ()
bool getF17 ()
bool getF18 ()
bool getF19 ()
bool getF20 ()
uint8_t getFunctionGroup5 ()
bool getF21 ()
bool getF22 ()
bool getF23 ()
bool getF24 ()
bool getF25 ()
bool getF26 ()
bool getF27 ()
bool getF28 ()
void setBusy (bool value)
void setSpeedsteps (uint8_t value)
void setLocoDrive14 (uint8_t value)
void setLocoDrive27 (uint8_t value)
void setLocoDrive28 (uint8_t value)
void setLocoDrive128 (uint8_t value)
void setDirection (bool value)
void setSpeed (uint8_t value)
void setDualTraction (bool value)
void setSmartSearch (bool value)
void setFunctionGroup1 (const uint8_t &value)
void setLight (bool value)
void setF0 (bool value)
void setF1 (bool value)
void setF2 (bool value)
void setF3 (bool value)
void setF4 (bool value)
void setFunctionGroup2 (const uint8_t &value)
void setF5 (bool value)
void setF6 (bool value)
void setF7 (bool value)
void setF8 (bool value)
void setFunctionGroup3 (const uint8_t &value)
void setF9 (bool value)
void setF10 (bool value)
void setF11 (bool value)
void setF12 (bool value)
void setFunctionGroup4 (const uint8_t &value)
void setF13 (bool value)
void setF14 (bool value)
void setF15 (bool value)
void setF16 (bool value)
void setF17 (bool value)
void setF18 (bool value)
void setF19 (bool value)
void setF20 (bool value)
void setFunctionGroup5 (const uint8_t &value)
void setF21 (bool value)
void setF22 (bool value)
void setF23 (bool value)
void setF24 (bool value)
void setF25 (bool value)
void setF26 (bool value)
void setF27 (bool value)
void setF28 (bool value)
Protected Member Functions
bool getDCCSpeedMessage (uint8_t *pMsg)
bool getDCCFG1Message (uint8_t *pMsg)
bool getDCCFG2Message (uint8_t *pMsg)
bool getDCCFG3Message (uint8_t *pMsg)
bool getDCCFG4Message (uint8_t *pMsg)
bool getDCCFG5Message (uint8_t *pMsg)
Private Attributes
uint8_t m_LocMode
uint8_t m_DCCState
uint8_t m_CurrentCVRead
LocInfo m_LocInfo
recursive_mutex m_MLocInfo
Additional Inherited Members
Constructor & Destructor Documentation
LocDecoder()
TBT::LocDecoder::LocDecoder (Manager * pManager, uint16_t dccAddress)
References TBT::LocInfo::Addr_LSB, TBT::LocInfo::Addr_MSB, TBT::Decoder::m_DCCAddress, m_LocInfo, and setSpeedsteps().
 LocDecoder()
TBT::LocDecoder::~LocDecoder () [virtual]
Member Function Documentation
getBusy()
bool TBT::LocDecoder::getBusy () [inline]
References TBT::LocInfo::DB2, m_LocInfo, and m_MLocInfo.
getDCCFG1Message()
bool TBT::LocDecoder::getDCCFG1Message (uint8_t * pMsg) [protected]
References getFunctionGroup1(), TBT::Decoder::insertDCCAddress(), and TBT::Decoder::insertXOR().
Referenced by getDccMessage(), and setF28().
getDCCFG2Message()
bool TBT::LocDecoder::getDCCFG2Message (uint8_t * pMsg) [protected]
References getFunctionGroup2(), TBT::Decoder::insertDCCAddress(), and TBT::Decoder::insertXOR().
Referenced by getDccMessage(), and setF28().
getDCCFG3Message()
bool TBT::LocDecoder::getDCCFG3Message (uint8_t * pMsg) [protected]
References getFunctionGroup3(), TBT::Decoder::insertDCCAddress(), and TBT::Decoder::insertXOR().
Referenced by getDccMessage(), and setF28().
getDCCFG4Message()
bool TBT::LocDecoder::getDCCFG4Message (uint8_t * pMsg) [protected]
References getFunctionGroup4(), TBT::Decoder::insertDCCAddress(), and TBT::Decoder::insertXOR().
Referenced by getDccMessage(), and setF28().
getDCCFG5Message()
bool TBT::LocDecoder::getDCCFG5Message (uint8_t * pMsg) [protected]
References getFunctionGroup5(), TBT::Decoder::insertDCCAddress(), and TBT::Decoder::insertXOR().
Referenced by getDccMessage(), and setF28().
getDccMessage()
bool TBT::LocDecoder::getDccMessage (uint8_t * pMsg) [virtual]
Reimplemented from TBT::Decoder.
References TBT::SystemState::CentralState, getDCCFG1Message(), getDCCFG2Message(), getDCCFG3Message(), getDCCFG4Message(), getDCCFG5Message(), getDCCSpeedMessage(), TBT::Manager::getSystemState(), TBT::Decoder::insertDCCAddress(), TBT::Decoder::insertXOR(), m_CurrentCVRead, m_DCCState, m_MLocInfo, and TBT::Decoder::m_pManager.
getDCCSpeedMessage()
bool TBT::LocDecoder::getDCCSpeedMessage (uint8_t * pMsg) [protected]
References getDirection(), getLight(), getSpeed(), getSpeedsteps(), TBT::Decoder::insertDCCAddress(), and TBT::Decoder::insertXOR().
Referenced by getDccMessage(), and setF28().
getDirection()
bool TBT::LocDecoder::getDirection () [inline]
References TBT::LocInfo::DB3, m_LocInfo, and m_MLocInfo.
Referenced by getDCCSpeedMessage().
getDualTraction()
bool TBT::LocDecoder::getDualTraction () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
getF0()
bool TBT::LocDecoder::getF0 () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF1()
bool TBT::LocDecoder::getF1 () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF10()
bool TBT::LocDecoder::getF10 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF11()
bool TBT::LocDecoder::getF11 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF12()
bool TBT::LocDecoder::getF12 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF13()
bool TBT::LocDecoder::getF13 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF14()
bool TBT::LocDecoder::getF14 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF15()
bool TBT::LocDecoder::getF15 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF16()
bool TBT::LocDecoder::getF16 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF17()
bool TBT::LocDecoder::getF17 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF18()
bool TBT::LocDecoder::getF18 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF19()
bool TBT::LocDecoder::getF19 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF2()
bool TBT::LocDecoder::getF2 () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF20()
bool TBT::LocDecoder::getF20 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF21()
bool TBT::LocDecoder::getF21 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF22()
bool TBT::LocDecoder::getF22 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF23()
bool TBT::LocDecoder::getF23 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF24()
bool TBT::LocDecoder::getF24 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF25()
bool TBT::LocDecoder::getF25 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF26()
bool TBT::LocDecoder::getF26 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF27()
bool TBT::LocDecoder::getF27 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF28()
bool TBT::LocDecoder::getF28 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF3()
bool TBT::LocDecoder::getF3 () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF4()
bool TBT::LocDecoder::getF4 () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF5()
bool TBT::LocDecoder::getF5 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF6()
bool TBT::LocDecoder::getF6 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF7()
bool TBT::LocDecoder::getF7 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF8()
bool TBT::LocDecoder::getF8 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getF9()
bool TBT::LocDecoder::getF9 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by TBT::UDPClientInterface::threadFunc().
getFunctionGroup1()
uint8_t TBT::LocDecoder::getFunctionGroup1 () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
Referenced by getDCCFG1Message().
getFunctionGroup2()
uint8_t TBT::LocDecoder::getFunctionGroup2 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by getDCCFG2Message().
getFunctionGroup3()
uint8_t TBT::LocDecoder::getFunctionGroup3 () [inline]
References TBT::LocInfo::DB5, m_LocInfo, and m_MLocInfo.
Referenced by getDCCFG3Message().
getFunctionGroup4()
uint8_t TBT::LocDecoder::getFunctionGroup4 () [inline]
References TBT::LocInfo::DB6, m_LocInfo, and m_MLocInfo.
Referenced by getDCCFG4Message().
getFunctionGroup5()
uint8_t TBT::LocDecoder::getFunctionGroup5 () [inline]
References TBT::LocInfo::DB7, m_LocInfo, and m_MLocInfo.
Referenced by getDCCFG5Message().
getLANLocInfo()
void TBT::LocDecoder::getLANLocInfo (uint8_t * pMsg)
References TBT::LocInfo::DataLen, m_LocInfo, m_MLocInfo, and TBT::LocInfo::XOR.
Referenced by TBT::UDPClient::broadcastLocInfoChanged(), getLocMode(), and TBT::UDPClientInterface::threadFunc().
getLight()
bool TBT::LocDecoder::getLight () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
Referenced by getDCCSpeedMessage().
getLocMode()
uint8_t TBT::LocDecoder::getLocMode (void) [inline]
References getLANLocInfo(), m_LocMode, and setLocMode().
Referenced by TBT::UDPClientInterface::threadFunc().
getSmartSearch()
bool TBT::LocDecoder::getSmartSearch () [inline]
References TBT::LocInfo::DB4, m_LocInfo, and m_MLocInfo.
getSpeed()
uint8_t TBT::LocDecoder::getSpeed () [inline]
References TBT::LocInfo::DB3, m_LocInfo, and m_MLocInfo.
Referenced by getDCCSpeedMessage().
getSpeedsteps()
uint8_t TBT::LocDecoder::getSpeedsteps () [inline]
References TBT::LocInfo::DB2, m_LocInfo, and m_MLocInfo.
Referenced by getDCCSpeedMessage(), and TBT::XpressNetClientInterface::threadFunc().
setBusy()
void TBT::LocDecoder::setBusy (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB2, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
setDirection()
void TBT::LocDecoder::setDirection (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB3, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
setDualTraction()
void TBT::LocDecoder::setDualTraction (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
setF0()
void TBT::LocDecoder::setF0 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF1()
void TBT::LocDecoder::setF1 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF10()
void TBT::LocDecoder::setF10 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF11()
void TBT::LocDecoder::setF11 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF12()
void TBT::LocDecoder::setF12 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF13()
void TBT::LocDecoder::setF13 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF14()
void TBT::LocDecoder::setF14 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF15()
void TBT::LocDecoder::setF15 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF16()
void TBT::LocDecoder::setF16 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF17()
void TBT::LocDecoder::setF17 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF18()
void TBT::LocDecoder::setF18 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF19()
void TBT::LocDecoder::setF19 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF2()
void TBT::LocDecoder::setF2 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF20()
void TBT::LocDecoder::setF20 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF21()
void TBT::LocDecoder::setF21 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF22()
void TBT::LocDecoder::setF22 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF23()
void TBT::LocDecoder::setF23 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF24()
void TBT::LocDecoder::setF24 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF25()
void TBT::LocDecoder::setF25 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF26()
void TBT::LocDecoder::setF26 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF27()
void TBT::LocDecoder::setF27 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF28()
void TBT::LocDecoder::setF28 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, getDCCFG1Message(), getDCCFG2Message(), getDCCFG3Message(), getDCCFG4Message(), getDCCFG5Message(), getDCCSpeedMessage(), m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF3()
void TBT::LocDecoder::setF3 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF4()
void TBT::LocDecoder::setF4 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF5()
void TBT::LocDecoder::setF5 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF6()
void TBT::LocDecoder::setF6 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF7()
void TBT::LocDecoder::setF7 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF8()
void TBT::LocDecoder::setF8 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setF9()
void TBT::LocDecoder::setF9 (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::UDPClientInterface::threadFunc().
setFunctionGroup1()
void TBT::LocDecoder::setFunctionGroup1 (const uint8_t & value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc().
setFunctionGroup2()
void TBT::LocDecoder::setFunctionGroup2 (const uint8_t & value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc().
setFunctionGroup3()
void TBT::LocDecoder::setFunctionGroup3 (const uint8_t & value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB5, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc().
setFunctionGroup4()
void TBT::LocDecoder::setFunctionGroup4 (const uint8_t & value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB6, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc().
setFunctionGroup5()
void TBT::LocDecoder::setFunctionGroup5 (const uint8_t & value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB7, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc().
setLight()
void TBT::LocDecoder::setLight (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
setLocMode()
uint8_t TBT::LocDecoder::setLocMode (uint8_t newMode)
References LOCMODE_DCC, TBT::Decoder::m_DCCAddress, and m_LocMode.
Referenced by getLocMode(), and TBT::UDPClientInterface::threadFunc().
setLocoDrive128()
void TBT::LocDecoder::setLocoDrive128 (uint8_t value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB3, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
setLocoDrive14()
void TBT::LocDecoder::setLocoDrive14 (uint8_t value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB3, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
setLocoDrive27()
void TBT::LocDecoder::setLocoDrive27 (uint8_t value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB3, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc().
setLocoDrive28()
void TBT::LocDecoder::setLocoDrive28 (uint8_t value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB3, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
setSmartSearch()
void TBT::LocDecoder::setSmartSearch (bool value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB4, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
setSpeed()
void TBT::LocDecoder::setSpeed (uint8_t value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB3, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
setSpeedsteps()
void TBT::LocDecoder::setSpeedsteps (uint8_t value) [inline]
References TBT::Manager::broadcastLocInfoChanged(), TBT::LocInfo::DB2, m_LocInfo, m_MLocInfo, and TBT::Decoder::m_pManager.
Referenced by LocDecoder().
Member Data Documentation
m_CurrentCVRead
uint8_t TBT::LocDecoder::m_CurrentCVRead [private]
Referenced by getDccMessage().
m_DCCState
uint8_t TBT::LocDecoder::m_DCCState [private]
Referenced by getDccMessage().
m_LocInfo
LocInfo TBT::LocDecoder::m_LocInfo [private]
Referenced by getBusy(), getDirection(), getDualTraction(), getF0(), getF1(), getF10(), getF11(), getF12(), getF13(), getF14(), getF15(), getF16(), getF17(), getF18(), getF19(), getF2(), getF20(), getF21(), getF22(), getF23(), getF24(), getF25(), getF26(), getF27(), getF28(), getF3(), getF4(), getF5(), getF6(), getF7(), getF8(), getF9(), getFunctionGroup1(), getFunctionGroup2(), getFunctionGroup3(), getFunctionGroup4(), getFunctionGroup5(), getLANLocInfo(), getLight(), getSmartSearch(), getSpeed(), getSpeedsteps(), LocDecoder(), setBusy(), setDirection(), setDualTraction(), setF0(), setF1(), setF10(), setF11(), setF12(), setF13(), setF14(), setF15(), setF16(), setF17(), setF18(), setF19(), setF2(), setF20(), setF21(), setF22(), setF23(), setF24(), setF25(), setF26(), setF27(), setF28(), setF3(), setF4(), setF5(), setF6(), setF7(), setF8(), setF9(), setFunctionGroup1(), setFunctionGroup2(), setFunctionGroup3(), setFunctionGroup4(), setFunctionGroup5(), setLight(), setLocoDrive128(), setLocoDrive14(), setLocoDrive27(), setLocoDrive28(), setSmartSearch(), setSpeed(), and setSpeedsteps().
m_LocMode
uint8_t TBT::LocDecoder::m_LocMode [private]
Referenced by getLocMode(), and setLocMode().
m_MLocInfo
recursive_mutex TBT::LocDecoder::m_MLocInfo [private]
Referenced by getBusy(), getDccMessage(), getDirection(), getDualTraction(), getF0(), getF1(), getF10(), getF11(), getF12(), getF13(), getF14(), getF15(), getF16(), getF17(), getF18(), getF19(), getF2(), getF20(), getF21(), getF22(), getF23(), getF24(), getF25(), getF26(), getF27(), getF28(), getF3(), getF4(), getF5(), getF6(), getF7(), getF8(), getF9(), getFunctionGroup1(), getFunctionGroup2(), getFunctionGroup3(), getFunctionGroup4(), getFunctionGroup5(), getLANLocInfo(), getLight(), getSmartSearch(), getSpeed(), getSpeedsteps(), setBusy(), setDirection(), setDualTraction(), setF0(), setF1(), setF10(), setF11(), setF12(), setF13(), setF14(), setF15(), setF16(), setF17(), setF18(), setF19(), setF2(), setF20(), setF21(), setF22(), setF23(), setF24(), setF25(), setF26(), setF27(), setF28(), setF3(), setF4(), setF5(), setF6(), setF7(), setF8(), setF9(), setFunctionGroup1(), setFunctionGroup2(), setFunctionGroup3(), setFunctionGroup4(), setFunctionGroup5(), setLight(), setLocoDrive128(), setLocoDrive14(), setLocoDrive27(), setLocoDrive28(), setSmartSearch(), setSpeed(), and setSpeedsteps().
The documentation for this class was generated from the following files:
LocDecoder.h
LocDecoder.cpp