TBT::XpressNetClientInterface Class Reference
#include <XpressNetClientInterface.h>
Public Member Functions
XpressNetClientInterface (Manager *pManager, const char *ttyPath=`/dev/ttyO1`)
virtual ~XpressNetClientInterface ()
virtual void broadcastPowerStateChange (bool newState)
virtual void broadcastLocInfoChange (LocDecoder *pLoc)
virtual void broadcastEmergencyStop (void)
Protected Member Functions
XpressNetClient * findClient (const uint8_t &address)
Private Member Functions
void threadFunc (void)
Private Attributes
char * m_pTtyPath
int m_fdSerial
int m_fdStop
thread m_thread
map< uint8_t, XpressNetClient * > m_Clients
recursive_mutex m_MClients
Additional Inherited Members
Constructor & Destructor Documentation
XpressNetClientInterface()
TBT::XpressNetClientInterface::XpressNetClientInterface (Manager * pManager, const char * ttyPath = `/dev/ttyO1`)
References m_fdSerial, m_fdStop, m_pTtyPath, m_thread, and threadFunc().
 XpressNetClientInterface()
TBT::XpressNetClientInterface::~XpressNetClientInterface () [virtual]
References m_fdSerial, m_fdStop, m_pTtyPath, and m_thread.
Member Function Documentation
broadcastEmergencyStop()
void TBT::XpressNetClientInterface::broadcastEmergencyStop (void) [virtual]
Implements TBT::ClientInterface.
References m_fdSerial.
broadcastLocInfoChange()
void TBT::XpressNetClientInterface::broadcastLocInfoChange (LocDecoder * pLoc) [virtual]
Implements TBT::ClientInterface.
broadcastPowerStateChange()
void TBT::XpressNetClientInterface::broadcastPowerStateChange (bool newState) [virtual]
Implements TBT::ClientInterface.
References m_fdSerial.
findClient()
XpressNetClient * TBT::XpressNetClientInterface::findClient (const uint8_t & address) [protected]
References m_Clients, and m_MClients.
Referenced by threadFunc().
threadFunc()
void TBT::XpressNetClientInterface::threadFunc (void) [private]
References findClient(), TBT::Manager::findDecoder(), TBT::Manager::getCentralState(), TBT::Client::getInterface(), TBT::ClientInterface::getManager(), TBT::LocDecoder::getSpeedsteps(), m_fdSerial, m_fdStop, NBRXPRESSNETPOLLEVENTS, TBT::PowerOff, TBT::PowerOn, TBT::Manager::setEmergencyStop(), TBT::LocDecoder::setFunctionGroup1(), TBT::LocDecoder::setFunctionGroup2(), TBT::LocDecoder::setFunctionGroup3(), TBT::LocDecoder::setFunctionGroup4(), TBT::LocDecoder::setFunctionGroup5(), TBT::LocDecoder::setLocoDrive128(), TBT::LocDecoder::setLocoDrive14(), TBT::LocDecoder::setLocoDrive27(), TBT::LocDecoder::setLocoDrive28(), and TBT::Manager::setPowerState().
Referenced by XpressNetClientInterface().
Member Data Documentation
m_Clients
map<uint8_t, XpressNetClient*> TBT::XpressNetClientInterface::m_Clients [private]
Referenced by findClient().
m_fdSerial
int TBT::XpressNetClientInterface::m_fdSerial [private]
Referenced by broadcastEmergencyStop(), broadcastPowerStateChange(), threadFunc(), XpressNetClientInterface(), and ~XpressNetClientInterface().
m_fdStop
int TBT::XpressNetClientInterface::m_fdStop [private]
Referenced by threadFunc(), XpressNetClientInterface(), and ~XpressNetClientInterface().
m_MClients
recursive_mutex TBT::XpressNetClientInterface::m_MClients [private]
Referenced by findClient().
m_pTtyPath
char* TBT::XpressNetClientInterface::m_pTtyPath [private]
Referenced by XpressNetClientInterface(), and ~XpressNetClientInterface().
m_thread
thread TBT::XpressNetClientInterface::m_thread [private]
Referenced by XpressNetClientInterface(), and ~XpressNetClientInterface().
The documentation for this class was generated from the following files:
XpressNetClientInterface.h
XpressNetClientInterface.cpp