TBT::ClientInterface Class Reference
#include <ClientInterface.h>
Public Member Functions
ClientInterface (Manager *pManager)
virtual ~ClientInterface ()
Manager * getManager (void)
virtual void broadcastPowerStateChange (bool newState)=0
virtual void broadcastLocInfoChange (LocDecoder *pLoc)=0
virtual void broadcastEmergencyStop (void)=0
Protected Attributes
Manager * m_pManager
Constructor & Destructor Documentation
ClientInterface()
TBT::ClientInterface::ClientInterface (Manager * pManager)
 ClientInterface()
TBT::ClientInterface::~ClientInterface () [virtual]
Member Function Documentation
broadcastEmergencyStop()
virtual void TBT::ClientInterface::broadcastEmergencyStop (void) [pure virtual]
Implemented in TBT::UDPClientInterface, TBT::WSClientInterface, and TBT::XpressNetClientInterface.
Referenced by getManager().
broadcastLocInfoChange()
virtual void TBT::ClientInterface::broadcastLocInfoChange (LocDecoder * pLoc) [pure virtual]
Implemented in TBT::UDPClientInterface, TBT::WSClientInterface, and TBT::XpressNetClientInterface.
Referenced by getManager().
broadcastPowerStateChange()
virtual void TBT::ClientInterface::broadcastPowerStateChange (bool newState) [pure virtual]
Implemented in TBT::UDPClientInterface, TBT::WSClientInterface, and TBT::XpressNetClientInterface.
Referenced by getManager().
getManager()
Manager* TBT::ClientInterface::getManager (void) [inline]
References broadcastEmergencyStop(), broadcastLocInfoChange(), broadcastPowerStateChange(), and m_pManager.
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
Member Data Documentation
m_pManager
Manager* TBT::ClientInterface::m_pManager [protected]
Referenced by getManager().
The documentation for this class was generated from the following files:
ClientInterface.h
ClientInterface.cpp