TBT::Manager Class Reference
Class Manager represents 'the Boss' in the system.
#include <Manager.h>
Public Member Functions
Manager ()
class Manager constructor
virtual ~Manager ()
class Manager destructor
Decoder * findDecoder (uint16_t dccAddress)
returns pointer to decoder with address dccAddress or NULL if decoder doesn't exists.
void registerDecoder (Decoder *pDecoder)
registers (add) the decoder into the pool of decoders
void unregisterDecoder (Decoder *pDecoder)
unregisters (remove) the decoder from the pool of decoders
void broadcastLocInfoChanged (LocDecoder *pLoc)
sends message to all interfaces about the locdecoder
void setPowerState (PowerState newState)
sets the new powerstate and notifies all interfaces about the new state
void setEmergencyStop ()
sets the emergency stop flag and notifies all interfaces about the new state
void getSystemState (SystemState *pMsg)
copies the systemstate into pMsg
const uint8_t & getCentralState (void)
returns reference to the centralState of the unit
const uint8_t & getCentralStateEx (void)
returns reference to the centralStateEx of the unit
Private Attributes
SystemState m_SystemState
variable to hold the systemstate of the unit
recursive_mutex m_MSystemState
mutex to protect m_SystemState against concurrent access
vector< ClientInterface * > m_ClientInterfaces
all the active clientinterfaces
recursive_mutex m_MClientInterfaces
mutex to protect m_ClientInterfaces against concurrent access
map< uint16_t, Decoder * > m_Decoders
all the decoders in the system, indexed by DCC address
recursive_mutex m_MDecoders
mutex to protect m_Decoders against concurrent access
DccGenerator * m_pDccGenerator
pointer to the DCC generator
Detailed Description
Class Manager represents 'the Boss' in the system.
Class Manager is responsible for general supervision over the correct distribution of the different events through the whole system. It collects and keeps state information regarding the overall state of the system.
Constructor & Destructor Documentation
Manager()
TBT::Manager::Manager ()
class Manager constructor
Default constructor for class Manager.
Create a new Manager instance with the following interfaces:
UDPClientInterface
XpressNetClientInterface
WSClientInterface
then, create and start a DccGenerator
Parameters
none
Returns
none, a new Manager instance is created
Warning
It is quite obvious that there should be just one and only one instance of this class in the running application. Maybe I implement it as a singleton, don't know for now...
References m_ClientInterfaces, m_Decoders, m_MDecoders, and m_pDccGenerator.
 Manager()
TBT::Manager::~Manager () [virtual]
class Manager destructor
Destructor for class Manager
Destroy the instance by first deleting the DccGenerator and then deleting all clientInterfaces.
Parameters
none
Returns
none, the Manager instance is deleted.
References m_ClientInterfaces, and m_pDccGenerator.
Member Function Documentation
broadcastLocInfoChanged()
void TBT::Manager::broadcastLocInfoChanged (LocDecoder * pLoc)
sends message to all interfaces about the locdecoder
Manager::broadcastLocInfoChanged itterates over the pool of interfaces and informs each of them about the change in the state of LocDecoder pointed to by pLoc.
Parameters
pLoc pointer to LocDecoder who's state changed.
Returns
void
References m_ClientInterfaces, and m_MClientInterfaces.
Referenced by TBT::LocDecoder::setBusy(), TBT::LocDecoder::setDirection(), TBT::LocDecoder::setDualTraction(), TBT::LocDecoder::setF0(), TBT::LocDecoder::setF1(), TBT::LocDecoder::setF10(), TBT::LocDecoder::setF11(), TBT::LocDecoder::setF12(), TBT::LocDecoder::setF13(), TBT::LocDecoder::setF14(), TBT::LocDecoder::setF15(), TBT::LocDecoder::setF16(), TBT::LocDecoder::setF17(), TBT::LocDecoder::setF18(), TBT::LocDecoder::setF19(), TBT::LocDecoder::setF2(), TBT::LocDecoder::setF20(), TBT::LocDecoder::setF21(), TBT::LocDecoder::setF22(), TBT::LocDecoder::setF23(), TBT::LocDecoder::setF24(), TBT::LocDecoder::setF25(), TBT::LocDecoder::setF26(), TBT::LocDecoder::setF27(), TBT::LocDecoder::setF28(), TBT::LocDecoder::setF3(), TBT::LocDecoder::setF4(), TBT::LocDecoder::setF5(), TBT::LocDecoder::setF6(), TBT::LocDecoder::setF7(), TBT::LocDecoder::setF8(), TBT::LocDecoder::setF9(), TBT::LocDecoder::setFunctionGroup1(), TBT::LocDecoder::setFunctionGroup2(), TBT::LocDecoder::setFunctionGroup3(), TBT::LocDecoder::setFunctionGroup4(), TBT::LocDecoder::setFunctionGroup5(), TBT::LocDecoder::setLight(), TBT::LocDecoder::setLocoDrive128(), TBT::LocDecoder::setLocoDrive14(), TBT::LocDecoder::setLocoDrive27(), TBT::LocDecoder::setLocoDrive28(), TBT::LocDecoder::setSmartSearch(), TBT::LocDecoder::setSpeed(), and TBT::LocDecoder::setSpeedsteps().
findDecoder()
Decoder * TBT::Manager::findDecoder (uint16_t dccAddress)
returns pointer to decoder with address dccAddress or NULL if decoder doesn't exists.
Manager::findDecoder returns a pointer to the registered decoder with the specified DCC address. If the decoder isn't found, return NULL.
At this point we cannot create a new decoder instance because there is no way to determine what kind of decoder to create. (class Decoder is virtual)
Parameters
dccAddress the DCC address of the decoder to find
Returns
pointer to the decoder or NULL if the decoder doesn't appear in the list of registered decoders.
References m_Decoders, and m_MDecoders.
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
getCentralState()
const uint8_t& TBT::Manager::getCentralState (void) [inline]
returns reference to the centralState of the unit
CentralState layout
 bit 7 bit 6 bit 5 bit 4 bit 3 bit 2 bit 1 bit 0
 bit 7 bit 6 bit 5 bit 4 bit 3 bit 2 bit 1 bit 0
- - csProgrammingModeActive - - csShortCircuit cdTrackVoltageOff csEmergencyStop
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
getCentralStateEx()
const uint8_t& TBT::Manager::getCentralStateEx (void) [inline]
returns reference to the centralStateEx of the unit
CentralStateEx layout
 bit 7 bit 6 bit 5 bit 4 bit 3 bit 2 bit 1 bit 0
 bit 7 bit 6 bit 5 bit 4 bit 3 bit 2 bit 1 bit 0
- - - - cseShortCircuitInternal cseShortCircuitExternal csePowerLost cseHighTemperature
getSystemState()
void TBT::Manager::getSystemState (SystemState * pMsg)
copies the systemstate into pMsg
Manager::getSystemState generate the UDP message (Z21 LAN protocol) about the unit's systemstate. The user is responsible for allocating a buffer big enough to contain the returned message.
Parameters
pMsg : pointer to a struct SystemState variable.
Returns
void
References TBT::SystemState::DataLen, m_MSystemState, and m_SystemState.
Referenced by TBT::LocDecoder::getDccMessage(), and TBT::UDPClientInterface::threadFunc().
registerDecoder()
void TBT::Manager::registerDecoder (Decoder * pDecoder)
registers (add) the decoder into the pool of decoders
Manager::registerDecoder registers (add) the decoder pointed to by pDecoder into the pool of decoders. If there already exists a decoder with the same address in the pool, the existing pointer will be overwritten.
Warning
This situation can lead to a memoryleak.
Parameters
pDecoder pointer to the decoder to add into the pool
Returns
void
References TBT::Decoder::getDCCAddress(), m_Decoders, and m_MDecoders.
Referenced by TBT::Decoder::Decoder().
setEmergencyStop()
void TBT::Manager::setEmergencyStop ()
sets the emergency stop flag and notifies all interfaces about the new state
Manager::setEmergencyStop raises an emergencystop condition. All locdecoders shall be stopped immediatly but the power will remain on the tracks.
Parameters
none
Returns
void
References TBT::SystemState::CentralState, csEmergencyStop, m_ClientInterfaces, m_MClientInterfaces, m_MSystemState, and m_SystemState.
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
setPowerState()
void TBT::Manager::setPowerState (PowerState newState)
sets the new powerstate and notifies all interfaces about the new state
Manager::setPowerState set the powerstate of the system to the new state indicated by newState and informs each interface about the new state. In the case that newState is PowerOn, this function will cancel any pending emergencystop.
Parameters
newState member of enum PowerState
Returns
void
References TBT::SystemState::CentralState, csEmergencyStop, csTrackVoltageOff, m_ClientInterfaces, m_MClientInterfaces, m_MSystemState, m_SystemState, and TBT::PowerOn.
Referenced by TBT::XpressNetClientInterface::threadFunc(), and TBT::UDPClientInterface::threadFunc().
unregisterDecoder()
void TBT::Manager::unregisterDecoder (Decoder * pDecoder)
unregisters (remove) the decoder from the pool of decoders
Manager::unregisterDecoder unregisters (remove) the decoder pointed to by pDecoder from the pool of decoders. If the decoder wasn't prevoiusly registerd, i.e. it isn't in the pool, nothing changes.
Parameters
pDecoder pointer to the decoder to remove from the pool
Returns
void
References TBT::Decoder::getDCCAddress(), m_Decoders, and m_MDecoders.
Referenced by TBT::Decoder::~Decoder().
Member Data Documentation
m_ClientInterfaces
vector<ClientInterface*> TBT::Manager::m_ClientInterfaces [private]
all the active clientinterfaces
Referenced by broadcastLocInfoChanged(), Manager(), setEmergencyStop(), setPowerState(), and ~Manager().
m_Decoders
map<uint16_t, Decoder*> TBT::Manager::m_Decoders [private]
all the decoders in the system, indexed by DCC address
Referenced by findDecoder(), Manager(), registerDecoder(), and unregisterDecoder().
m_MClientInterfaces
recursive_mutex TBT::Manager::m_MClientInterfaces [private]
mutex to protect m_ClientInterfaces against concurrent access
Referenced by broadcastLocInfoChanged(), setEmergencyStop(), and setPowerState().
m_MDecoders
recursive_mutex TBT::Manager::m_MDecoders [private]
mutex to protect m_Decoders against concurrent access
Referenced by findDecoder(), Manager(), registerDecoder(), and unregisterDecoder().
m_MSystemState
recursive_mutex TBT::Manager::m_MSystemState [private]
mutex to protect m_SystemState against concurrent access
Referenced by getSystemState(), setEmergencyStop(), and setPowerState().
m_pDccGenerator
DccGenerator* TBT::Manager::m_pDccGenerator [private]
pointer to the DCC generator
Referenced by Manager(), and ~Manager().
m_SystemState
SystemState TBT::Manager::m_SystemState [private]
variable to hold the systemstate of the unit
Referenced by getSystemState(), setEmergencyStop(), and setPowerState().
The documentation for this class was generated from the following files:
Manager.h
Manager.cpp