TBT::UDPClientInterface Class Reference
#include <UDPClientInterface.h>
Public Member Functions
UDPClientInterface (Manager *pManager, const in_port_t &port=21105)
UDPClientInterface constructor.
virtual ~UDPClientInterface ()
UDPClientInterface destructor.
int getMySocket (void)
virtual void broadcastPowerStateChange (bool newState)
sends a notification to all clients about a powerstate change.
virtual void broadcastLocInfoChange (LocDecoder *pLoc)
sends a notification to all clients about the locdecoder.
virtual void broadcastEmergencyStop (void)
sends a notification to all clients about an emergencystop.
Protected Member Functions
UDPClient * findClient (const sockaddr_in &address)
returns pointer to client with specified address.
bool removeClient (UDPClient *pClient)
removes client with specified address and destroys it.
Private Member Functions
void threadFunc (void)
does the actual work in a separate thread.
Private Attributes
in_port_t m_port
thread m_thread
sockaddr_in m_sockaddr_me
int m_fdsock_me
int m_fdStop
vector< UDPClient * > sm_Clients
recursive_mutex sm_MClients
Additional Inherited Members
Detailed Description
Class UDPClientInterface represents the ClientInterface for UDP clients using the Z21 Lan Protocol.
Basics
Communication:
Communication with the Z21 protocol over UDP port 21105 or 21106. Control applications on the client (PC, App, ...) should primarily use port 21105. The communication is always asynchronous, i.e. between a request and the corresponding response other broadcast messages can occur.
It is expected that each client communicates with the Z21 once per minute, otherwise it will be removed from the list of active participants. If possible, a client should log off when exiting with the LAN_LOGOFF command.
Z21 Datagram layout
A Z21 datagram, i.e. a request or response is structured as follows:
Z21 Datagram Layout
 DataLen Header Data
 DataLen Header Data
2 Bytes 2 Bytes n Bytes
DataLen (little endian):
Total length over the entire data set including DataLen, Header and Data, i.e. DataLen = 2 + 2 + n.
Header (little endian):
Describes the command or protocol group.
Data:
Structure and length depend on command. Exact description see respective command.
Unless otherwise stated, the byte order is little-endian, i.e. first the low byte, then the high byte.
Constructor & Destructor Documentation
UDPClientInterface()
TBT::UDPClientInterface::UDPClientInterface (Manager * pManager, const in_port_t & port = 21105)
UDPClientInterface constructor.
The constructor of UDPClientInterface
initializes its base class
sets up an event file descriptor (m_fdStop) which is responsible for a clean shutdown of the worker thread.
sets up a socket file descriptor (m_fdsock_me) and initializes it for listening for incomming Z21 portocol datagrams.
sets up a worker thread and start the threadFunc to listen to incomming datagrams.
Parameters
pManager : pointer to the Manager instance.
port : The port on which to listen for incomming messages.
Returns
none : a new instance of type class UDPClientInterface is constructed.
References m_fdsock_me, m_fdStop, m_port, m_sockaddr_me, m_thread, and threadFunc().
 UDPClientInterface()
TBT::UDPClientInterface::~UDPClientInterface () [virtual]
UDPClientInterface destructor.
The destructor of UDPClientInterface
informs the worker thread to finish processing of incomming datagrams.
waits for the worker thread to finish.
cleans up open file descriptors
References m_fdsock_me, m_fdStop, and m_thread.
Member Function Documentation
broadcastEmergencyStop()
void TBT::UDPClientInterface::broadcastEmergencyStop (void) [virtual]
sends a notification to all clients about an emergencystop.
UDPClinetInterface::broadcastEmergencyStop informs each client about the raise of an emergency stop.
Parameters
none
Returns
void
Implements TBT::ClientInterface.
References sm_Clients, and sm_MClients.
broadcastLocInfoChange()
void TBT::UDPClientInterface::broadcastLocInfoChange (LocDecoder * pLoc) [virtual]
sends a notification to all clients about the locdecoder.
UDPClientInterface::broadcastLocInfoChange informs each client about changes in the state of a LocDecoder.
Parameters
pLoc : pointer to the LocDecoder instance whoes state changed.
Returns
void
Implements TBT::ClientInterface.
References sm_Clients, and sm_MClients.
broadcastPowerStateChange()
void TBT::UDPClientInterface::broadcastPowerStateChange (bool newState) [virtual]
sends a notification to all clients about a powerstate change.
UDPClientInterface::broadcastPowerStateChange informs each client about a power state change.
Parameters
newState : bool true if the power is applied to the track, false otherwise.
Returns
void
Implements TBT::ClientInterface.
References sm_Clients, and sm_MClients.
findClient()
UDPClient * TBT::UDPClientInterface::findClient (const sockaddr_in & address) [protected]
returns pointer to client with specified address.
UDPClientInterface::findClient returns a pointer to an UDPClient instance at the specified address. If the client doesn't exists, it is created.
Parameters
address : the socket address on which the client is addressed.
Returns
a pointer to the instance of the UDPClient.
References sm_Clients, and sm_MClients.
Referenced by threadFunc().
getMySocket()
int TBT::UDPClientInterface::getMySocket (void) [inline]
returns handle to the socket of the client.
UDPClientInterface::getMySocket returns the handle to the socket on which to send responses to the client.
Parameters
none
Returns
int : handle to socket on wich to send responses to.
removeClient()
bool TBT::UDPClientInterface::removeClient (UDPClient * pClient) [protected]
removes client with specified address and destroys it.
UDPClientInterface::removeClient removes a client from the pool of UDPClients and destroys the client if it exists.
Parameters
pClient : pointer to instance of class UDPClient to remove.
Returns
true if client is removed,
false if client didn't exists.
References sm_Clients, and sm_MClients.
Referenced by threadFunc().
threadFunc()
void TBT::UDPClientInterface::threadFunc (void) [private]
does the actual work in a separate thread.
UDPClientInterface::threadFunc runs in a separate thread. The function listen on the socket (m_fdsock_me) for incomming datagrams.
LAN_GET_SERIAL_NUMBER
read the serial number from the Z21
request:
 DataLen Headers Data
 DataLen Headers Data
0x04 0x00 0x10 0x00 --
response:
 DataLen Headers Data
 DataLen Headers Data
0x08 0x00 0x10 0x00 Serialnumber (32 bit, little endian)
LAN_GET_CODE
With this command, the SW feature scope of the Z21 can be checked and read out. This command is of particular interest for the hardware version `z21 start` in order to check whether driving and switching via LAN is blocked or allowed.
Request:
 DataLen Header Data
 DataLen Header Data
0x04 0x00 0x18 0x00 -
Response:
 DataLen Header Data
 DataLen Header Data
0x05 0x00 0x18 0x00 Code (8 Bit)
Code layout
 define Value Meaning
 define Value Meaning
Z21_NO_LOCK 0x00 No features locked
Z21_START_LOCKED 0x01 `z21 start` : Driving and switching disabled via LAN.
Z21_START_UNLOCKED 0x02 `z21 start` : all feature locks are removed
LAN_GET_HWINFO
With this command the hardware type and the firmware version of the Z21 can be read out.
Request:
 DataLen Header Data
 DataLen Header Data
0x04 0x00 0x1A 0x00 -
Response:
 DataLen Header Data
 DataLen Header Data
0x0C 0x00 0x1A 0x00 HwType 32 Bit(little endian) FW Version 32 Bit (little endian)
HwType 32 Bit
 define Value Meaning
 define Value Meaning
D_HWT_Z21_OLD 0x00000200 `Black Z21` (Hardware-version from 2012)
D_HWT_Z21_NEW 0x00000201 `Black Z21` (Hardware-version from 2013)
D_HWT_SMARTRAIL 0x00000202 `SmartRail` (from 2012)
D_HWT_z21_SMALL 0x00000203 `White z21` Starterset-version (from 2013)
D_HWT_z21_START 0x00000204 `z21 start` Starterset-version (from 2016)
The FW version is specified in BCD format.
LAN_LOGOFF
Log off this client from the system
request:
 DataLen Headers Data
 DataLen Headers Data
0x04 0x00 0x30 0x00 --
response: none
When logging out, use the same port number as when logging in.
Note: logging in occurs implicitly with the client's first command (e.g. LAN_SYSTEM_STATE_GETDATA, ...).
LAN_GET_BROADCASTFLAGS
Reading out the broadcast flags in the Z21.
Request:
 DataLen Headers Data
 DataLen Headers Data
0x04 0x00 0x51 0x00 --
Response:
 DataLen Headers Data
 DataLen Headers Data
0x08 0x00 0x51 0x00 Broadcast-Flags (32 Bit little endian)
Broadcast-Flags : see UDPClient::getBroadcastFlags
LAN_SYSTEMSTATE_GETDATA
Request the current system state.
Request:
 DataLen Headers Data
 DataLen Headers Data
0x04 0x00 0x85 0x00 -
response : see TBT::SystemState
LAN_LOCONET_FROM_LAN
From Z21 FW version 1.20.
With this message, a LAN client can write a message to the LocoNet bus.
Request:
 DataLen Headers Data
 DataLen Headers Data
0x04 + n 0x00 0xA2 0x00 LocoNet message incl. CKSUM
    n Bytes
LAN_RMBUS_GETDATA
Request the current status of the feedback.
Request:
 DataLen Headers Data
 DataLen Headers Data
0x05 0x00 0x81 0x00 Group index (1 Byte)
Response:
 DataLen Headers Data
 DataLen Headers Data
0x0F 0x00 0x80 0x00 Group index (1 Byte) Feedback status (10 bytes)
Group index :
0 --> Feedback status for address from 1 to 10
1 --> Feedback status for address from 11 to 20
Feedback status :
1 byte per feedback,
1 bit per input.
The assignment of feedback address and byte position is statically ascending.
Example: GroupIndex = 1 and feedback status = 0x01 0x00 0xC5 0x00 0x00 0x00 0x00 0x00 0x00 0x00 means `feedback 11, contact input 1; Feedback 13, contact input 8,7,3 and 1 `
LAN_RMBUS_PROGRAMMODULE
Change the feedback address.
Request:
 DataLen Headers Data
 DataLen Headers Data
0x05 0x00 0x82 0x00 Address (1 Byte)
Address: new address for the feedback module to be programmed. Supported value range: 0 and 1 ... 20.
Response: none
Warning
The programming command is output on the R-BUS until this command is sent again to Z21 with address = 0. During the programming process, no other feedback module may be connected on the R-BUS.
LAN_GET_LOCOMODE
Read the output format for a given locomotive address.
The output format (DCC, MM) can be stored persistently per locomotive address in the Z21. A maximum of 256 different locomotive addresses can be stored. Each address> = 256 is automatically DCC.
Request:
 DataLen Headers Data
 DataLen Headers Data
0x06 0x00 0x60 0x00 Loc-Address (16 Bit big endian)
Response:
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x60 0x00 Loc-Address (16 Bit big endian) Modus (8 bit)
Modus : see LocDecoder::getLocMode
LAN_X_SET_STOP
With the following command the emergency stop is raised. All Locs goes into speedstep 01, but the power is still feed to the rails.
request:
 DataLen Headers Data
 DataLen Headers Data
0x06 0x00 0x40 0x00 X-Header XOR-Byte
    0x80 0x80
response : see UDPClient::broadcastEmergencyStop
LAN_GET_TURNOUTMODE
Reading the settings for a given function decoder address (`Function Decoder` in the sense of `Accessory Decoder` RP-9.2.1). The output format (DCC, MM) can be stored persistently per function decoder address in the Z21. A maximum of 256 different function decoder addresses can be stored. Each Address> = 256 is automatically DCC.
Request:
 DataLen Headers Data
 DataLen Headers Data
0x06 0x00 0x70 0x00 Function Decoder Address (16 Bit big endian)
Response:
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x70 0x00 Function Decoder Address (16 Bit big endian) Modus (8 Bit)
Modus : see FunctionDecoder::getMode
At the LAN interface and in the Z21, the function decoder addresses are addressed from 0, in the visualization on the apps or on the multi-mouse, however, from 1. This is merely a decision of the visualization. Example: multiMaus switch address # 3, corresponds on the LAN and Z21 to address # 2.
LAN_X_GET_VERSION
With the following command the X-Bus version of the Z21 can be read out.
request:
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
    0x21 0x21 0x00
response:
 DataLen Headers Data
 DataLen Headers Data
0x09 0x00 0x40 0x00 X-Header DB0 DB1 DB2 XOR-Byte
    0x63 0x21 0x30 0x12 0x60
DB1 --> X-Bus Version (3.0)
DB2 --> ID (Z21 = 0x12)
LAN_X_GET_STATUS
with the following command the system's status can be read out.
request:
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
    0x21 0x24 0x05
response:
 DataLen Headers Data
 DataLen Headers Data
0x08 0x00 0x40 0x00 X-Header DB0 DB1 XOR-Byte
    0x62 0x22 CentralState XOR-Byte
The system status is identical to the centralState, which is supplied in SystemStatus.
See also
Manager::getCentralState
LAN_X_SET_TRACK_POWER_OFF
With the following command the trackpower is switched off.
request:
 DataLen Header Data
 DataLen Header Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
    0x21 0x80 0xA1
response: see UDPClient::broadcastPowerStateChange
LAN_X_SET_TRACK_POWER_ON
With the following command the trackpower is switched on. This cancels a pending emergencystop or programmingmode.
request:
 DataLen Header Data
 DataLen Header Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
    0x21 0x81 0xA0
response: see UDPClient::broadcastPowerStateChange
References findClient(), TBT::Manager::findDecoder(), TBT::UDPClient::getBroadcastFlags(), TBT::Manager::getCentralState(), TBT::Decoder::getDCCAddress(), TBT::LocDecoder::getF0(), TBT::LocDecoder::getF1(), TBT::LocDecoder::getF10(), TBT::LocDecoder::getF11(), TBT::LocDecoder::getF12(), TBT::LocDecoder::getF13(), TBT::LocDecoder::getF14(), TBT::LocDecoder::getF15(), TBT::LocDecoder::getF16(), TBT::LocDecoder::getF17(), TBT::LocDecoder::getF18(), TBT::LocDecoder::getF19(), TBT::LocDecoder::getF2(), TBT::LocDecoder::getF20(), TBT::LocDecoder::getF21(), TBT::LocDecoder::getF22(), TBT::LocDecoder::getF23(), TBT::LocDecoder::getF24(), TBT::LocDecoder::getF25(), TBT::LocDecoder::getF26(), TBT::LocDecoder::getF27(), TBT::LocDecoder::getF28(), TBT::LocDecoder::getF3(), TBT::LocDecoder::getF4(), TBT::LocDecoder::getF5(), TBT::LocDecoder::getF6(), TBT::LocDecoder::getF7(), TBT::LocDecoder::getF8(), TBT::LocDecoder::getF9(), TBT::Client::getInterface(), TBT::LocDecoder::getLANLocInfo(), TBT::LocDecoder::getLocMode(), TBT::ClientInterface::getManager(), TBT::Manager::getSystemState(), m_fdsock_me, m_fdStop, TBT::PowerOff, TBT::PowerOn, removeClient(), TBT::UDPClient::setBroadcastFlags(), TBT::Manager::setEmergencyStop(), TBT::LocDecoder::setF0(), TBT::LocDecoder::setF1(), TBT::LocDecoder::setF10(), TBT::LocDecoder::setF11(), TBT::LocDecoder::setF12(), TBT::LocDecoder::setF13(), TBT::LocDecoder::setF14(), TBT::LocDecoder::setF15(), TBT::LocDecoder::setF16(), TBT::LocDecoder::setF17(), TBT::LocDecoder::setF18(), TBT::LocDecoder::setF19(), TBT::LocDecoder::setF2(), TBT::LocDecoder::setF20(), TBT::LocDecoder::setF21(), TBT::LocDecoder::setF22(), TBT::LocDecoder::setF23(), TBT::LocDecoder::setF24(), TBT::LocDecoder::setF25(), TBT::LocDecoder::setF26(), TBT::LocDecoder::setF27(), TBT::LocDecoder::setF28(), TBT::LocDecoder::setF3(), TBT::LocDecoder::setF4(), TBT::LocDecoder::setF5(), TBT::LocDecoder::setF6(), TBT::LocDecoder::setF7(), TBT::LocDecoder::setF8(), TBT::LocDecoder::setF9(), TBT::LocDecoder::setLocMode(), TBT::LocDecoder::setLocoDrive128(), TBT::LocDecoder::setLocoDrive14(), TBT::LocDecoder::setLocoDrive28(), and TBT::Manager::setPowerState().
Referenced by UDPClientInterface().
Member Data Documentation
m_fdsock_me
int TBT::UDPClientInterface::m_fdsock_me [private]
Referenced by threadFunc(), UDPClientInterface(), and ~UDPClientInterface().
m_fdStop
int TBT::UDPClientInterface::m_fdStop [private]
Referenced by threadFunc(), UDPClientInterface(), and ~UDPClientInterface().
m_port
in_port_t TBT::UDPClientInterface::m_port [private]
Referenced by UDPClientInterface().
m_sockaddr_me
sockaddr_in TBT::UDPClientInterface::m_sockaddr_me [private]
Referenced by UDPClientInterface().
m_thread
thread TBT::UDPClientInterface::m_thread [private]
Referenced by UDPClientInterface(), and ~UDPClientInterface().
sm_Clients
vector<UDPClient*> TBT::UDPClientInterface::sm_Clients [private]
Referenced by broadcastEmergencyStop(), broadcastLocInfoChange(), broadcastPowerStateChange(), findClient(), and removeClient().
sm_MClients
recursive_mutex TBT::UDPClientInterface::sm_MClients [private]
Referenced by broadcastEmergencyStop(), broadcastLocInfoChange(), broadcastPowerStateChange(), findClient(), and removeClient().
The documentation for this class was generated from the following files:
UDPClientInterface.h
UDPClientInterface.cpp