TBT::WSClientInterface Class Reference
#include <WSClientInterface.h>
Public Member Functions
WSClientInterface (Manager *pManager, const char *port=WS_PORT)
virtual ~WSClientInterface ()
virtual void broadcastPowerStateChange (bool newState)
virtual void broadcastLocInfoChange (LocDecoder *pLoc)
virtual void broadcastEmergencyStop ()
Protected Attributes
char * m_port
volatile bool m_bContinue
thread m_thread
mg_mgr m_mgr
mg_connection * m_conn
Private Member Functions
void threadFunc (void)
Constructor & Destructor Documentation
WSClientInterface()
TBT::WSClientInterface::WSClientInterface (Manager * pManager, const char * port = WS_PORT)
References m_port, m_thread, and threadFunc().
 WSClientInterface()
TBT::WSClientInterface::~WSClientInterface () [virtual]
References m_bContinue, m_port, and m_thread.
Member Function Documentation
broadcastEmergencyStop()
void TBT::WSClientInterface::broadcastEmergencyStop (void) [virtual]
Implements TBT::ClientInterface.
References TBT::ev_handler_StateChange(), and m_mgr.
broadcastLocInfoChange()
void TBT::WSClientInterface::broadcastLocInfoChange (LocDecoder * pLoc) [virtual]
Implements TBT::ClientInterface.
broadcastPowerStateChange()
void TBT::WSClientInterface::broadcastPowerStateChange (bool newState) [virtual]
Implements TBT::ClientInterface.
References TBT::ev_handler_StateChange(), and m_mgr.
threadFunc()
void TBT::WSClientInterface::threadFunc (void) [private]
References TBT::ev_handler(), m_bContinue, m_conn, m_mgr, m_port, mg_bind(), mg_mgr_free(), mg_mgr_init(), mg_mgr_poll(), and mg_set_protocol_http_websocket().
Referenced by WSClientInterface().
Member Data Documentation
m_bContinue
volatile bool TBT::WSClientInterface::m_bContinue [protected]
Referenced by threadFunc(), and ~WSClientInterface().
m_conn
mg_connection* TBT::WSClientInterface::m_conn [protected]
Referenced by threadFunc().
m_mgr
mg_mgr TBT::WSClientInterface::m_mgr [protected]
Referenced by broadcastEmergencyStop(), broadcastPowerStateChange(), and threadFunc().
m_port
char* TBT::WSClientInterface::m_port [protected]
Referenced by threadFunc(), WSClientInterface(), and ~WSClientInterface().
m_thread
thread TBT::WSClientInterface::m_thread [protected]
Referenced by WSClientInterface(), and ~WSClientInterface().
The documentation for this class was generated from the following files:
WSClientInterface.h
WSClientInterface.cpp