Z21LANProtocolSystem
Functions
void TBT::UDPClientInterface::threadFunc (void)
does the actual work in a separate thread.
Detailed Description
Class UDPClientInterface represents the ClientInterface for UDP clients using the Z21 Lan Protocol.
Basics
Communication:
Communication with the Z21 protocol over UDP port 21105 or 21106. Control applications on the client (PC, App, ...) should primarily use port 21105. The communication is always asynchronous, i.e. between a request and the corresponding response other broadcast messages can occur.
It is expected that each client communicates with the Z21 once per minute, otherwise it will be removed from the list of active participants. If possible, a client should log off when exiting with the LAN_LOGOFF command.
Z21 Datagram layout
A Z21 datagram, i.e. a request or response is structured as follows:
 DataLen Header Data
 DataLen Header Data
2 bytes 2 bytes n bytes
DataLen (little endian):
Total length over the entire data set including DataLen, Header and Data, i.e. DataLen = 2 + 2 + n.
Header (little endian):
Describes the command or protocol group.
Data:
Structure and length depend on command. Exact description see respective command.
Unless otherwise stated, the byte order is little-endian, i.e. first the low byte, then the high byte.
System, Status and Version
Function Documentation
threadFunc()
void TBT::UDPClientInterface::threadFunc (void) [private]
does the actual work in a separate thread.
UDPClientInterface::threadFunc runs in a separate thread. The function listen on the socket (m_fdsock_me) for incomming datagrams.
LAN_GET_SERIAL_NUMBER
read the serial number from the Z21
request:
 DataLen Headers Data
 DataLen Headers Data
0x04 0x00 0x10 0x00 --
response:
 DataLen Headers Data
 DataLen Headers Data
0x08 0x00 0x10 0x00 Serialnumber (32 bit, little endian)
LAN_LOGOFF
Log off this client from the system
request:
 DataLen Headers Data
 DataLen Headers Data
0x04 0x00 0x30 0x00 --
response: none
When logging out, use the same port number as when logging in.
Note: logging in occurs implicitly with the client's first command (e.g. LAN_SYSTEM_STATE_GETDATA, ...).
LAN_X_GET_VERSION
With the following command the X-Bus version of the Z21 can be read out.
request:
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
    0x21 0x21 0x00
response:
 DataLen Headers Data
 DataLen Headers Data
0x09 0x00 0x40 0x00 X-Header DB0 DB1 DB2 XOR-Byte
    0x63 0x21 0x30 0x12 0x60
DB1 --> X-Bus Version (3.0)
DB2 --> ID (Z21 = 0x12)
LAN_X_GET_STATUS
with the following command the system's status can be read out.
request:
 DataLen Headers Data
 DataLen Headers Data
0x14 0x00 0x84 0x00 SystemState (16 Bytes)
response:
 DataLen Headers Data
 DataLen Headers Data
0x07 0x00 0x40 0x00 X-Header DB0 XOR-Byte
SystemState layout (INT16 is little-endian)
 Byte offset Type Name Unit note
 Byte offset Type Name Unit note
0 int16_t MainCurrent mA Main Track Current
2 int16_t ProgCurrent mA Programm Track Current
4 int16_t FilteredMainCurrent mA Smoothed Main Track Current
6 int16_t Temperature &#176;C Internal temperature
8 uint16_t SupplyVoltage mV Supply voltage
10 uint16_t VCCVoltage mV Voltage at the track
12 uint8_t CentralState bitmask see below
13 uint8_t CentralStateEx bitmask see below
14 uint8_t reserved
15 uint8_t reserved
The system status is identical to the centralState, which is supplied in SystemStatus.
CentralState layout
 7 6 5 4 3 2 1 0
 7 6 5 4 3 2 1 0
- - csProgrammingModeActive - - csShortCircuit cdTrackVoltageOff csEmergencyStop
CentralStateEx layout
 7 6 5 4 3 2 1 0
 7 6 5 4 3 2 1 0
- - - - cseShortCircuitInternal cseShortCircuitExternal csePowerLost cseHighTemperature
LAN_X_SET_TRACK_POWER_OFF
References TBT::UDPClientInterface::findClient(), TBT::Manager::findDecoder(), TBT::UDPClient::getBroadcastFlags(), TBT::Manager::getCentralState(), TBT::Decoder::getDCCAddress(), TBT::LocDecoder::getF0(), TBT::LocDecoder::getF1(), TBT::LocDecoder::getF10(), TBT::LocDecoder::getF11(), TBT::LocDecoder::getF12(), TBT::LocDecoder::getF13(), TBT::LocDecoder::getF14(), TBT::LocDecoder::getF15(), TBT::LocDecoder::getF16(), TBT::LocDecoder::getF17(), TBT::LocDecoder::getF18(), TBT::LocDecoder::getF19(), TBT::LocDecoder::getF2(), TBT::LocDecoder::getF20(), TBT::LocDecoder::getF21(), TBT::LocDecoder::getF22(), TBT::LocDecoder::getF23(), TBT::LocDecoder::getF24(), TBT::LocDecoder::getF25(), TBT::LocDecoder::getF26(), TBT::LocDecoder::getF27(), TBT::LocDecoder::getF28(), TBT::LocDecoder::getF3(), TBT::LocDecoder::getF4(), TBT::LocDecoder::getF5(), TBT::LocDecoder::getF6(), TBT::LocDecoder::getF7(), TBT::LocDecoder::getF8(), TBT::LocDecoder::getF9(), TBT::Client::getInterface(), TBT::LocDecoder::getLANLocInfo(), TBT::LocDecoder::getLocMode(), TBT::ClientInterface::getManager(), TBT::Manager::getSystemState(), TBT::UDPClientInterface::m_fdsock_me, TBT::UDPClientInterface::m_fdStop, TBT::PowerOff, TBT::PowerOn, TBT::UDPClientInterface::removeClient(), TBT::UDPClient::setBroadcastFlags(), TBT::Manager::setEmergencyStop(), TBT::LocDecoder::setF0(), TBT::LocDecoder::setF1(), TBT::LocDecoder::setF10(), TBT::LocDecoder::setF11(), TBT::LocDecoder::setF12(), TBT::LocDecoder::setF13(), TBT::LocDecoder::setF14(), TBT::LocDecoder::setF15(), TBT::LocDecoder::setF16(), TBT::LocDecoder::setF17(), TBT::LocDecoder::setF18(), TBT::LocDecoder::setF19(), TBT::LocDecoder::setF2(), TBT::LocDecoder::setF20(), TBT::LocDecoder::setF21(), TBT::LocDecoder::setF22(), TBT::LocDecoder::setF23(), TBT::LocDecoder::setF24(), TBT::LocDecoder::setF25(), TBT::LocDecoder::setF26(), TBT::LocDecoder::setF27(), TBT::LocDecoder::setF28(), TBT::LocDecoder::setF3(), TBT::LocDecoder::setF4(), TBT::LocDecoder::setF5(), TBT::LocDecoder::setF6(), TBT::LocDecoder::setF7(), TBT::LocDecoder::setF8(), TBT::LocDecoder::setF9(), TBT::LocDecoder::setLocMode(), TBT::LocDecoder::setLocoDrive128(), TBT::LocDecoder::setLocoDrive14(), TBT::LocDecoder::setLocoDrive28(), and TBT::Manager::setPowerState().
Referenced by TBT::UDPClientInterface::UDPClientInterface().