mongoose.c File Reference
#include `mongoose.h`
#include <stdarg.h>
#include <stdio.h>
#include <string.h>
#include <limits.h>
#include <stddef.h>
#include <sys/time.h>
#include <assert.h>
#include <stdlib.h>
#include <signal.h>
Classes
struct ctl_msg
union char64long16
struct mg_tun_frame
struct mg_tun_ssl_opts
struct mg_tun_client
struct mg_http_proto_data_file
struct mg_http_proto_data_chuncked
struct mg_http_endpoint
struct mg_http_multipart_stream
struct mg_reverse_proxy_data
struct mg_ws_proto_data
struct mg_http_proto_data
struct ws_mask_ctx
struct mg_dns_header
struct mg_resolve_async_request
Macros
#define CS_MONGOOSE_SRC_INTERNAL_H_
#define MBUF_REALLOC MG_REALLOC
#define MBUF_FREE MG_FREE
#define MG_SET_PTRPTR(_ptr, _v)
#define MG_INTERNAL static
#define MG_CTL_MSG_MESSAGE_SIZE 8192
#define MIN(a, b) ((a) < (b) ? (a) : (b))
#define CS_COMMON_MG_MEM_H_
#define MG_MALLOC malloc
#define MG_CALLOC calloc
#define MG_REALLOC realloc
#define MG_FREE free
#define CS_COMMON_CS_DBG_H_
#define CS_ENABLE_DEBUG 0
#define CS_LOG_ENABLE_TS_DIFF 0
#define LOG(l, x)
#define DBG(x)
#define NUM_UPPERCASES ('Z' - 'A' + 1)
#define NUM_LETTERS (NUM_UPPERCASES * 2)
#define NUM_DIGITS ('9' - '0' + 1)
#define BASE64_ENCODE_BODY
#define BASE64_OUT(ch)
#define BASE64_FLUSH()
#define CS_COMMON_CS_DIRENT_H_
#define CS_COMMON_CS_ENDIAN_H_
#define F1(x, y, z) (z ^ (x & (y ^ z)))
#define F2(x, y, z) F1(z, x, y)
#define F3(x, y, z) (x ^ y ^ z)
#define F4(x, y, z) (y ^ (x | ~z))
#define MD5STEP(f, w, x, y, z, data, s) (w += f(x, y, z) + data, w = w << s | w >> (32 - s), w += x)
#define SHA1HANDSOFF
#define rol(value, bits) (((value) << (bits)) | ((value) >> (32 - (bits))))
#define blk(i)
#define R0(v, w, x, y, z, i)
#define R1(v, w, x, y, z, i)
#define R2(v, w, x, y, z, i)
#define R3(v, w, x, y, z, i)
#define R4(v, w, x, y, z, i)
#define C_DISABLE_BUILTIN_SNPRINTF 0
#define C_SNPRINTF_APPEND_CHAR(ch)
#define C_SNPRINTF_FLAG_ZERO 1
#define CS_MONGOOSE_SRC_TUN_H_
#define MG_TUN_RECONNECT_INTERVAL 1
#define MG_TUN_PROTO_NAME `mg_tun`
#define MG_TUN_DATA_FRAME 0x0
#define MG_TUN_F_END_STREAM 0x1
#define MG_MAX_HOST_LEN 200
#define MG_COPY_COMMON_CONNECTION_OPTIONS(dst, src) memcpy(dst, src, sizeof(*dst));
#define _MG_ALLOWED_CONNECT_FLAGS_MASK
#define _MG_CALLBACK_MODIFIABLE_FLAGS_MASK
#define intptr_t long
#define CS_MONGOOSE_SRC_NET_IF_SOCKET_H_
#define MG_ENABLE_NET_IF_SOCKET MG_NET_IF == MG_NET_IF_SOCKET
#define CS_MONGOOSE_SRC_NET_IF_TUN_H_
#define CS_MONGOOSE_SRC_NET_IF_SOCKS_H_
#define MG_TCP_RECV_BUFFER_SIZE 1024
#define MG_UDP_RECV_BUFFER_SIZE 1500
#define _MG_F_FD_CAN_READ 1
#define _MG_F_FD_CAN_WRITE 1 << 1
#define _MG_F_FD_ERROR 1 << 2
#define MG_SOCKET_IFACE_VTABLE
#define MG_TCP_RECV_BUFFER_SIZE 1024
#define MG_UDP_RECV_BUFFER_SIZE 1500
#define MG_TUN_IFACE_VTABLE
#define HEXTOI(x) (isdigit(x) ? x - '0' : x - 'W')
#define MG_WEBSOCKET_PING_INTERVAL_SECONDS 5
#define MAX(a, b) ((a) > (b) ? (a) : (b))
#define MG_DEFAULT_NAMESERVER `8.8.8.8`
#define CS_COMMON_PLATFORMS_SIMPLELINK_SL_FS_SLFS_H_
#define CS_COMMON_PLATFORMS_SIMPLELINK_SL_NET_IF_H_
#define MG_ENABLE_NET_IF_SIMPLELINK MG_NET_IF == MG_NET_IF_SIMPLELINK
#define CS_COMMON_PLATFORMS_LWIP_MG_NET_IF_LWIP_H_
#define MG_ENABLE_NET_IF_LWIP_LOW_LEVEL MG_NET_IF == MG_NET_IF_LWIP_LOW_LEVEL
#define CS_COMMON_PLATFORMS_PIC32_NET_IF_H_
#define MG_ENABLE_NET_IF_PIC32 MG_NET_IF == MG_NET_IF_PIC32
Typedefs
typedef int cs_dirent_dummy
Enumerations
enum cs_log_level {
LL_NONE = -1,
LL_ERROR = 0,
LL_WARN = 1,
LL_INFO = 2,
LL_DEBUG = 3,
LL_VERBOSE_DEBUG = 4,
_LL_MIN = -2,
_LL_MAX = 5
 }
enum mg_http_proto_data_type { DATA_NONE,
DATA_FILE,
DATA_PUT
 }
enum mg_http_multipart_stream_state {
MPS_BEGIN,
MPS_WAITING_FOR_BOUNDARY,
MPS_WAITING_FOR_CHUNK,
MPS_GOT_CHUNK,
MPS_GOT_BOUNDARY,
MPS_FINALIZE,
MPS_FINISHED
 }
Functions
MG_INTERNAL struct mg_connection * mg_do_connect (struct mg_connection *nc, int proto, union socket_address *sa)
MG_INTERNAL int mg_parse_address (const char *str, union socket_address *sa, int *proto, char *host, size_t host_len)
MG_INTERNAL void mg_call (struct mg_connection *nc, mg_event_handler_t ev_handler, void *user_data, int ev, void *ev_data)
void mg_forward (struct mg_connection *from, struct mg_connection *to)
MG_INTERNAL void mg_add_conn (struct mg_mgr *mgr, struct mg_connection *c)
MG_INTERNAL void mg_remove_conn (struct mg_connection *c)
MG_INTERNAL struct mg_connection * mg_create_connection (struct mg_mgr *mgr, mg_event_handler_t callback, struct mg_add_sock_opts opts)
MG_INTERNAL int parse_mqtt (struct mbuf *io, struct mg_mqtt_message *mm)
MG_INTERNAL size_t mg_handle_chunked (struct mg_connection *nc, struct http_message *hm, char *buf, size_t blen)
MG_INTERNAL void mg_ws_handler (struct mg_connection *nc, int ev, void *ev_data MG_UD_ARG(void *user_data))
MG_INTERNAL void mg_ws_handshake (struct mg_connection *nc, const struct mg_str *key, struct http_message *)
MG_INTERNAL int mg_get_errno (void)
MG_INTERNAL void mg_close_conn (struct mg_connection *conn)
void cs_log_set_level (enum cs_log_level level)
void cs_log_set_filter (const char *source_file_name)
int cs_log_print_prefix (enum cs_log_level level, const char *func, const char *filename)
static void cs_base64_emit_code (struct cs_base64_ctx *ctx, int v)
static void cs_base64_emit_chunk (struct cs_base64_ctx *ctx)
void cs_base64_init (struct cs_base64_ctx *ctx, cs_base64_putc_t b64_putc, void *user_data)
void cs_base64_update (struct cs_base64_ctx *ctx, const char *str, size_t len)
void cs_base64_finish (struct cs_base64_ctx *ctx)
void cs_base64_encode (const unsigned char *src, int src_len, char *dst)
static unsigned char from_b64 (unsigned char ch)
int cs_base64_decode (const unsigned char *s, int len, char *dst, int *dec_len)
double cs_time (void)
double cs_timegm (const struct tm *tm)
static void byteReverse (unsigned char *buf, unsigned longs)
void cs_md5_init (cs_md5_ctx *ctx)
static void cs_md5_transform (uint32_t buf[4], uint32_t const in[16])
void cs_md5_update (cs_md5_ctx *ctx, const unsigned char *buf, size_t len)
void cs_md5_final (unsigned char digest[16], cs_md5_ctx *ctx)
static uint32_t blk0 (union char64long16 *block, int i)
void cs_sha1_transform (uint32_t state[5], const unsigned char buffer[64])
void cs_sha1_init (cs_sha1_ctx *context)
void cs_sha1_update (cs_sha1_ctx *context, const unsigned char *data, uint32_t len)
void cs_sha1_final (unsigned char digest[20], cs_sha1_ctx *context)
void cs_hmac_sha1 (const unsigned char *key, size_t keylen, const unsigned char *data, size_t datalen, unsigned char out[20])
void mbuf_init (struct mbuf *mbuf, size_t initial_size) WEAK
void mbuf_free (struct mbuf *mbuf) WEAK
void mbuf_resize (struct mbuf *a, size_t new_size) WEAK
void mbuf_trim (struct mbuf *mbuf) WEAK
size_t mbuf_insert (struct mbuf *a, size_t off, const void *buf, size_t) WEAK
size_t mbuf_append (struct mbuf *a, const void *buf, size_t len) WEAK
void mbuf_remove (struct mbuf *mb, size_t n) WEAK
int mg_ncasecmp (const char *s1, const char *s2, size_t len) WEAK
struct mg_str mg_mk_str (const char *s) WEAK
struct mg_str mg_mk_str_n (const char *s, size_t len) WEAK
int mg_vcmp (const struct mg_str *str1, const char *str2) WEAK
int mg_vcasecmp (const struct mg_str *str1, const char *str2) WEAK
static struct mg_str mg_strdup_common (const struct mg_str s, int nul_terminate)
struct mg_str mg_strdup (const struct mg_str s) WEAK
struct mg_str mg_strdup_nul (const struct mg_str s) WEAK
const char * mg_strchr (const struct mg_str s, int c) WEAK
int mg_strcmp (const struct mg_str str1, const struct mg_str str2) WEAK
int mg_strncmp (const struct mg_str, const struct mg_str, size_t n) WEAK
const char * mg_strstr (const struct mg_str haystack, const struct mg_str needle) WEAK
size_t c_strnlen (const char *s, size_t maxlen) WEAK
static int c_itoa (char *buf, size_t buf_size, int64_t num, int base, int flags, int field_width)
int c_vsnprintf (char *buf, size_t buf_size, const char *fmt, va_list ap) WEAK
int c_snprintf (char *buf, size_t buf_size, const char *fmt,...) WEAK
const char * c_strnstr (const char *s, const char *find, size_t slen) WEAK
void cs_to_hex (char *to, const unsigned char *p, size_t len) WEAK
static int fourbit (int ch)
void cs_from_hex (char *to, const char *p, size_t len) WEAK
static int str_util_lowercase (const char *s)
int mg_casecmp (const char *s1, const char *s2) WEAK
int mg_asprintf (char **buf, size_t size, const char *fmt,...) WEAK
int mg_avprintf (char **buf, size_t size, const char *fmt, va_list ap) WEAK
const char * mg_next_comma_list_entry (const char *, struct mg_str *, struct mg_str *)
struct mg_str mg_next_comma_list_entry_n (struct mg_str list, struct mg_str *val, struct mg_str *eq_val) WEAK
int mg_match_prefix_n (const struct mg_str, const struct mg_str)
int mg_match_prefix (const char *, int, const char *)
struct mg_connection * mg_tun_bind_opt (struct mg_mgr *mgr, const char *dispatcher, MG_CB(mg_event_handler_t handler, void *user_data), struct mg_bind_opts opts)
int mg_tun_parse_frame (void *data, size_t len, struct mg_tun_frame *frame)
void mg_tun_send_frame (struct mg_connection *ws, uint32_t stream_id, uint8_t type, uint8_t flags, struct mg_str msg)
void mg_tun_destroy_client (struct mg_tun_client *client)
void mg_if_timer (struct mg_connection *c, double now)
void mg_if_poll (struct mg_connection *nc, time_t now)
void mg_destroy_conn (struct mg_connection *conn, int destroy_if)
void mg_mgr_init (struct mg_mgr *m, void *user_data)
void mg_mgr_init_opt (struct mg_mgr *m, void *user_data, struct mg_mgr_init_opts opts)
void mg_mgr_free (struct mg_mgr *m)
time_t mg_mgr_poll (struct mg_mgr *m, int timeout_ms)
int mg_vprintf (struct mg_connection *nc, const char *fmt, va_list ap)
int mg_printf (struct mg_connection *conn, const char *fmt,...)
MG_INTERNAL struct mg_connection * mg_create_connection_base (struct mg_mgr *mgr, mg_event_handler_t callback, struct mg_add_sock_opts opts)
struct mg_connection * mg_if_accept_new_conn (struct mg_connection *lc)
void mg_if_accept_tcp_cb (struct mg_connection *nc, union socket_address *sa, size_t sa_len)
void mg_send (struct mg_connection *nc, const void *buf, int len)
void mg_if_sent_cb (struct mg_connection *nc, int num_sent)
MG_INTERNAL void mg_recv_common (struct mg_connection *nc, void *buf, int len, int own)
void mg_if_recv_tcp_cb (struct mg_connection *nc, void *buf, int len, int own)
void mg_if_recv_udp_cb (struct mg_connection *nc, void *buf, int len, union socket_address *sa, size_t sa_len)
void mg_if_connect_cb (struct mg_connection *nc, int err)
static void resolve_cb (struct mg_dns_message *msg, void *data, enum mg_resolve_err e)
struct mg_connection * mg_connect (struct mg_mgr *mgr, const char *address, MG_CB(mg_event_handler_t callback, void *user_data))
struct mg_connection * mg_connect_opt (struct mg_mgr *mgr, const char *address, MG_CB(mg_event_handler_t callback, void *user_data), struct mg_connect_opts opts)
struct mg_connection * mg_bind (struct mg_mgr *srv, const char *address, MG_CB(mg_event_handler_t event_handler, void *user_data))
struct mg_connection * mg_bind_opt (struct mg_mgr *mgr, const char *address, MG_CB(mg_event_handler_t callback, void *user_data), struct mg_bind_opts opts)
struct mg_connection * mg_next (struct mg_mgr *s, struct mg_connection *conn)
static int isbyte (int n)
static int parse_net (const char *spec, uint32_t *net, uint32_t *mask)
int mg_check_ip_acl (const char *acl, uint32_t remote_ip)
double mg_set_timer (struct mg_connection *c, double timestamp)
void mg_sock_set (struct mg_connection *nc, sock_t sock)
void mg_if_get_conn_addr (struct mg_connection *nc, int remote, union socket_address *sa)
struct mg_connection * mg_add_sock_opt (struct mg_mgr *s, sock_t sock, MG_CB(mg_event_handler_t callback, void *user_data), struct mg_add_sock_opts opts)
struct mg_connection * mg_add_sock (struct mg_mgr *s, sock_t sock, MG_CB(mg_event_handler_t callback, void *user_data))
double mg_time (void)
struct mg_connection * mg_tun_if_find_conn (struct mg_tun_client *client, uint32_t stream_id)
struct mg_iface * mg_if_create_iface (const struct mg_iface_vtable *vtable, struct mg_mgr *mgr)
struct mg_iface * mg_find_iface (struct mg_mgr *mgr, const struct mg_iface_vtable *vtable, struct mg_iface *from)
static sock_t mg_open_listening_socket (union socket_address *sa, int type, int proto)
void mg_set_non_blocking_mode (sock_t sock)
static int mg_is_error (void)
void mg_socket_if_connect_tcp (struct mg_connection *nc, const union socket_address *sa)
void mg_socket_if_connect_udp (struct mg_connection *nc)
int mg_socket_if_listen_tcp (struct mg_connection *nc, union socket_address *sa)
int mg_socket_if_listen_udp (struct mg_connection *nc, union socket_address *sa)
void mg_socket_if_tcp_send (struct mg_connection *nc, const void *buf, size_t len)
void mg_socket_if_udp_send (struct mg_connection *nc, const void *buf, size_t len)
void mg_socket_if_recved (struct mg_connection *nc, size_t len)
int mg_socket_if_create_conn (struct mg_connection *nc)
void mg_socket_if_destroy_conn (struct mg_connection *nc)
static int mg_accept_conn (struct mg_connection *lc)
static void mg_write_to_socket (struct mg_connection *nc)
MG_INTERNAL size_t recv_avail_size (struct mg_connection *conn, size_t max)
static void mg_handle_tcp_read (struct mg_connection *conn)
static int mg_recvfrom (struct mg_connection *nc, union socket_address *sa, socklen_t *sa_len, char **buf)
static void mg_handle_udp_read (struct mg_connection *nc)
void mg_mgr_handle_conn (struct mg_connection *nc, int fd_flags, double now)
void mg_socket_if_sock_set (struct mg_connection *nc, sock_t sock)
void mg_socket_if_init (struct mg_iface *iface)
void mg_socket_if_free (struct mg_iface *iface)
void mg_socket_if_add_conn (struct mg_connection *nc)
void mg_socket_if_remove_conn (struct mg_connection *nc)
void mg_add_to_set (sock_t sock, fd_set *set, sock_t *max_fd)
time_t mg_socket_if_poll (struct mg_iface *iface, int timeout_ms)
static void mg_sock_get_addr (sock_t sock, int remote, union socket_address *sa)
void mg_sock_to_str (sock_t sock, char *buf, size_t len, int flags)
void mg_socket_if_get_conn_addr (struct mg_connection *nc, int remote, union socket_address *sa)
void mg_tun_if_connect_tcp (struct mg_connection *nc, const union socket_address *sa)
void mg_tun_if_connect_udp (struct mg_connection *nc)
int mg_tun_if_listen_tcp (struct mg_connection *nc, union socket_address *sa)
int mg_tun_if_listen_udp (struct mg_connection *nc, union socket_address *sa)
void mg_tun_if_tcp_send (struct mg_connection *nc, const void *buf, size_t len)
void mg_tun_if_udp_send (struct mg_connection *nc, const void *buf, size_t len)
void mg_tun_if_recved (struct mg_connection *nc, size_t len)
int mg_tun_if_create_conn (struct mg_connection *nc)
void mg_tun_if_destroy_conn (struct mg_connection *nc)
void mg_tun_if_sock_set (struct mg_connection *nc, sock_t sock)
void mg_tun_if_init (struct mg_iface *iface)
void mg_tun_if_free (struct mg_iface *iface)
void mg_tun_if_add_conn (struct mg_connection *nc)
void mg_tun_if_remove_conn (struct mg_connection *nc)
time_t mg_tun_if_poll (struct mg_iface *iface, int timeout_ms)
void mg_tun_if_get_conn_addr (struct mg_connection *nc, int remote, union socket_address *sa)
static void parse_uri_component (const char **p, const char *end, const char *seps, struct mg_str *res)
int mg_parse_uri (const struct mg_str uri, struct mg_str *scheme, struct mg_str *user_info, struct mg_str *host, unsigned int *port, struct mg_str *path, struct mg_str *query, struct mg_str *fragment)
int mg_normalize_uri_path (const struct mg_str *in, struct mg_str *out)
int mg_assemble_uri (const struct mg_str *scheme, const struct mg_str *user_info, const struct mg_str *host, unsigned int port, const struct mg_str *path, const struct mg_str *query, const struct mg_str *fragment, int normalize_path, struct mg_str *uri)
static void mg_http_conn_destructor (void *proto_data)
struct mg_connection * mg_connect_http_base (struct mg_mgr *mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data), struct mg_connect_opts opts, const char *scheme1, const char *scheme2, const char *scheme_ssl1, const char *scheme_ssl2, const char *url, struct mg_str *path, struct mg_str *user_info, struct mg_str *host)
static struct mg_http_proto_data * mg_http_get_proto_data (struct mg_connection *c)
static void mg_http_free_proto_data_endpoints (struct mg_http_endpoint **ep)
static void mg_http_free_reverse_proxy_data (struct mg_reverse_proxy_data *rpd)
static int mg_http_get_request_len (const char *s, int buf_len)
static const char * mg_http_parse_headers (const char *s, const char *end, int len, struct http_message *req)
int mg_parse_http (const char *s, int n, struct http_message *hm, int is_req)
struct mg_str * mg_get_http_header (struct http_message *hm, const char *name)
static size_t mg_http_parse_chunk (char *buf, size_t len, char **chunk_data, size_t *chunk_len)
struct mg_http_endpoint * mg_http_get_endpoint_handler (struct mg_connection *nc, struct mg_str *uri_path)
static void mg_http_call_endpoint_handler (struct mg_connection *nc, int ev, struct http_message *hm)
static void deliver_chunk (struct mg_connection *c, struct http_message *hm, int req_len)
void mg_http_handler (struct mg_connection *nc, int ev, void *ev_data MG_UD_ARG(void *user_data))
static size_t mg_get_line_len (const char *buf, size_t buf_len)
void mg_set_protocol_http_websocket (struct mg_connection *nc)
const char * mg_status_message (int status_code)
void mg_send_response_line_s (struct mg_connection *nc, int status_code, const struct mg_str extra_headers)
void mg_send_response_line (struct mg_connection *nc, int status_code, const char *extra_headers)
void mg_http_send_redirect (struct mg_connection *nc, int status_code, const struct mg_str location, const struct mg_str extra_headers)
void mg_send_head (struct mg_connection *c, int status_code, int64_t content_length, const char *extra_headers)
void mg_http_send_error (struct mg_connection *nc, int code, const char *reason)
int mg_url_decode (const char *src, int src_len, char *dst, int dst_len, int is_form_url_encoded)
int mg_get_http_var (const struct mg_str *buf, const char *name, char *dst, size_t dst_len)
void mg_send_http_chunk (struct mg_connection *nc, const char *buf, size_t len)
void mg_printf_http_chunk (struct mg_connection *nc, const char *fmt,...)
void mg_printf_html_escape (struct mg_connection *nc, const char *fmt,...)
int mg_http_parse_header (struct mg_str *hdr, const char *var_name, char *buf, size_t buf_size)
int mg_get_http_basic_auth (struct http_message *hm, char *user, size_t user_len, char *pass, size_t pass_len)
int mg_parse_http_basic_auth (struct mg_str *hdr, char *user, size_t user_len, char *pass, size_t pass_len)
struct mg_connection * mg_connect_http_opt (struct mg_mgr *mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data), struct mg_connect_opts opts, const char *url, const char *extra_headers, const char *post_data)
struct mg_connection * mg_connect_http (struct mg_mgr *mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data), const char *url, const char *extra_headers, const char *post_data)
size_t mg_parse_multipart (const char *buf, size_t buf_len, char *var_name, size_t var_name_len, char *file_name, size_t file_name_len, const char **data, size_t *data_len)
void mg_register_http_endpoint_opt (struct mg_connection *nc, const char *uri_path, mg_event_handler_t handler, struct mg_http_endpoint_opts opts)
void mg_register_http_endpoint (struct mg_connection *nc, const char *uri_path, MG_CB(mg_event_handler_t handler, void *user_data))
static int mg_is_ws_fragment (unsigned char flags)
static int mg_is_ws_first_fragment (unsigned char flags)
static void mg_handle_incoming_websocket_frame (struct mg_connection *nc, struct websocket_message *wsm)
static struct mg_ws_proto_data * mg_ws_get_proto_data (struct mg_connection *nc)
static int mg_deliver_websocket_data (struct mg_connection *nc)
static uint32_t mg_ws_random_mask (void)
static void mg_send_ws_header (struct mg_connection *nc, int op, size_t len, struct ws_mask_ctx *ctx)
static void mg_ws_mask_frame (struct mbuf *mbuf, struct ws_mask_ctx *ctx)
void mg_send_websocket_frame (struct mg_connection *nc, int op, const void *data, size_t len)
void mg_send_websocket_framev (struct mg_connection *nc, int op, const struct mg_str *strv, int strvcnt)
void mg_printf_websocket_frame (struct mg_connection *nc, int op, const char *fmt,...)
void mg_hash_sha1_v (size_t num_msgs, const uint8_t *msgs[], const size_t *msg_lens, uint8_t *digest)
void mg_send_websocket_handshake2 (struct mg_connection *nc, const char *path, const char *host, const char *protocol, const char *extra_headers)
void mg_send_websocket_handshake3 (struct mg_connection *nc, const char *path, const char *host, const char *protocol, const char *extra_headers, const char *user, const char *pass)
void mg_send_websocket_handshake3v (struct mg_connection *nc, const struct mg_str path, const struct mg_str host, const struct mg_str protocol, const struct mg_str extra_headers, const struct mg_str user, const struct mg_str pass)
void mg_send_websocket_handshake (struct mg_connection *nc, const char *path, const char *extra_headers)
struct mg_connection * mg_connect_ws_opt (struct mg_mgr *mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data), struct mg_connect_opts opts, const char *url, const char *protocol, const char *extra_headers)
struct mg_connection * mg_connect_ws (struct mg_mgr *mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data), const char *url, const char *protocol, const char *extra_headers)
const char * mg_skip (const char *s, const char *end, const char *delims, struct mg_str *v)
void mg_base64_encode (const unsigned char *src, int src_len, char *dst)
int mg_base64_decode (const unsigned char *s, int len, char *dst)
void mg_set_close_on_exec (sock_t sock)
int mg_sock_addr_to_str (const union socket_address *sa, char *buf, size_t len, int flags)
int mg_conn_addr_to_str (struct mg_connection *nc, char *buf, size_t len, int flags)
int mg_is_big_endian (void)
void mg_mbuf_append_base64_putc (char ch, void *user_data)
void mg_mbuf_append_base64 (struct mbuf *mbuf, const void *data, size_t len)
void mg_basic_auth_header (const struct mg_str user, const struct mg_str pass, struct mbuf *buf)
struct mg_str mg_url_encode (const struct mg_str src)
static uint16_t getu16 (const char *p)
static const char * scanto (const char *p, struct mg_str *s)
static void mqtt_handler (struct mg_connection *nc, int ev, void *ev_data MG_UD_ARG(void *user_data))
static void mg_mqtt_proto_data_destructor (void *proto_data)
int mg_mqtt_match_topic_expression (struct mg_str exp, struct mg_str topic)
int mg_mqtt_vmatch_topic_expression (const char *exp, struct mg_str topic)
void mg_set_protocol_mqtt (struct mg_connection *nc)
static void mg_mqtt_prepend_header (struct mg_connection *nc, uint8_t cmd, uint8_t flags, size_t len)
void mg_send_mqtt_handshake (struct mg_connection *nc, const char *client_id)
void mg_send_mqtt_handshake_opt (struct mg_connection *nc, const char *client_id, struct mg_send_mqtt_handshake_opts opts)
void mg_mqtt_publish (struct mg_connection *nc, const char *topic, uint16_t message_id, int flags, const void *data, size_t len)
void mg_mqtt_subscribe (struct mg_connection *nc, const struct mg_mqtt_topic_expression *topics, size_t topics_len, uint16_t message_id)
int mg_mqtt_next_subscribe_topic (struct mg_mqtt_message *msg, struct mg_str *topic, uint8_t *qos, int pos)
void mg_mqtt_unsubscribe (struct mg_connection *nc, char **topics, size_t topics_len, uint16_t message_id)
void mg_mqtt_connack (struct mg_connection *nc, uint8_t return_code)
static void mg_send_mqtt_short_command (struct mg_connection *nc, uint8_t cmd, uint16_t message_id)
void mg_mqtt_puback (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_pubrec (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_pubrel (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_pubcomp (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_suback (struct mg_connection *nc, uint8_t *qoss, size_t qoss_len, uint16_t message_id)
void mg_mqtt_unsuback (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_ping (struct mg_connection *nc)
void mg_mqtt_pong (struct mg_connection *nc)
void mg_mqtt_disconnect (struct mg_connection *nc)
struct mg_dns_resource_record * mg_dns_next_record (struct mg_dns_message *msg, int query, struct mg_dns_resource_record *prev)
int mg_dns_parse_record_data (struct mg_dns_message *msg, struct mg_dns_resource_record *rr, void *data, size_t data_len)
int mg_dns_insert_header (struct mbuf *io, size_t pos, struct mg_dns_message *msg)
int mg_dns_copy_questions (struct mbuf *io, struct mg_dns_message *msg)
int mg_dns_encode_name (struct mbuf *io, const char *name, size_t len)
int mg_dns_encode_record (struct mbuf *io, struct mg_dns_resource_record *rr, const char *name, size_t nlen, const void *rdata, size_t rlen)
void mg_send_dns_query (struct mg_connection *nc, const char *name, int query_type)
static unsigned char * mg_parse_dns_resource_record (unsigned char *data, unsigned char *end, struct mg_dns_resource_record *rr, int reply)
int mg_parse_dns (const char *buf, int len, struct mg_dns_message *msg)
size_t mg_dns_uncompress_name (struct mg_dns_message *msg, struct mg_str *name, char *dst, int dst_len)
static void dns_handler (struct mg_connection *nc, int ev, void *ev_data MG_UD_ARG(void *user_data))
void mg_set_protocol_dns (struct mg_connection *nc)
static int mg_get_ip_address_of_nameserver (char *name, size_t name_len)
int mg_resolve_from_hosts_file (const char *name, union socket_address *usa)
static void mg_resolve_async_eh (struct mg_connection *nc, int ev, void *data MG_UD_ARG(void *user_data))
int mg_resolve_async (struct mg_mgr *mgr, const char *name, int query, mg_resolve_callback_t cb, void *data)
int mg_resolve_async_opt (struct mg_mgr *mgr, const char *name, int query, mg_resolve_callback_t cb, void *data, struct mg_resolve_async_opts opts)
void mg_set_nameserver (struct mg_mgr *mgr, const char *nameserver)
static void mg_tun_reconnect (struct mg_tun_client *client, int timeout)
static void mg_tun_init_client (struct mg_tun_client *client, struct mg_mgr *mgr, struct mg_iface *iface, const char *dispatcher, struct mg_tun_ssl_opts ssl)
void mg_tun_log_frame (struct mg_tun_frame *frame)
static void mg_tun_close_all (struct mg_tun_client *client)
static void mg_tun_client_handler (struct mg_connection *nc, int ev, void *ev_data MG_UD_ARG(void *user_data))
static void mg_tun_do_reconnect (struct mg_tun_client *client)
void mg_tun_reconnect_ev_handler (struct mg_connection *nc, int ev, void *ev_data MG_UD_ARG(void *user_data))
static struct mg_tun_client * mg_tun_create_client (struct mg_mgr *mgr, const char *dispatcher, struct mg_tun_ssl_opts ssl)
static struct mg_connection * mg_tun_do_bind (struct mg_tun_client *client, MG_CB(mg_event_handler_t handler, void *user_data), struct mg_bind_opts opts)
Variables
void *(* test_malloc)(size_t size)
void *(* test_calloc)(size_t count, size_t size)
enum cs_log_level cs_log_threshold
enum cs_log_level cs_log_threshold WEAK
static char * s_filter_pattern = NULL
static size_t s_filter_pattern_len
const struct mg_iface_vtable mg_socket_iface_vtable = MG_SOCKET_IFACE_VTABLE
const struct mg_iface_vtable mg_tun_iface_vtable = MG_TUN_IFACE_VTABLE
const struct mg_iface_vtable mg_default_iface_vtable = MG_SOCKET_IFACE_VTABLE
const struct mg_iface_vtable * mg_ifaces []
int mg_num_ifaces = (int) (sizeof(mg_ifaces) / sizeof(mg_ifaces[0]))
static const char * mg_version_header = `Mongoose/` MG_VERSION
static int mg_dns_tid = 0xa0
const struct mg_iface_vtable mg_simplelink_iface_vtable
const struct mg_iface_vtable mg_pic32_iface_vtable
Macro Definition Documentation
_MG_ALLOWED_CONNECT_FLAGS_MASK
#define _MG_ALLOWED_CONNECT_FLAGS_MASK
Value:
(MG_F_USER_1 | MG_F_USER_2 | MG_F_USER_3 |
      MG_F_USER_4 | MG_F_USER_5 | \
   MG_F_USER_6 | MG_F_WEBSOCKET_NO_DEFRAG |
      MG_F_ENABLE_BROADCAST)
Referenced by mg_connect_opt(), and mg_create_connection_base().
_MG_CALLBACK_MODIFIABLE_FLAGS_MASK
#define _MG_CALLBACK_MODIFIABLE_FLAGS_MASK
Value:
(MG_F_USER_1 | MG_F_USER_2 | MG_F_USER_3 |
      MG_F_USER_4 | MG_F_USER_5 | \
   MG_F_USER_6 | MG_F_WEBSOCKET_NO_DEFRAG |
      MG_F_SEND_AND_CLOSE | \
   MG_F_CLOSE_IMMEDIATELY | MG_F_IS_WEBSOCKET |
      MG_F_DELETE_CHUNK)
Referenced by mg_call().
_MG_F_FD_CAN_READ
#define _MG_F_FD_CAN_READ 1
Referenced by mg_mgr_handle_conn(), and mg_socket_if_poll().
_MG_F_FD_CAN_WRITE
#define _MG_F_FD_CAN_WRITE 1 << 1
Referenced by mg_mgr_handle_conn(), and mg_socket_if_poll().
_MG_F_FD_ERROR
#define _MG_F_FD_ERROR 1 << 2
Referenced by mg_socket_if_poll().
BASE64_ENCODE_BODY
#define BASE64_ENCODE_BODY
Value:
static const char *b64 = \
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"; \
  int i, j, a, b, c; \
                                                                          \
  for (i = j = 0; i < src_len; i += 3) { \
    a = src[i]; \
    b = i + 1 >= src_len ? 0 : src[i + 1]; \
    c = i + 2 >= src_len ? 0 : src[i + 2]; \
                                                                          \
    BASE64_OUT(b64[a >> 2]); \
    BASE64_OUT(b64[((a & 3) << 4) | (b >> 4)]); \
    if (i + 1 < src_len) { \
      BASE64_OUT(b64[(b & 15) << 2 | (c >> 6)]); \
    } \
    if (i + 2 < src_len) { \
      BASE64_OUT(b64[c & 63]); \
    } \
  } \
                                                                          \
  while (j % 4 != 0) { \
    BASE64_OUT('='); \
  } \
  BASE64_FLUSH()
Referenced by cs_base64_encode().
BASE64_FLUSH
#define BASE64_FLUSH()
Value:
do { \
    dst[j++] = '\0'; \
  } while (0)
BASE64_OUT
#define BASE64_OUT(ch)
Value:
do { \
    dst[j++] = (ch); \
  } while (0)
blk
#define blk(i)
Value:
(block->l[i & 15] = rol(block->l[(i + 13) & 15] ^ block->l[(i + 8) & 15] ^ \
                              block->l[(i + 2) & 15] ^ block->l[i & 15], \
                          1))
Referenced by mg_register_http_endpoint().
C_DISABLE_BUILTIN_SNPRINTF
#define C_DISABLE_BUILTIN_SNPRINTF 0
C_SNPRINTF_APPEND_CHAR
#define C_SNPRINTF_APPEND_CHAR(ch)
Value:
do { \
    if (i < (int) buf_size) buf[i] = ch; \
    i++; \
  } while (0)
Referenced by c_itoa(), and c_vsnprintf().
C_SNPRINTF_FLAG_ZERO
#define C_SNPRINTF_FLAG_ZERO 1
Referenced by c_itoa(), and c_vsnprintf().
CS_COMMON_CS_DBG_H_
#define CS_COMMON_CS_DBG_H_
CS_COMMON_CS_DIRENT_H_
#define CS_COMMON_CS_DIRENT_H_
CS_COMMON_CS_ENDIAN_H_
#define CS_COMMON_CS_ENDIAN_H_
CS_COMMON_MG_MEM_H_
#define CS_COMMON_MG_MEM_H_
CS_COMMON_PLATFORMS_LWIP_MG_NET_IF_LWIP_H_
#define CS_COMMON_PLATFORMS_LWIP_MG_NET_IF_LWIP_H_
CS_COMMON_PLATFORMS_PIC32_NET_IF_H_
#define CS_COMMON_PLATFORMS_PIC32_NET_IF_H_
CS_COMMON_PLATFORMS_SIMPLELINK_SL_FS_SLFS_H_
#define CS_COMMON_PLATFORMS_SIMPLELINK_SL_FS_SLFS_H_
CS_COMMON_PLATFORMS_SIMPLELINK_SL_NET_IF_H_
#define CS_COMMON_PLATFORMS_SIMPLELINK_SL_NET_IF_H_
CS_ENABLE_DEBUG
#define CS_ENABLE_DEBUG 0
CS_LOG_ENABLE_TS_DIFF
#define CS_LOG_ENABLE_TS_DIFF 0
CS_MONGOOSE_SRC_INTERNAL_H_
#define CS_MONGOOSE_SRC_INTERNAL_H_
CS_MONGOOSE_SRC_NET_IF_SOCKET_H_
#define CS_MONGOOSE_SRC_NET_IF_SOCKET_H_
CS_MONGOOSE_SRC_NET_IF_SOCKS_H_
#define CS_MONGOOSE_SRC_NET_IF_SOCKS_H_
CS_MONGOOSE_SRC_NET_IF_TUN_H_
#define CS_MONGOOSE_SRC_NET_IF_TUN_H_
CS_MONGOOSE_SRC_TUN_H_
#define CS_MONGOOSE_SRC_TUN_H_
DBG
#define DBG(x)
Referenced by mg_accept_conn(), mg_add_conn(), mg_bind_opt(), mg_call(), mg_check_ip_acl(), mg_close_conn(), mg_connect_opt(), mg_do_connect(), mg_get_http_header(), mg_get_line_len(), mg_handle_tcp_read(), mg_handle_udp_read(), mg_http_handler(), mg_if_accept_new_conn(), mg_if_connect_cb(), mg_if_recv_udp_cb(), mg_if_sent_cb(), mg_mgr_free(), mg_mgr_handle_conn(), mg_mgr_init_opt(), mg_parse_http_basic_auth(), mg_printf(), mg_recv_common(), mg_recvfrom(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_resolve_async_opt(), mg_send_dns_query(), mg_send_websocket_frame(), mg_set_timer(), mg_skip(), mg_socket_if_connect_tcp(), mg_socket_if_init(), mg_socket_if_poll(), mg_socket_if_sock_set(), mg_tun_send_frame(), mg_write_to_socket(), and mg_ws_handshake().
F1
#define F1(x, y, z) (z ^ (x & (y ^ z)))
Referenced by cs_md5_transform().
F2
#define F2(x, y, z) F1(z, x, y)
Referenced by cs_md5_transform().
F3
#define F3(x, y, z) (x ^ y ^ z)
Referenced by cs_md5_transform().
F4
#define F4(x, y, z) (y ^ (x | ~z))
Referenced by cs_md5_transform().
HEXTOI
#define HEXTOI(x) (isdigit(x) ? x - '0' : x - 'W')
Referenced by mg_url_decode().
intptr_t
#define intptr_t long
LOG
#define LOG(l, x)
Referenced by mg_connect_http_base(), mg_get_http_header(), mg_http_send_error(), mg_mgr_poll(), mg_parse_http_basic_auth(), mg_resolve_async_eh(), mg_tun_client_handler(), mg_tun_close_all(), mg_tun_create_client(), mg_tun_do_reconnect(), mg_tun_if_destroy_conn(), mg_tun_if_find_conn(), mg_tun_if_tcp_send(), mg_tun_log_frame(), mg_tun_send_frame(), mqtt_handler(), and parse_mqtt().
MAX
#define MAX(a, b) ((a) > (b) ? (a) : (b))
Referenced by mg_conn_addr_to_str().
MBUF_FREE
#define MBUF_FREE MG_FREE
Referenced by mbuf_free().
MBUF_REALLOC
#define MBUF_REALLOC MG_REALLOC
Referenced by mbuf_insert(), and mbuf_resize().
MD5STEP
#define MD5STEP(f, w, x, y, z, data, s) (w += f(x, y, z) + data, w = w << s | w >> (32 - s), w += x)
Referenced by cs_md5_transform().
MG_CALLOC
#define MG_CALLOC calloc
Referenced by mg_create_connection_base(), mg_http_get_proto_data(), mg_if_create_iface(), mg_mqtt_disconnect(), mg_parse_http_basic_auth(), mg_register_http_endpoint_opt(), mg_resolve_async_opt(), mg_send_dns_query(), mg_set_nameserver(), mg_set_protocol_mqtt(), and mg_tun_send_frame().
MG_COPY_COMMON_CONNECTION_OPTIONS
#define MG_COPY_COMMON_CONNECTION_OPTIONS(dst, src) memcpy(dst, src, sizeof(*dst));
Referenced by mg_bind_opt(), and mg_connect_opt().
MG_CTL_MSG_MESSAGE_SIZE
#define MG_CTL_MSG_MESSAGE_SIZE 8192
MG_DEFAULT_NAMESERVER
#define MG_DEFAULT_NAMESERVER `8.8.8.8`
Referenced by mg_get_ip_address_of_nameserver(), and mg_resolve_async_opt().
MG_ENABLE_NET_IF_LWIP_LOW_LEVEL
#define MG_ENABLE_NET_IF_LWIP_LOW_LEVEL MG_NET_IF == MG_NET_IF_LWIP_LOW_LEVEL
MG_ENABLE_NET_IF_PIC32
#define MG_ENABLE_NET_IF_PIC32 MG_NET_IF == MG_NET_IF_PIC32
MG_ENABLE_NET_IF_SIMPLELINK
#define MG_ENABLE_NET_IF_SIMPLELINK MG_NET_IF == MG_NET_IF_SIMPLELINK
MG_ENABLE_NET_IF_SOCKET
#define MG_ENABLE_NET_IF_SOCKET MG_NET_IF == MG_NET_IF_SOCKET
MG_FREE
#define MG_FREE free
Referenced by mg_avprintf(), mg_connect_http_base(), mg_create_connection(), mg_destroy_conn(), mg_get_line_len(), mg_handle_tcp_read(), mg_http_conn_destructor(), mg_http_free_proto_data_endpoints(), mg_http_get_proto_data(), mg_http_send_error(), mg_http_send_redirect(), mg_if_recv_udp_cb(), mg_mgr_free(), mg_mqtt_disconnect(), mg_mqtt_proto_data_destructor(), mg_parse_http_basic_auth(), mg_printf_html_escape(), mg_printf_http_chunk(), mg_printf_websocket_frame(), mg_recv_common(), mg_recvfrom(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_resolve_async_opt(), mg_send_dns_query(), mg_set_nameserver(), mg_tun_destroy_client(), mg_tun_send_frame(), and mg_vprintf().
MG_INTERNAL
#define MG_INTERNAL static
Referenced by mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_socket_if_poll(), and mg_tun_send_frame().
MG_MALLOC
#define MG_MALLOC malloc
Referenced by c_strnstr(), mg_avprintf(), mg_handle_tcp_read(), mg_http_send_error(), mg_mgr_init_opt(), mg_mqtt_disconnect(), mg_parse_http_basic_auth(), mg_recvfrom(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_strdup_common(), mg_tun_create_client(), and mg_tun_send_frame().
MG_MAX_HOST_LEN
#define MG_MAX_HOST_LEN 200
Referenced by mg_bind_opt(), and mg_connect_opt().
MG_REALLOC
#define MG_REALLOC realloc
Referenced by mg_mqtt_disconnect(), mg_parse_http_basic_auth(), and mg_tun_send_frame().
MG_SET_PTRPTR
#define MG_SET_PTRPTR(_ptr, _v)
Value:
do { \
    if (_ptr) *(_ptr) = _v; \
  } while (0)
Referenced by mg_bind_opt(), mg_connect_http_base(), mg_connect_opt(), mg_create_connection(), and mg_create_connection_base().
MG_SOCKET_IFACE_VTABLE
#define MG_SOCKET_IFACE_VTABLE
Value:
{ \
    mg_socket_if_init, \
    mg_socket_if_free, \
    mg_socket_if_add_conn, \
    mg_socket_if_remove_conn, \
    mg_socket_if_poll, \
    mg_socket_if_listen_tcp, \
    mg_socket_if_listen_udp, \
    mg_socket_if_connect_tcp, \
    mg_socket_if_connect_udp, \
    mg_socket_if_tcp_send, \
    mg_socket_if_udp_send, \
    mg_socket_if_recved, \
    mg_socket_if_create_conn, \
    mg_socket_if_destroy_conn, \
    mg_socket_if_sock_set, \
    mg_socket_if_get_conn_addr, \
  }
MG_TCP_RECV_BUFFER_SIZE [1/2]
#define MG_TCP_RECV_BUFFER_SIZE 1024
Referenced by mg_handle_tcp_read().
MG_TCP_RECV_BUFFER_SIZE [2/2]
#define MG_TCP_RECV_BUFFER_SIZE 1024
MG_TUN_DATA_FRAME
#define MG_TUN_DATA_FRAME 0x0
Referenced by mg_tun_if_destroy_conn(), and mg_tun_if_tcp_send().
MG_TUN_F_END_STREAM
#define MG_TUN_F_END_STREAM 0x1
Referenced by mg_tun_client_handler(), and mg_tun_if_destroy_conn().
MG_TUN_IFACE_VTABLE
#define MG_TUN_IFACE_VTABLE
Value:
{ \
    mg_tun_if_init, \
    mg_tun_if_free, \
    mg_tun_if_add_conn, \
    mg_tun_if_remove_conn, \
    mg_tun_if_poll, \
    mg_tun_if_listen_tcp, \
    mg_tun_if_listen_udp, \
    mg_tun_if_connect_tcp, \
    mg_tun_if_connect_udp, \
    mg_tun_if_tcp_send, \
    mg_tun_if_udp_send, \
    mg_tun_if_recved, \
    mg_tun_if_create_conn, \
    mg_tun_if_destroy_conn, \
    mg_tun_if_sock_set, \
    mg_tun_if_get_conn_addr, \
  }
MG_TUN_PROTO_NAME
#define MG_TUN_PROTO_NAME `mg_tun`
Referenced by mg_tun_do_reconnect().
MG_TUN_RECONNECT_INTERVAL
#define MG_TUN_RECONNECT_INTERVAL 1
Referenced by mg_tun_client_handler().
MG_UDP_RECV_BUFFER_SIZE [1/2]
#define MG_UDP_RECV_BUFFER_SIZE 1500
Referenced by mg_recvfrom().
MG_UDP_RECV_BUFFER_SIZE [2/2]
#define MG_UDP_RECV_BUFFER_SIZE 1500
MG_WEBSOCKET_PING_INTERVAL_SECONDS
#define MG_WEBSOCKET_PING_INTERVAL_SECONDS 5
Referenced by mg_ws_handler().
MIN
#define MIN(a, b) ((a) < (b) ? (a) : (b))
NUM_DIGITS
#define NUM_DIGITS ('9' - '0' + 1)
Referenced by cs_base64_emit_code().
NUM_LETTERS
#define NUM_LETTERS (NUM_UPPERCASES * 2)
Referenced by cs_base64_emit_code().
NUM_UPPERCASES
#define NUM_UPPERCASES ('Z' - 'A' + 1)
Referenced by cs_base64_emit_code().
R0
#define R0(v, w, x, y, z, i)
Value:
z += ((w & (x ^ y)) ^ y) + blk0(block, i) + 0x5A827999 + rol(v, 5); \
  w = rol(w, 30);
Referenced by cs_sha1_transform().
R1
#define R1(v, w, x, y, z, i)
Value:
z += ((w & (x ^ y)) ^ y) + blk(i) + 0x5A827999 + rol(v, 5); \
  w = rol(w, 30);
Referenced by cs_sha1_transform().
R2
#define R2(v, w, x, y, z, i)
Value:
z += (w ^ x ^ y) + blk(i) + 0x6ED9EBA1 + rol(v, 5); \
  w = rol(w, 30);
Referenced by cs_sha1_transform().
R3
#define R3(v, w, x, y, z, i)
Value:
z += (((w | x) & y) | (w & x)) + blk(i) + 0x8F1BBCDC + rol(v, 5); \
  w = rol(w, 30);
Referenced by cs_sha1_transform().
R4
#define R4(v, w, x, y, z, i)
Value:
z += (w ^ x ^ y) + blk(i) + 0xCA62C1D6 + rol(v, 5); \
  w = rol(w, 30);
Referenced by cs_sha1_transform().
rol
#define rol(value, bits) (((value) << (bits)) | ((value) >> (32 - (bits))))
Referenced by blk0().
SHA1HANDSOFF
#define SHA1HANDSOFF
Typedef Documentation
cs_dirent_dummy
typedef int cs_dirent_dummy
Enumeration Type Documentation
cs_log_level
enum cs_log_level
Enumerator
LL_NONE
LL_ERROR
LL_WARN
LL_INFO
LL_DEBUG
LL_VERBOSE_DEBUG
_LL_MIN
_LL_MAX
mg_http_multipart_stream_state
enum mg_http_multipart_stream_state
Enumerator
MPS_BEGIN
MPS_WAITING_FOR_BOUNDARY
MPS_WAITING_FOR_CHUNK
MPS_GOT_CHUNK
MPS_GOT_BOUNDARY
MPS_FINALIZE
MPS_FINISHED
mg_http_proto_data_type
enum mg_http_proto_data_type
Enumerator
DATA_NONE
DATA_FILE
DATA_PUT
Function Documentation
blk0()
static uint32_t blk0 (union char64long16 * block, int i) [static]
References char64long16::l, and rol.
byteReverse()
static void byteReverse (unsigned char * buf, unsigned longs) [static]
Referenced by cs_md5_final(), and cs_md5_update().
c_itoa()
static int c_itoa (char * buf, size_t buf_size, int64_t num, int base, int flags, int field_width) [static]
References C_SNPRINTF_APPEND_CHAR, C_SNPRINTF_FLAG_ZERO, c_vsnprintf(), and WEAK.
Referenced by c_vsnprintf().
c_snprintf()
int c_snprintf (char * buf, size_t buf_size, const char * fmt, ...)
References c_strnstr(), c_vsnprintf(), mg_str::p, and WEAK.
Referenced by c_vsnprintf().
c_strnlen()
size_t c_strnlen (const char * s, size_t maxlen)
Referenced by c_vsnprintf().
c_strnstr()
const char * c_strnstr (const char * s, const char * find, size_t slen)
References cs_to_hex(), MG_MALLOC, mg_str::p, and WEAK.
Referenced by c_snprintf(), and mg_get_line_len().
c_vsnprintf()
int c_vsnprintf (char * buf, size_t buf_size, const char * fmt, va_list ap)
References c_itoa(), c_snprintf(), C_SNPRINTF_APPEND_CHAR, C_SNPRINTF_FLAG_ZERO, c_strnlen(), and WEAK.
Referenced by c_itoa(), and c_snprintf().
cs_base64_decode()
int cs_base64_decode (const unsigned char * s, int len, char * dst, int * dec_len)
References from_b64().
Referenced by mg_base64_decode(), and mg_parse_http_basic_auth().
cs_base64_emit_chunk()
static void cs_base64_emit_chunk (struct cs_base64_ctx * ctx) [static]
References cs_base64_ctx::chunk, cs_base64_ctx::chunk_size, and cs_base64_emit_code().
Referenced by cs_base64_finish(), and cs_base64_update().
cs_base64_emit_code()
static void cs_base64_emit_code (struct cs_base64_ctx * ctx, int v) [static]
References cs_base64_ctx::b64_putc, NUM_DIGITS, NUM_LETTERS, NUM_UPPERCASES, and cs_base64_ctx::user_data.
Referenced by cs_base64_emit_chunk().
cs_base64_encode()
void cs_base64_encode (const unsigned char * src, int src_len, char * dst)
References BASE64_ENCODE_BODY, and cs_fprint_base64().
Referenced by mg_base64_encode().
cs_base64_finish()
void cs_base64_finish (struct cs_base64_ctx * ctx)
References cs_base64_ctx::b64_putc, cs_base64_ctx::chunk, cs_base64_ctx::chunk_size, cs_base64_emit_chunk(), and cs_base64_ctx::user_data.
Referenced by mg_basic_auth_header(), and mg_mbuf_append_base64().
cs_base64_init()
void cs_base64_init (struct cs_base64_ctx * ctx, cs_base64_putc_t b64_putc, void * user_data)
References cs_base64_ctx::b64_putc, cs_base64_ctx::chunk_size, and cs_base64_ctx::user_data.
Referenced by mg_basic_auth_header(), and mg_mbuf_append_base64().
cs_base64_update()
void cs_base64_update (struct cs_base64_ctx * ctx, const char * str, size_t len)
References cs_base64_ctx::chunk, cs_base64_ctx::chunk_size, and cs_base64_emit_chunk().
Referenced by mg_basic_auth_header(), and mg_mbuf_append_base64().
cs_from_hex()
void cs_from_hex (char * to, const char * p, size_t len)
References fourbit(), mg_str::len, and WEAK.
Referenced by fourbit().
cs_hmac_sha1()
void cs_hmac_sha1 (const unsigned char * key, size_t keylen, const unsigned char * data, size_t datalen, unsigned char out[20])
References cs_sha1_final(), cs_sha1_init(), cs_sha1_update(), mbuf_init(), and WEAK.
cs_log_print_prefix()
int cs_log_print_prefix (enum cs_log_level level, const char * func, const char * filename)
cs_log_set_filter()
void cs_log_set_filter (const char * source_file_name)
cs_log_set_level()
void cs_log_set_level (enum cs_log_level level)
References cs_time().
cs_md5_final()
void cs_md5_final (unsigned char digest[16], cs_md5_ctx * ctx)
References cs_md5_ctx::bits, cs_md5_ctx::buf, byteReverse(), cs_md5_transform(), and cs_md5_ctx::in.
Referenced by mg_parse_http_basic_auth().
cs_md5_init()
void cs_md5_init (cs_md5_ctx * ctx)
References cs_md5_ctx::bits, and cs_md5_ctx::buf.
Referenced by mg_parse_http_basic_auth().
cs_md5_transform()
static void cs_md5_transform (uint32_t buf[4], uint32_t const in[16]) [static]
References F1, F2, F3, F4, and MD5STEP.
Referenced by cs_md5_final(), and cs_md5_update().
cs_md5_update()
void cs_md5_update (cs_md5_ctx * ctx, const unsigned char * buf, size_t len)
References cs_md5_ctx::bits, cs_md5_ctx::buf, byteReverse(), cs_md5_transform(), and cs_md5_ctx::in.
Referenced by mg_parse_http_basic_auth().
cs_sha1_final()
void cs_sha1_final (unsigned char digest[20], cs_sha1_ctx * context)
References char64long16::c, cs_sha1_ctx::count, cs_sha1_update(), and cs_sha1_ctx::state.
Referenced by cs_hmac_sha1(), and mg_hash_sha1_v().
cs_sha1_init()
void cs_sha1_init (cs_sha1_ctx * context)
References cs_sha1_ctx::count, and cs_sha1_ctx::state.
Referenced by cs_hmac_sha1(), and mg_hash_sha1_v().
cs_sha1_transform()
void cs_sha1_transform (uint32_t state[5], const unsigned char buffer[64])
References char64long16::c, R0, R1, R2, R3, and R4.
Referenced by cs_sha1_update().
cs_sha1_update()
void cs_sha1_update (cs_sha1_ctx * context, const unsigned char * data, uint32_t len)
References cs_sha1_ctx::buffer, cs_sha1_ctx::count, cs_sha1_transform(), and cs_sha1_ctx::state.
Referenced by cs_hmac_sha1(), cs_sha1_final(), and mg_hash_sha1_v().
cs_time()
double cs_time (void)
Referenced by cs_log_set_level(), mg_time(), and mg_tun_if_poll().
cs_timegm()
double cs_timegm (const struct tm * tm)
cs_to_hex()
void cs_to_hex (char * to, const unsigned char * p, size_t len)
Referenced by c_strnstr(), and mg_parse_http_basic_auth().
deliver_chunk()
static void deliver_chunk (struct mg_connection * c, struct http_message * hm, int req_len) [static]
References TBT::__attribute__, http_message::body, mg_connection::flags, mg_connection::handler, mg_str::len, mbuf::len, mg_call(), MG_EV_HTTP_CHUNK, MG_F_DELETE_CHUNK, mg_http_handler(), MG_UD_ARG, mg_connection::recv_mbuf, and mg_connection::user_data.
Referenced by mg_http_handler().
dns_handler()
static void dns_handler (struct mg_connection * nc, int ev, void *ev_data MG_UD_ARGvoid *user_data) [static]
References mbuf::buf, mg_connection::flags, mg_dns_message::flags, mg_connection::handler, mbuf::len, mbuf_insert(), mbuf_remove(), mg_dns_insert_header(), MG_DNS_MESSAGE, MG_EV_RECV, MG_F_UDP, mg_parse_dns(), mg_send(), MG_UD_ARG, and mg_connection::recv_mbuf.
Referenced by mg_set_protocol_dns().
fourbit()
static int fourbit (int ch) [static]
References cs_from_hex(), and WEAK.
Referenced by cs_from_hex().
from_b64()
static unsigned char from_b64 (unsigned char ch) [static]
Referenced by cs_base64_decode().
getu16()
static uint16_t getu16 (const char * p) [static]
Referenced by parse_mqtt(), and scanto().
isbyte()
static int isbyte (int n) [static]
Referenced by parse_net().
mbuf_append()
size_t mbuf_append (struct mbuf * a, const void * buf, size_t len)
References mbuf::len, mbuf_insert(), mbuf_remove(), and WEAK.
Referenced by mbuf_insert(), mg_assemble_uri(), mg_basic_auth_header(), mg_dns_copy_questions(), mg_dns_encode_name(), mg_dns_encode_record(), mg_mbuf_append_base64_putc(), mg_recv_common(), mg_set_nameserver(), mg_socket_if_tcp_send(), mg_socket_if_udp_send(), and mg_url_encode().
mbuf_free()
void mbuf_free (struct mbuf * mbuf)
References mbuf::buf, MBUF_FREE, mbuf_init(), mbuf_resize(), and WEAK.
Referenced by mbuf_init(), mg_assemble_uri(), mg_connect_http_opt(), mg_destroy_conn(), mg_recv_common(), mg_send_dns_query(), mg_send_websocket_handshake3v(), and mg_set_nameserver().
mbuf_init()
void mbuf_init (struct mbuf * mbuf, size_t initial_size)
References mbuf::buf, mbuf::len, mbuf_free(), mbuf_resize(), mbuf::size, and WEAK.
Referenced by cs_hmac_sha1(), mbuf_free(), mg_assemble_uri(), mg_connect_http_opt(), mg_send_dns_query(), mg_send_websocket_handshake3v(), mg_set_nameserver(), and mg_url_encode().
mbuf_insert()
size_t mbuf_insert (struct mbuf * a, size_t off, const void * buf, size_t len)
References mbuf::buf, mbuf::len, mbuf_append(), MBUF_REALLOC, MBUF_SIZE_MULTIPLIER, mbuf::size, and WEAK.
Referenced by dns_handler(), mbuf_append(), mbuf_trim(), mg_dns_insert_header(), mg_mqtt_prepend_header(), mg_send_dns_query(), and mg_set_protocol_dns().
mbuf_remove()
void mbuf_remove (struct mbuf * mb, size_t n)
References mbuf::buf, mbuf::len, mg_ncasecmp(), and WEAK.
Referenced by dns_handler(), mbuf_append(), mg_deliver_websocket_data(), mg_forward(), mg_get_http_header(), mg_get_line_len(), mg_http_handler(), mg_if_sent_cb(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_set_nameserver(), mg_tun_send_frame(), and mqtt_handler().
mbuf_resize()
void mbuf_resize (struct mbuf * a, size_t new_size)
References mbuf::buf, mbuf::len, MBUF_REALLOC, mbuf_trim(), mbuf::size, and WEAK.
Referenced by mbuf_free(), mbuf_init(), and mbuf_trim().
mbuf_trim()
void mbuf_trim (struct mbuf * mbuf)
References mbuf::len, mbuf_insert(), mbuf_resize(), and WEAK.
Referenced by mbuf_resize(), mg_if_sent_cb(), and mg_url_encode().
mg_accept_conn()
static int mg_accept_conn (struct mg_connection * lc) [static]
References DBG, mg_connection::flags, mg_close_conn(), MG_F_SSL, mg_get_errno(), mg_if_accept_new_conn(), mg_if_accept_tcp_cb(), mg_is_error(), mg_sock_set(), socket_address::sa, socket_address::sin, and mg_connection::sock.
Referenced by mg_mgr_handle_conn().
mg_add_conn()
MG_INTERNAL void mg_add_conn (struct mg_mgr * mgr, struct mg_connection * c)
References mg_mgr::active_connections, mg_iface_vtable::add_conn, DBG, mg_connection::iface, mg_connection::mgr, mg_connection::next, mg_connection::prev, mg_connection::sock, and mg_iface::vtable.
Referenced by mg_add_sock_opt(), mg_bind_opt(), mg_do_connect(), mg_if_accept_new_conn(), and mg_if_recv_udp_cb().
mg_add_sock()
struct mg_connection* mg_add_sock (struct mg_mgr * s, sock_t sock, MG_CB(mg_event_handler_t callback, void *user_data))
References mg_add_sock_opt(), and MG_CB.
Referenced by mg_register_http_endpoint(), and mg_tun_reconnect().
mg_add_sock_opt()
struct mg_connection* mg_add_sock_opt (struct mg_mgr * s, sock_t sock, MG_CB(mg_event_handler_t callback, void *user_data) , struct mg_add_sock_opts opts)
References mg_add_conn(), mg_create_connection_base(), mg_sock_set(), mg_connection::mgr, mg_connection::user_data, and mg_add_sock_opts::user_data.
Referenced by mg_add_sock().
mg_add_to_set()
void mg_add_to_set (sock_t sock, fd_set * set, sock_t * max_fd)
References mg_connection::sock.
Referenced by mg_socket_if_poll().
mg_asprintf()
int mg_asprintf (char ** buf, size_t size, const char * fmt, ...)
References mg_avprintf(), and WEAK.
Referenced by mg_casecmp(), mg_connect_http_base(), mg_http_send_redirect(), mg_mqtt_disconnect(), mg_parse_http_basic_auth(), and mg_tun_send_frame().
mg_assemble_uri()
int mg_assemble_uri (const struct mg_str * scheme, const struct mg_str * user_info, const struct mg_str * host, unsigned int port, const struct mg_str * path, const struct mg_str * query, const struct mg_str * fragment, int normalize_path, struct mg_str * uri)
References mbuf::buf, mg_str::len, mbuf::len, mbuf_append(), mbuf_free(), mbuf_init(), mg_normalize_uri_path(), mg_strdup(), and mg_str::p.
mg_avprintf()
int mg_avprintf (char ** buf, size_t size, const char * fmt, va_list ap)
References mg_str::len, MG_FREE, and MG_MALLOC.
Referenced by mg_asprintf(), mg_printf_html_escape(), mg_printf_http_chunk(), mg_printf_websocket_frame(), and mg_vprintf().
mg_base64_decode()
int mg_base64_decode (const unsigned char * s, int len, char * dst)
References cs_base64_decode().
mg_base64_encode()
void mg_base64_encode (const unsigned char * src, int src_len, char * dst)
References cs_base64_encode().
Referenced by mg_send_websocket_handshake3v(), and mg_ws_handshake().
mg_basic_auth_header()
void mg_basic_auth_header (const struct mg_str user, const struct mg_str pass, struct mbuf * buf)
References cs_base64_finish(), cs_base64_init(), cs_base64_update(), mg_str::len, mbuf_append(), mg_mbuf_append_base64_putc(), and mg_str::p.
Referenced by mg_connect_http_opt(), and mg_send_websocket_handshake3v().
mg_bind()
struct mg_connection* mg_bind (struct mg_mgr * srv, const char * address, MG_CB(mg_event_handler_t event_handler, void *user_data))
References mg_bind_opt(), and MG_CB.
Referenced by TBT::WSClientInterface::threadFunc().
mg_bind_opt()
struct mg_connection* mg_bind_opt (struct mg_mgr * mgr, const char * address, MG_CB(mg_event_handler_t callback, void *user_data) , struct mg_bind_opts opts)
References DBG, mg_bind_opts::error_string, mg_connection::flags, mg_connection::iface, mg_iface_vtable::listen_tcp, mg_iface_vtable::listen_udp, mg_add_conn(), MG_CB, MG_COPY_COMMON_CONNECTION_OPTIONS, mg_create_connection(), mg_destroy_conn(), MG_F_LISTENING, MG_F_SSL, MG_F_UDP, MG_MAX_HOST_LEN, mg_mk_str(), mg_parse_address(), MG_SET_PTRPTR, mg_strncmp(), mg_tun_bind_opt(), mg_connection::mgr, mg_connection::sa, mg_add_sock_opts::user_data, mg_bind_opts::user_data, and mg_iface::vtable.
Referenced by mg_bind(), and mg_tun_do_bind().
mg_call()
MG_INTERNAL void mg_call (struct mg_connection * nc, mg_event_handler_t ev_handler, void * user_data, int ev, void * ev_data)
References _MG_CALLBACK_MODIFIABLE_FLAGS_MASK, DBG, TBT::ev_handler(), mg_connection::flags, mg_connection::handler, mg_connection::iface, mbuf::len, MG_EV_POLL, MG_EV_RECV, MG_EV_SEND, MG_F_UDP, MG_UD_ARG, mg_connection::mgr, mg_connection::proto_handler, mg_connection::recv_mbuf, mg_iface_vtable::recved, mg_connection::send_mbuf, and mg_iface::vtable.
Referenced by deliver_chunk(), mg_close_conn(), mg_get_line_len(), mg_handle_chunked(), mg_handle_incoming_websocket_frame(), mg_http_call_endpoint_handler(), mg_http_handler(), mg_if_accept_tcp_cb(), mg_if_connect_cb(), mg_if_poll(), mg_if_recv_udp_cb(), mg_if_sent_cb(), mg_if_timer(), mg_recv_common(), mg_register_http_endpoint(), mg_tun_send_frame(), mg_ws_handler(), and resolve_cb().
mg_casecmp()
int mg_casecmp (const char * s1, const char * s2)
References mg_asprintf(), mg_ncasecmp(), and WEAK.
Referenced by mg_http_conn_destructor(), and mg_ncasecmp().
mg_check_ip_acl()
int mg_check_ip_acl (const char * acl, uint32_t remote_ip)
References DBG, mg_next_comma_list_entry(), mg_str::p, and parse_net().
Referenced by mg_parse_http_basic_auth().
mg_close_conn()
void mg_close_conn (struct mg_connection * conn)
References DBG, mg_iface_vtable::destroy_conn, mg_connection::flags, mg_connection::iface, mg_call(), mg_destroy_conn(), MG_EV_CLOSE, MG_F_SSL_HANDSHAKE_DONE, mg_remove_conn(), mg_connection::sock, mg_connection::user_data, and mg_iface::vtable.
Referenced by mg_accept_conn(), mg_mgr_free(), mg_socket_if_poll(), and mg_tun_client_handler().
mg_conn_addr_to_str()
int mg_conn_addr_to_str (struct mg_connection * nc, char * buf, size_t len, int flags)
References MAX, mg_conn_addr_to_str(), MG_EV_ACCEPT, MG_EV_CLOSE, MG_EV_CONNECT, MG_EV_RECV, MG_EV_SEND, mg_if_get_conn_addr(), mg_sock_addr_to_str(), MG_SOCK_STRINGIFY_IP, MG_SOCK_STRINGIFY_PORT, MG_SOCK_STRINGIFY_REMOTE, and mg_time().
Referenced by mg_conn_addr_to_str(), mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_connect()
struct mg_connection* mg_connect (struct mg_mgr * mgr, const char * address, MG_CB(mg_event_handler_t callback, void *user_data))
References MG_CB, and mg_connect_opt().
Referenced by mg_resolve_async_opt(), and mg_tun_send_frame().
mg_connect_http()
struct mg_connection* mg_connect_http (struct mg_mgr * mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data) , const char * url, const char * extra_headers, const char * post_data)
References MG_CB, and mg_connect_http_opt().
mg_connect_http_base()
struct mg_connection * mg_connect_http_base (struct mg_mgr * mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data) , struct mg_connect_opts opts, const char * scheme1, const char * scheme2, const char * scheme_ssl1, const char * scheme_ssl2, const char * url, struct mg_str * path, struct mg_str * user_info, struct mg_str * host)
References mg_connect_opts::error_string, mg_str::len, LL_DEBUG, LOG, mg_asprintf(), MG_CB, mg_connect_opt(), MG_FREE, mg_mk_str(), mg_parse_uri(), mg_set_protocol_http_websocket(), MG_SET_PTRPTR, mg_vcmp(), and mg_str::p.
Referenced by mg_connect_http_opt(), mg_connect_ws_opt(), and mg_parse_http_basic_auth().
mg_connect_http_opt()
struct mg_connection* mg_connect_http_opt (struct mg_mgr * mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data) , struct mg_connect_opts opts, const char * url, const char * extra_headers, const char * post_data)
References mbuf::buf, mg_str::len, mbuf::len, mbuf_free(), mbuf_init(), mg_basic_auth_header(), MG_CB, mg_connect_http_base(), mg_mk_str(), MG_NULL_STR, mg_printf(), and mg_str::p.
Referenced by mg_connect_http().
mg_connect_opt()
struct mg_connection* mg_connect_opt (struct mg_mgr * mgr, const char * address, MG_CB(mg_event_handler_t callback, void *user_data) , struct mg_connect_opts opts)
References _MG_ALLOWED_CONNECT_FLAGS_MASK, DBG, mg_resolve_async_opts::dns_conn, mg_connect_opts::error_string, mg_connection::flags, mg_connect_opts::flags, MG_COPY_COMMON_CONNECTION_OPTIONS, mg_create_connection(), mg_destroy_conn(), MG_DNS_A_RECORD, mg_do_connect(), MG_F_RESOLVING, MG_F_SSL, MG_F_UDP, MG_MAX_HOST_LEN, mg_parse_address(), mg_resolve_async_opt(), MG_SET_PTRPTR, mg_connection::mgr, mg_connect_opts::nameserver, mg_resolve_async_opts::nameserver, mg_connection::priv_2, resolve_cb(), mg_connection::sa, mg_connection::user_data, mg_add_sock_opts::user_data, and mg_connect_opts::user_data.
Referenced by mg_connect(), and mg_connect_http_base().
mg_connect_ws()
struct mg_connection* mg_connect_ws (struct mg_mgr * mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data) , const char * url, const char * protocol, const char * extra_headers)
References MG_CB, and mg_connect_ws_opt().
mg_connect_ws_opt()
struct mg_connection* mg_connect_ws_opt (struct mg_mgr * mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data) , struct mg_connect_opts opts, const char * url, const char * protocol, const char * extra_headers)
References MG_CB, mg_connect_http_base(), mg_mk_str(), MG_NULL_STR, and mg_send_websocket_handshake3v().
Referenced by mg_connect_ws(), and mg_tun_do_reconnect().
mg_create_connection()
MG_INTERNAL struct mg_connection * mg_create_connection (struct mg_mgr * mgr, mg_event_handler_t callback, struct mg_add_sock_opts opts)
References mg_iface_vtable::create_conn, mg_add_sock_opts::error_string, mg_connection::iface, mg_create_connection_base(), MG_FREE, MG_SET_PTRPTR, and mg_iface::vtable.
Referenced by mg_bind_opt(), mg_connect_opt(), and mg_if_accept_new_conn().
mg_create_connection_base()
MG_INTERNAL struct mg_connection* mg_create_connection_base (struct mg_mgr * mgr, mg_event_handler_t callback, struct mg_add_sock_opts opts)
References _MG_ALLOWED_CONNECT_FLAGS_MASK, ctl_msg::callback, mg_add_sock_opts::error_string, mg_connection::flags, mg_add_sock_opts::flags, mg_connection::handler, mg_connection::iface, mg_add_sock_opts::iface, mg_mgr::ifaces, mg_connection::last_io_time, MG_CALLOC, MG_MAIN_IFACE, MG_SET_PTRPTR, mg_time(), mg_connection::mgr, mg_connection::recv_mbuf_limit, mg_connection::sock, mg_connection::user_data, and mg_add_sock_opts::user_data.
Referenced by mg_add_sock_opt(), mg_create_connection(), and mg_if_recv_udp_cb().
mg_deliver_websocket_data()
static int mg_deliver_websocket_data (struct mg_connection * nc) [static]
References mbuf::buf, websocket_message::data, mg_connection::flags, websocket_message::flags, mbuf::len, mbuf_remove(), MG_F_CLOSE_IMMEDIATELY, MG_F_SEND_AND_CLOSE, MG_F_WEBSOCKET_NO_DEFRAG, mg_handle_incoming_websocket_frame(), mg_is_ws_first_fragment(), mg_is_ws_fragment(), mg_ws_get_proto_data(), mg_connection::recv_mbuf, websocket_message::size, and WEBSOCKET_OP_CLOSE.
Referenced by mg_ws_handler().
mg_destroy_conn()
void mg_destroy_conn (struct mg_connection * conn, int destroy_if)
References mg_iface_vtable::destroy_conn, mg_connection::iface, mbuf_free(), MG_FREE, mg_connection::proto_data, mg_connection::proto_data_destructor, mg_connection::recv_mbuf, mg_connection::send_mbuf, and mg_iface::vtable.
Referenced by mg_bind_opt(), mg_close_conn(), mg_connect_opt(), and resolve_cb().
mg_dns_copy_questions()
int mg_dns_copy_questions (struct mbuf * io, struct mg_dns_message * msg)
References mg_str::len, mbuf_append(), mg_dns_resource_record::name, mg_dns_message::num_questions, mg_str::p, mg_dns_message::pkt, and mg_dns_message::questions.
Referenced by mg_set_protocol_dns().
mg_dns_encode_name()
int mg_dns_encode_name (struct mbuf * io, const char * name, size_t len)
References mbuf::len, mbuf_append(), and mg_dns_resource_record::name.
Referenced by mg_dns_encode_record().
mg_dns_encode_record()
int mg_dns_encode_record (struct mbuf * io, struct mg_dns_resource_record * rr, const char * name, size_t nlen, const void * rdata, size_t rlen)
References mbuf::buf, mg_dns_resource_record::kind, mbuf::len, mbuf_append(), MG_DNS_ANSWER, MG_DNS_CNAME_RECORD, mg_dns_encode_name(), MG_DNS_INVALID_RECORD, mg_dns_resource_record::rclass, mg_dns_resource_record::rtype, and mg_dns_resource_record::ttl.
Referenced by mg_send_dns_query(), and mg_set_protocol_dns().
mg_dns_insert_header()
int mg_dns_insert_header (struct mbuf * io, size_t pos, struct mg_dns_message * msg)
References mg_dns_message::flags, mg_dns_header::flags, mbuf_insert(), mg_dns_message::num_answers, mg_dns_header::num_answers, mg_dns_message::num_questions, mg_dns_header::num_questions, mg_dns_message::transaction_id, and mg_dns_header::transaction_id.
Referenced by dns_handler(), mg_send_dns_query(), and mg_set_protocol_dns().
mg_dns_next_record()
struct mg_dns_resource_record* mg_dns_next_record (struct mg_dns_message * msg, int query, struct mg_dns_resource_record * prev)
References mg_dns_message::answers, mg_dns_message::num_answers, and mg_dns_resource_record::rtype.
mg_dns_parse_record_data()
int mg_dns_parse_record_data (struct mg_dns_message * msg, struct mg_dns_resource_record * rr, void * data, size_t data_len)
References mg_str::len, MG_DNS_A_RECORD, MG_DNS_AAAA_RECORD, MG_DNS_CNAME_RECORD, mg_dns_uncompress_name(), mg_str::p, mg_dns_message::pkt, mg_dns_resource_record::rdata, and mg_dns_resource_record::rtype.
Referenced by resolve_cb().
mg_dns_uncompress_name()
size_t mg_dns_uncompress_name (struct mg_dns_message * msg, struct mg_str * name, char * dst, int dst_len)
References mg_str::len, mg_str::p, and mg_dns_message::pkt.
Referenced by mg_dns_parse_record_data(), and mg_set_protocol_dns().
mg_do_connect()
MG_INTERNAL struct mg_connection * mg_do_connect (struct mg_connection * nc, int proto, union socket_address * sa)
References mg_iface_vtable::connect_tcp, mg_iface_vtable::connect_udp, DBG, mg_connection::flags, mg_connection::iface, mg_add_conn(), MG_F_CONNECTING, mg_connection::mgr, socket_address::sin, and mg_iface::vtable.
Referenced by mg_connect_opt(), and resolve_cb().
mg_find_iface()
struct mg_iface* mg_find_iface (struct mg_mgr * mgr, const struct mg_iface_vtable * vtable, struct mg_iface * from)
References mg_mgr::ifaces, mg_open_listening_socket(), mg_mgr::num_ifaces, and mg_iface::vtable.
Referenced by mg_tun_create_client().
mg_forward()
void mg_forward (struct mg_connection * from, struct mg_connection * to)
References mbuf::buf, mbuf::len, mbuf_remove(), mg_send(), and mg_connection::recv_mbuf.
Referenced by mg_get_http_header(), and mg_register_http_endpoint().
mg_get_errno()
DO_NOT_WARN_UNUSED MG_INTERNAL int mg_get_errno (void)
Referenced by mg_accept_conn(), mg_http_send_error(), mg_is_error(), mg_parse_http_basic_auth(), mg_printf(), mg_recvfrom(), mg_register_http_endpoint(), mg_socket_if_connect_tcp(), mg_socket_if_connect_udp(), mg_socket_if_listen_tcp(), mg_socket_if_listen_udp(), and mg_write_to_socket().
mg_get_http_basic_auth()
int mg_get_http_basic_auth (struct http_message * hm, char * user, size_t user_len, char * pass, size_t pass_len)
References mg_get_http_header(), and mg_parse_http_basic_auth().
mg_get_http_header()
struct mg_str* mg_get_http_header (struct http_message * hm, const char * name)
References mbuf::buf, DATA_FILE, DBG, mg_connection::flags, http_message::header_names, http_message::header_values, mg_str::len, mbuf::len, LL_DEBUG, LOG, mbuf_remove(), MG_F_SEND_AND_CLOSE, mg_forward(), mg_http_get_proto_data(), MG_MAX_HTTP_SEND_MBUF, mg_ncasecmp(), mg_send(), mg_str::p, mg_connection::recv_mbuf, and mg_connection::send_mbuf.
Referenced by mg_get_http_basic_auth(), mg_get_line_len(), mg_http_handler(), mg_http_send_error(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), and mg_ws_handshake().
mg_get_http_var()
int mg_get_http_var (const struct mg_str * buf, const char * name, char * dst, size_t dst_len)
References mg_str::len, mg_ncasecmp(), mg_url_decode(), and mg_str::p.
mg_get_ip_address_of_nameserver()
static int mg_get_ip_address_of_nameserver (char * name, size_t name_len) [static]
References MG_DEFAULT_NAMESERVER.
Referenced by mg_resolve_async_opt().
mg_get_line_len()
static size_t mg_get_line_len (const char * buf, size_t buf_len) [static]
References mbuf::buf, c_strnstr(), mg_http_multipart_part::data, DBG, mg_http_proto_data::endpoint_handler, mg_http_multipart_part::file_name, mg_connection::flags, mg_connection::handler, mg_http_endpoint::handler, mg_str::len, mbuf::len, mg_connection::listener, mbuf_remove(), mg_call(), MG_F_CLOSE_IMMEDIATELY, MG_FREE, mg_get_http_header(), mg_http_call_endpoint_handler(), mg_http_get_endpoint_handler(), mg_http_get_proto_data(), mg_http_parse_header(), mg_ncasecmp(), MPS_BEGIN, MPS_FINALIZE, MPS_FINISHED, MPS_GOT_BOUNDARY, MPS_GOT_CHUNK, MPS_WAITING_FOR_BOUNDARY, MPS_WAITING_FOR_CHUNK, mg_str::p, mg_connection::recv_mbuf, http_message::uri, mg_connection::user_data, mg_http_multipart_part::user_data, and mg_http_multipart_part::var_name.
Referenced by mg_parse_multipart().
mg_handle_chunked()
MG_INTERNAL size_t mg_handle_chunked (struct mg_connection * nc, struct http_message * hm, char * buf, size_t blen)
References http_message::body, mg_http_proto_data_chuncked::body_len, mg_http_proto_data::chunk, mg_connection::flags, mg_connection::handler, mg_str::len, mbuf::len, http_message::message, mg_call(), MG_EV_HTTP_CHUNK, MG_F_DELETE_CHUNK, mg_http_get_proto_data(), mg_http_parse_chunk(), mg_str::p, mg_connection::recv_mbuf, and mg_connection::user_data.
Referenced by mg_http_handler().
mg_handle_incoming_websocket_frame()
static void mg_handle_incoming_websocket_frame (struct mg_connection * nc, struct websocket_message * wsm) [static]
References websocket_message::flags, mg_connection::handler, mg_call(), MG_EV_WEBSOCKET_CONTROL_FRAME, MG_EV_WEBSOCKET_FRAME, and mg_connection::user_data.
Referenced by mg_deliver_websocket_data().
mg_handle_tcp_read()
static void mg_handle_tcp_read (struct mg_connection * conn) [static]
References DBG, mg_connection::flags, MG_F_CLOSE_IMMEDIATELY, MG_F_SEND_AND_CLOSE, MG_F_SSL, MG_F_SSL_HANDSHAKE_DONE, MG_FREE, mg_if_recv_tcp_cb(), mg_is_error(), MG_MALLOC, MG_RECV_FUNC, MG_TCP_RECV_BUFFER_SIZE, recv_avail_size(), and mg_connection::sock.
Referenced by mg_mgr_handle_conn().
mg_handle_udp_read()
static void mg_handle_udp_read (struct mg_connection * nc) [static]
References DBG, mg_connection::flags, mg_connection::listener, MG_F_CLOSE_IMMEDIATELY, MG_F_SSL_HANDSHAKE_DONE, MG_F_WANT_READ, MG_F_WANT_WRITE, mg_if_accept_tcp_cb(), mg_if_connect_cb(), mg_if_recv_udp_cb(), mg_recvfrom(), socket_address::sa, mg_connection::sa, socket_address::sin, and mg_connection::sock.
Referenced by mg_mgr_handle_conn().
mg_hash_sha1_v()
void mg_hash_sha1_v (size_t num_msgs, const uint8_t * msgs[], const size_t * msg_lens, uint8_t * digest)
References cs_sha1_final(), cs_sha1_init(), cs_sha1_update(), and mg_hash_sha1_v().
Referenced by mg_hash_sha1_v(), and mg_ws_handshake().
mg_http_call_endpoint_handler()
static void mg_http_call_endpoint_handler (struct mg_connection * nc, int ev, struct http_message * hm) [static]
References mg_http_endpoint::auth_domain, mg_http_endpoint::auth_file, mg_http_proto_data::endpoint_handler, mg_connection::handler, mg_http_endpoint::handler, mg_connection::listener, mg_call(), MG_ENABLE_HTTP_STREAMING_MULTIPART, MG_EV_HTTP_REQUEST, mg_http_get_endpoint_handler(), mg_http_get_proto_data(), http_message::uri, and mg_connection::user_data.
Referenced by mg_get_line_len(), mg_http_get_endpoint_handler(), and mg_http_handler().
mg_http_conn_destructor()
static void mg_http_conn_destructor (void * proto_data) [static]
References mg_http_proto_data::endpoints, mg_str::len, mg_casecmp(), MG_FREE, mg_http_free_proto_data_endpoints(), mg_http_free_reverse_proxy_data(), mg_next_comma_list_entry(), mg_vcasecmp(), mg_str::p, and mg_http_proto_data::reverse_proxy_data.
Referenced by mg_http_get_proto_data().
mg_http_free_proto_data_endpoints()
static void mg_http_free_proto_data_endpoints (struct mg_http_endpoint ** ep) [static]
References mg_http_endpoint::auth_domain, mg_http_endpoint::auth_file, MG_FREE, mg_http_endpoint::next, mg_str::p, and mg_http_endpoint::uri_pattern.
Referenced by mg_http_conn_destructor().
mg_http_free_reverse_proxy_data()
static void mg_http_free_reverse_proxy_data (struct mg_reverse_proxy_data * rpd) [static]
References mg_connection::flags, mg_reverse_proxy_data::linked_conn, MG_F_SEND_AND_CLOSE, mg_http_get_proto_data(), and mg_http_proto_data::reverse_proxy_data.
Referenced by mg_http_conn_destructor().
mg_http_get_endpoint_handler()
struct mg_http_endpoint* mg_http_get_endpoint_handler (struct mg_connection * nc, struct mg_str * uri_path)
References mg_http_proto_data::endpoints, mg_http_call_endpoint_handler(), mg_http_get_proto_data(), mg_match_prefix_n(), mg_http_endpoint::next, and mg_http_endpoint::uri_pattern.
Referenced by mg_get_line_len(), mg_http_call_endpoint_handler(), and mg_http_handler().
mg_http_get_proto_data()
static struct mg_http_proto_data* mg_http_get_proto_data (struct mg_connection * c) [static]
References mg_http_multipart_stream::boundary, mg_http_multipart_stream::file_name, mg_http_proto_data_file::fp, MG_CALLOC, MG_FREE, mg_http_conn_destructor(), mg_connection::proto_data, mg_connection::proto_data_destructor, and mg_http_multipart_stream::var_name.
Referenced by mg_get_http_header(), mg_get_line_len(), mg_handle_chunked(), mg_http_call_endpoint_handler(), mg_http_free_reverse_proxy_data(), mg_http_get_endpoint_handler(), mg_http_handler(), mg_http_send_error(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_register_http_endpoint_opt(), and mg_ws_get_proto_data().
mg_http_get_request_len()
static int mg_http_get_request_len (const char * s, int buf_len) [static]
Referenced by mg_parse_http(), mg_parse_multipart(), and mg_register_http_endpoint().
mg_http_handler()
void mg_http_handler (struct mg_connection * nc, int ev, void *ev_data MG_UD_ARGvoid *user_data)
References http_message::body, mbuf::buf, DBG, deliver_chunk(), mg_http_proto_data::endpoint_handler, mg_http_multipart_part::file_name, mg_connection::flags, mg_connection::handler, mg_http_endpoint::handler, mg_str::len, mbuf::len, mg_connection::listener, mbuf_remove(), http_message::message, http_message::method, mg_call(), MG_EV_CLOSE, MG_EV_HTTP_REPLY, MG_EV_HTTP_REQUEST, MG_EV_RECV, MG_EV_WEBSOCKET_HANDSHAKE_DONE, MG_EV_WEBSOCKET_HANDSHAKE_REQUEST, MG_F_CLOSE_IMMEDIATELY, MG_F_IS_WEBSOCKET, MG_F_SEND_AND_CLOSE, mg_get_http_header(), mg_handle_chunked(), mg_http_call_endpoint_handler(), mg_http_get_endpoint_handler(), mg_http_get_proto_data(), MG_MAX_HTTP_REQUEST_SIZE, mg_parse_http(), mg_sock_addr_to_str(), MG_SOCK_STRINGIFY_IP, MG_SOCK_STRINGIFY_PORT, MG_UD_ARG, mg_vcasecmp(), mg_ws_handler(), mg_ws_handshake(), mg_str::p, mg_connection::proto_handler, mg_http_proto_data::rcvd, mg_connection::recv_mbuf, mg_connection::sa, mg_connection::send_mbuf, mg_http_multipart_part::status, http_message::uri, mg_connection::user_data, and mg_http_multipart_part::var_name.
Referenced by deliver_chunk(), and mg_set_protocol_http_websocket().
mg_http_parse_chunk()
static size_t mg_http_parse_chunk (char * buf, size_t len, char ** chunk_data, size_t * chunk_len) [static]
Referenced by mg_handle_chunked().
mg_http_parse_header()
int mg_http_parse_header (struct mg_str * hdr, const char * var_name, char * buf, size_t buf_size)
References mg_str::len, and mg_str::p.
Referenced by mg_get_line_len(), mg_parse_http_basic_auth(), and mg_parse_multipart().
mg_http_parse_headers()
static const char* mg_http_parse_headers (const char * s, const char * end, int len, struct http_message * req) [static]
References ARRAY_SIZE, http_message::body, http_message::header_names, http_message::header_values, mg_str::len, http_message::message, mg_ncasecmp(), mg_skip(), and mg_str::p.
Referenced by mg_parse_http(), and mg_register_http_endpoint().
mg_http_send_error()
void mg_http_send_error (struct mg_connection * nc, int code, const char * reason)
References DATA_FILE, mg_connection::flags, mg_str::len, LL_DEBUG, LOG, MG_F_SEND_AND_CLOSE, MG_FREE, mg_get_errno(), mg_get_http_header(), mg_http_get_proto_data(), mg_http_send_error(), MG_MALLOC, mg_match_prefix(), mg_mk_str(), mg_printf(), mg_send(), mg_send_head(), mg_send_response_line_s(), mg_status_message(), mg_time(), mg_vcasecmp(), mg_vcmp(), mg_str::p, and http_message::proto.
Referenced by mg_http_send_error(), mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_http_send_redirect()
void mg_http_send_redirect (struct mg_connection * nc, int status_code, const struct mg_str location, const struct mg_str extra_headers)
References mg_str::len, mg_asprintf(), MG_FREE, mg_send(), mg_send_response_line(), and mg_str::p.
mg_if_accept_new_conn()
struct mg_connection* mg_if_accept_new_conn (struct mg_connection * lc)
References DBG, mg_connection::flags, mg_connection::handler, mg_connection::iface, mg_connection::listener, mg_add_conn(), mg_create_connection(), MG_F_SSL, mg_connection::mgr, mg_connection::proto_handler, mg_connection::recv_mbuf_limit, mg_connection::sock, and mg_connection::user_data.
Referenced by mg_accept_conn(), and mg_tun_if_find_conn().
mg_if_accept_tcp_cb()
void mg_if_accept_tcp_cb (struct mg_connection * nc, union socket_address * sa, size_t sa_len)
References mg_call(), MG_EV_ACCEPT, mg_connection::sa, and mg_connection::user_data.
Referenced by mg_accept_conn(), and mg_handle_udp_read().
mg_if_connect_cb()
void mg_if_connect_cb (struct mg_connection * nc, int err)
References DBG, mg_connection::flags, mg_call(), MG_EV_CONNECT, MG_F_CLOSE_IMMEDIATELY, MG_F_CONNECTING, and mg_connection::user_data.
Referenced by mg_handle_udp_read(), and mg_mgr_handle_conn().
mg_if_create_iface()
struct mg_iface* mg_if_create_iface (const struct mg_iface_vtable * vtable, struct mg_mgr * mgr)
References mg_iface::data, MG_CALLOC, mg_iface::mgr, and mg_iface::vtable.
Referenced by mg_mgr_init_opt().
mg_if_get_conn_addr()
void mg_if_get_conn_addr (struct mg_connection * nc, int remote, union socket_address * sa)
References mg_iface_vtable::get_conn_addr, mg_connection::iface, and mg_iface::vtable.
Referenced by mg_conn_addr_to_str().
mg_if_poll()
void mg_if_poll (struct mg_connection * nc, time_t now)
References mg_connection::flags, mg_call(), MG_EV_POLL, MG_F_SSL, MG_F_SSL_HANDSHAKE_DONE, and mg_connection::user_data.
Referenced by mg_mgr_handle_conn().
mg_if_recv_tcp_cb()
void mg_if_recv_tcp_cb (struct mg_connection * nc, void * buf, int len, int own)
References mg_recv_common().
Referenced by mg_handle_tcp_read(), and mg_tun_client_handler().
mg_if_recv_udp_cb()
void mg_if_recv_udp_cb (struct mg_connection * nc, void * buf, int len, union socket_address * sa, size_t sa_len)
References DBG, mg_connection::flags, mg_connection::handler, mg_connection::iface, mg_connection::listener, mg_add_conn(), mg_call(), mg_create_connection_base(), MG_EV_ACCEPT, MG_F_LISTENING, MG_F_SEND_AND_CLOSE, MG_F_UDP, MG_FREE, mg_next(), mg_recv_common(), mg_connection::mgr, mg_connection::proto_handler, mg_connection::recv_mbuf_limit, mg_iface_vtable::recved, socket_address::sa, mg_connection::sa, mg_connection::sock, mg_connection::user_data, and mg_iface::vtable.
Referenced by mg_handle_udp_read().
mg_if_sent_cb()
void mg_if_sent_cb (struct mg_connection * nc, int num_sent)
References mbuf::buf, DBG, mg_connection::flags, mbuf_remove(), mbuf_trim(), mg_call(), MG_EV_SEND, MG_F_CLOSE_IMMEDIATELY, mg_connection::mgr, mg_connection::send_mbuf, and mg_connection::user_data.
Referenced by mg_write_to_socket().
mg_if_timer()
void mg_if_timer (struct mg_connection * c, double now)
References mg_connection::ev_timer_time, mg_call(), MG_EV_TIMER, and mg_connection::user_data.
Referenced by mg_mgr_handle_conn().
mg_is_big_endian()
int mg_is_big_endian (void)
mg_is_error()
static int mg_is_error (void) [static]
References mg_get_errno().
Referenced by mg_accept_conn(), mg_handle_tcp_read(), and mg_socket_if_connect_tcp().
mg_is_ws_first_fragment()
static int mg_is_ws_first_fragment (unsigned char flags) [static]
Referenced by mg_deliver_websocket_data().
mg_is_ws_fragment()
static int mg_is_ws_fragment (unsigned char flags) [static]
Referenced by mg_deliver_websocket_data().
mg_match_prefix()
int mg_match_prefix (const char * , int , const char *)
References mg_str::len, and mg_match_prefix_n().
Referenced by mg_http_send_error(), mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_match_prefix_n()
int mg_match_prefix_n (const struct mg_str , const struct mg_str)
References mg_str::len, mg_match_prefix_n(), mg_str::p, and str_util_lowercase().
Referenced by mg_http_get_endpoint_handler(), mg_match_prefix(), mg_match_prefix_n(), and mg_parse_http_basic_auth().
mg_mbuf_append_base64()
void mg_mbuf_append_base64 (struct mbuf * mbuf, const void * data, size_t len)
References cs_base64_finish(), cs_base64_init(), cs_base64_update(), and mg_mbuf_append_base64_putc().
mg_mbuf_append_base64_putc()
void mg_mbuf_append_base64_putc (char ch, void * user_data)
References mbuf_append().
Referenced by mg_basic_auth_header(), and mg_mbuf_append_base64().
mg_mgr_free()
void mg_mgr_free (struct mg_mgr * m)
References mg_mgr::active_connections, DBG, mg_iface_vtable::free, mg_mgr::ifaces, mg_close_conn(), MG_FREE, mg_mgr_poll(), mg_mgr::nameserver, mg_connection::next, mg_mgr::num_ifaces, and mg_iface::vtable.
Referenced by TBT::WSClientInterface::threadFunc().
mg_mgr_handle_conn()
void mg_mgr_handle_conn (struct mg_connection * nc, int fd_flags, double now)
References _MG_F_FD_CAN_READ, _MG_F_FD_CAN_WRITE, ctl_msg::callback, DBG, mg_connection::err, mg_connection::flags, mbuf::len, ctl_msg::message, mg_accept_conn(), MG_EV_POLL, MG_F_CLOSE_IMMEDIATELY, MG_F_CONNECTING, MG_F_LISTENING, MG_F_SSL, MG_F_UDP, MG_F_WANT_READ, MG_F_WANT_WRITE, mg_handle_tcp_read(), mg_handle_udp_read(), mg_if_connect_cb(), mg_if_poll(), mg_if_timer(), mg_next(), MG_RECV_FUNC, MG_SEND_FUNC, MG_UD_ARG, mg_write_to_socket(), mg_connection::recv_mbuf, mg_connection::send_mbuf, mg_connection::sock, and mg_connection::user_data.
Referenced by mg_socket_if_poll().
mg_mgr_init()
void mg_mgr_init (struct mg_mgr * m, void * user_data)
References mg_mgr_init_opt().
Referenced by TBT::WSClientInterface::threadFunc().
mg_mgr_init_opt()
void mg_mgr_init_opt (struct mg_mgr * m, void * user_data, struct mg_mgr_init_opts opts)
References DBG, mg_mgr::ifaces, mg_mgr_init_opts::ifaces, mg_iface_vtable::init, mg_mgr_init_opts::main_iface, mg_if_create_iface(), mg_ifaces, MG_MAIN_IFACE, MG_MALLOC, mg_num_ifaces, mg_mgr::nameserver, mg_mgr_init_opts::nameserver, mg_mgr::num_ifaces, mg_mgr_init_opts::num_ifaces, mg_mgr::user_data, and mg_iface::vtable.
Referenced by mg_mgr_init().
mg_mgr_poll()
time_t mg_mgr_poll (struct mg_mgr * m, int timeout_ms)
References mg_mgr::ifaces, LL_ERROR, LOG, mg_mgr::num_ifaces, mg_iface_vtable::poll, and mg_iface::vtable.
Referenced by mg_mgr_free(), and TBT::WSClientInterface::threadFunc().
mg_mk_str()
struct mg_str mg_mk_str (const char * s)
References mg_str::len.
Referenced by mg_bind_opt(), mg_connect_http_base(), mg_connect_http_opt(), mg_connect_ws_opt(), mg_http_send_error(), mg_mqtt_vmatch_topic_expression(), mg_next_comma_list_entry(), mg_next_comma_list_entry_n(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_register_http_endpoint_opt(), mg_send_response_line(), mg_send_websocket_handshake(), and mg_send_websocket_handshake3().
mg_mk_str_n()
struct mg_str mg_mk_str_n (const char * s, size_t len)
References mg_vcmp(), and WEAK.
Referenced by mg_next_comma_list_entry_n(), and mg_url_encode().
mg_mqtt_connack()
void mg_mqtt_connack (struct mg_connection * nc, uint8_t return_code)
References MG_MQTT_CMD_CONNACK, mg_mqtt_prepend_header(), and mg_send().
Referenced by mg_mqtt_disconnect().
mg_mqtt_disconnect()
void mg_mqtt_disconnect (struct mg_connection * nc)
References mg_connection::flags, mg_str::len, LIST_FIRST, LIST_INIT, LIST_INSERT_HEAD, LIST_NEXT, LIST_REMOVE, mg_connection::listener, mg_mqtt_message::message_id, mg_asprintf(), MG_CALLOC, MG_EV_ACCEPT, MG_EV_CLOSE, MG_EV_MQTT_CONNACK_ACCEPTED, MG_EV_MQTT_CONNACK_SERVER_UNAVAILABLE, MG_EV_MQTT_CONNECT, MG_EV_MQTT_PUBLISH, MG_EV_MQTT_SUBSCRIBE, MG_F_CLOSE_IMMEDIATELY, MG_FREE, MG_MALLOC, MG_MQTT_CMD_DISCONNECT, mg_mqtt_connack(), mg_mqtt_next_subscribe_topic(), mg_mqtt_prepend_header(), mg_mqtt_publish(), mg_mqtt_suback(), mg_mqtt_vmatch_topic_expression(), MG_REALLOC, mg_set_protocol_mqtt(), mg_str::p, mg_mqtt_message::payload, mg_connection::proto_data, mg_mqtt_topic_expression::qos, mg_mqtt_message::topic, mg_mqtt_topic_expression::topic, and mg_connection::user_data.
mg_mqtt_match_topic_expression()
int mg_mqtt_match_topic_expression (struct mg_str exp, struct mg_str topic)
References mg_str::len, and mg_str::p.
Referenced by mg_mqtt_vmatch_topic_expression().
mg_mqtt_next_subscribe_topic()
int mg_mqtt_next_subscribe_topic (struct mg_mqtt_message * msg, struct mg_str * topic, uint8_t * qos, int pos)
References mg_str::len, mg_str::p, and mg_mqtt_message::payload.
Referenced by mg_mqtt_disconnect().
mg_mqtt_ping()
void mg_mqtt_ping (struct mg_connection * nc)
References MG_MQTT_CMD_PINGREQ, and mg_mqtt_prepend_header().
Referenced by mqtt_handler().
mg_mqtt_pong()
void mg_mqtt_pong (struct mg_connection * nc)
References MG_MQTT_CMD_PINGRESP, and mg_mqtt_prepend_header().
mg_mqtt_prepend_header()
static void mg_mqtt_prepend_header (struct mg_connection * nc, uint8_t cmd, uint8_t flags, size_t len) [static]
References mg_mqtt_proto_data::last_control_time, mbuf::len, mbuf_insert(), mg_time(), mg_connection::proto_data, and mg_connection::send_mbuf.
Referenced by mg_mqtt_connack(), mg_mqtt_disconnect(), mg_mqtt_ping(), mg_mqtt_pong(), mg_mqtt_publish(), mg_mqtt_suback(), mg_mqtt_subscribe(), mg_mqtt_unsubscribe(), mg_send_mqtt_handshake_opt(), and mg_send_mqtt_short_command().
mg_mqtt_proto_data_destructor()
static void mg_mqtt_proto_data_destructor (void * proto_data) [static]
References MG_FREE.
Referenced by mg_set_protocol_mqtt().
mg_mqtt_puback()
void mg_mqtt_puback (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_PUBACK, and mg_send_mqtt_short_command().
mg_mqtt_pubcomp()
void mg_mqtt_pubcomp (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_PUBCOMP, and mg_send_mqtt_short_command().
mg_mqtt_publish()
void mg_mqtt_publish (struct mg_connection * nc, const char * topic, uint16_t message_id, int flags, const void * data, size_t len)
References mbuf::len, MG_MQTT_CMD_PUBLISH, MG_MQTT_GET_QOS, mg_mqtt_prepend_header(), mg_send(), and mg_connection::send_mbuf.
Referenced by mg_mqtt_disconnect().
mg_mqtt_pubrec()
void mg_mqtt_pubrec (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_PUBREC, and mg_send_mqtt_short_command().
mg_mqtt_pubrel()
void mg_mqtt_pubrel (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_PUBREL, and mg_send_mqtt_short_command().
mg_mqtt_suback()
void mg_mqtt_suback (struct mg_connection * nc, uint8_t * qoss, size_t qoss_len, uint16_t message_id)
References MG_MQTT_CMD_SUBACK, mg_mqtt_prepend_header(), MG_MQTT_QOS, and mg_send().
Referenced by mg_mqtt_disconnect().
mg_mqtt_subscribe()
void mg_mqtt_subscribe (struct mg_connection * nc, const struct mg_mqtt_topic_expression * topics, size_t topics_len, uint16_t message_id)
References mbuf::len, MG_MQTT_CMD_SUBSCRIBE, mg_mqtt_prepend_header(), MG_MQTT_QOS, mg_send(), and mg_connection::send_mbuf.
mg_mqtt_unsuback()
void mg_mqtt_unsuback (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_UNSUBACK, and mg_send_mqtt_short_command().
mg_mqtt_unsubscribe()
void mg_mqtt_unsubscribe (struct mg_connection * nc, char ** topics, size_t topics_len, uint16_t message_id)
References mbuf::len, MG_MQTT_CMD_UNSUBSCRIBE, mg_mqtt_prepend_header(), MG_MQTT_QOS, mg_send(), and mg_connection::send_mbuf.
mg_mqtt_vmatch_topic_expression()
int mg_mqtt_vmatch_topic_expression (const char * exp, struct mg_str topic)
References mg_mk_str(), and mg_mqtt_match_topic_expression().
Referenced by mg_mqtt_disconnect().
mg_ncasecmp()
int mg_ncasecmp (const char * s1, const char * s2, size_t len)
References mg_casecmp(), str_util_lowercase(), and WEAK.
Referenced by mbuf_remove(), mg_casecmp(), mg_get_http_header(), mg_get_http_var(), mg_get_line_len(), mg_http_parse_headers(), mg_parse_address(), mg_parse_http_basic_auth(), mg_parse_multipart(), mg_vcasecmp(), and str_util_lowercase().
mg_next()
struct mg_connection* mg_next (struct mg_mgr * s, struct mg_connection * conn)
References mg_mgr::active_connections, ctl_msg::callback, ctl_msg::message, MG_RECV_FUNC, MG_SEND_FUNC, and mg_connection::next.
Referenced by mg_if_recv_udp_cb(), and mg_mgr_handle_conn().
mg_next_comma_list_entry()
const char* mg_next_comma_list_entry (const char * , struct mg_str * , struct mg_str *)
References mg_mk_str(), mg_next_comma_list_entry_n(), and mg_str::p.
Referenced by mg_check_ip_acl(), mg_http_conn_destructor(), and mg_parse_http_basic_auth().
mg_next_comma_list_entry_n()
struct mg_str mg_next_comma_list_entry_n (struct mg_str list, struct mg_str * val, struct mg_str * eq_val)
References mg_str::len, mg_mk_str(), mg_mk_str_n(), mg_strchr(), and mg_str::p.
Referenced by mg_next_comma_list_entry().
mg_normalize_uri_path()
int mg_normalize_uri_path (const struct mg_str * in, struct mg_str * out)
References mg_str::len, mg_vcmp(), mg_str::p, and parse_uri_component().
Referenced by mg_assemble_uri(), and mg_parse_http_basic_auth().
mg_open_listening_socket()
static sock_t mg_open_listening_socket (union socket_address * sa, int type, int proto) [static]
References MG_LWIP, mg_set_non_blocking_mode(), socket_address::sa, socket_address::sin, and socket_address::sin6.
Referenced by mg_find_iface(), mg_socket_if_listen_tcp(), and mg_socket_if_listen_udp().
mg_parse_address()
MG_INTERNAL int mg_parse_address (const char * str, union socket_address * sa, int * proto, char * host, size_t host_len)
References mg_ncasecmp(), mg_resolve_from_hosts_file(), socket_address::sin, and socket_address::sin6.
Referenced by mg_bind_opt(), and mg_connect_opt().
mg_parse_dns()
int mg_parse_dns (const char * buf, int len, struct mg_dns_message * msg)
References mg_dns_message::answers, ARRAY_SIZE, mg_dns_message::flags, mg_dns_header::flags, mg_str::len, mg_parse_dns_resource_record(), mg_dns_message::num_answers, mg_dns_header::num_answers, mg_dns_message::num_questions, mg_dns_header::num_questions, mg_str::p, mg_dns_message::pkt, mg_dns_message::questions, mg_dns_message::transaction_id, and mg_dns_header::transaction_id.
Referenced by dns_handler(), and mg_resolve_async_eh().
mg_parse_dns_resource_record()
static unsigned char* mg_parse_dns_resource_record (unsigned char * data, unsigned char * end, struct mg_dns_resource_record * rr, int reply) [static]
References mg_dns_resource_record::kind, mg_str::len, MG_DNS_ANSWER, MG_DNS_QUESTION, mg_dns_resource_record::name, mg_str::p, mg_dns_resource_record::rclass, mg_dns_resource_record::rdata, mg_dns_resource_record::rtype, and mg_dns_resource_record::ttl.
Referenced by mg_parse_dns().
mg_parse_http()
int mg_parse_http (const char * s, int n, struct http_message * hm, int is_req)
References http_message::body, mg_str::len, http_message::message, http_message::method, mg_http_get_request_len(), mg_http_parse_headers(), mg_skip(), mg_vcasecmp(), mg_str::p, http_message::proto, http_message::query_string, http_message::resp_code, http_message::resp_status_msg, and http_message::uri.
Referenced by mg_http_handler().
mg_parse_http_basic_auth()
int mg_parse_http_basic_auth (struct mg_str * hdr, char * user, size_t user_len, char * pass, size_t pass_len)
References ARRAY_SIZE, http_message::body, cs_base64_decode(), cs_md5_final(), cs_md5_init(), cs_md5_update(), cs_to_hex(), mg_http_multipart_part::data, DBG, mg_connect_opts::error_string, mg_http_multipart_part::file_name, mg_connection::flags, http_message::header_names, http_message::header_values, mg_str::len, mg_reverse_proxy_data::linked_conn, LL_DEBUG, LL_ERROR, LOG, http_message::message, http_message::method, mg_asprintf(), MG_CALLOC, MG_CB, mg_check_digest_auth(), mg_check_ip_acl(), mg_conn_addr_to_str(), mg_connect_http_base(), MG_ENABLE_HTTP_WEBDAV, MG_EV_CLOSE, MG_EV_CONNECT, MG_EV_HTTP_REPLY, MG_F_CLOSE_IMMEDIATELY, MG_F_SEND_AND_CLOSE, MG_FREE, mg_get_errno(), mg_get_http_header(), mg_hash_md5_v(), mg_http_check_digest_auth(), mg_http_create_digest_auth_header(), mg_http_get_proto_data(), mg_http_parse_header(), mg_http_send_error(), MG_INTERNAL, MG_MALLOC, mg_match_prefix(), mg_match_prefix_n(), MG_MAX_HTTP_HEADERS, MG_MAX_PATH, mg_mk_str(), MG_MK_STR, mg_ncasecmp(), mg_next_comma_list_entry(), mg_normalize_uri_path(), MG_NULL_STR, mg_printf(), mg_printf_http_chunk(), MG_REALLOC, mg_send(), mg_send_http_chunk(), mg_send_response_line(), MG_SOCK_STRINGIFY_PORT, mg_strncmp(), mg_time(), MG_UD_ARG, mg_url_decode(), mg_url_encode(), mg_vcasecmp(), mg_vcmp(), mg_connection::mgr, mg_str::p, parse_uri_component(), http_message::proto, http_message::query_string, mg_http_proto_data::reverse_proxy_data, mg_connection::sa, socket_address::sin, mg_http_multipart_part::status, http_message::uri, and mg_http_multipart_part::user_data.
Referenced by mg_get_http_basic_auth().
mg_parse_multipart()
size_t mg_parse_multipart (const char * buf, size_t buf_len, char * var_name, size_t var_name_len, char * file_name, size_t file_name_len, const char ** data, size_t * data_len)
References mg_str::len, mg_get_line_len(), mg_http_get_request_len(), mg_http_parse_header(), mg_ncasecmp(), and mg_str::p.
mg_parse_uri()
int mg_parse_uri (const struct mg_str uri, struct mg_str * scheme, struct mg_str * user_info, struct mg_str * host, unsigned int * port, struct mg_str * path, struct mg_str * query, struct mg_str * fragment)
References mg_str::len, mg_str::p, and parse_uri_component().
Referenced by mg_connect_http_base().
mg_printf()
int mg_printf (struct mg_connection * conn, const char * fmt, ...)
References DBG, mg_get_errno(), and mg_vprintf().
Referenced by mg_connect_http_opt(), mg_http_send_error(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_send_head(), mg_send_response_line_s(), mg_send_websocket_handshake3v(), and mg_ws_handshake().
mg_printf_html_escape()
void mg_printf_html_escape (struct mg_connection * nc, const char * fmt, ...)
References mg_str::len, mg_avprintf(), MG_FREE, mg_send(), and MG_VPRINTF_BUFFER_SIZE.
mg_printf_http_chunk()
void mg_printf_http_chunk (struct mg_connection * nc, const char * fmt, ...)
References mg_str::len, mg_avprintf(), MG_FREE, mg_send_http_chunk(), and MG_VPRINTF_BUFFER_SIZE.
Referenced by mg_parse_http_basic_auth().
mg_printf_websocket_frame()
void mg_printf_websocket_frame (struct mg_connection * nc, int op, const char * fmt, ...)
References mg_avprintf(), MG_FREE, mg_send_websocket_frame(), and MG_VPRINTF_BUFFER_SIZE.
mg_recv_common()
MG_INTERNAL void mg_recv_common (struct mg_connection * nc, void * buf, int len, int own)
References mbuf::buf, DBG, mg_connection::flags, mg_connection::last_io_time, mbuf::len, mbuf_append(), mbuf_free(), mg_call(), MG_EV_RECV, MG_F_CLOSE_IMMEDIATELY, MG_FREE, mg_time(), mg_connection::mgr, mg_connection::recv_mbuf, mbuf::size, and mg_connection::user_data.
Referenced by mg_if_recv_tcp_cb(), and mg_if_recv_udp_cb().
mg_recvfrom()
static int mg_recvfrom (struct mg_connection * nc, union socket_address * sa, socklen_t * sa_len, char ** buf) [static]
References DBG, MG_FREE, mg_get_errno(), MG_MALLOC, MG_UDP_RECV_BUFFER_SIZE, socket_address::sa, and mg_connection::sock.
Referenced by mg_handle_udp_read().
mg_register_http_endpoint()
void mg_register_http_endpoint (struct mg_connection * nc, const char * uri_path, MG_CB(mg_event_handler_t handler, void *user_data))
References mg_ssi_call_ctx::arg, ARRAY_SIZE, blk, http_message::body, mbuf::buf, DATA_PUT, DBG, mg_ssi_call_ctx::file, mg_connection::flags, http_message::header_names, http_message::header_values, mg_str::len, mbuf::len, mbuf_remove(), http_message::message, http_message::method, mg_add_sock(), mg_call(), MG_CGI_ENVIRONMENT_SIZE, mg_conn_addr_to_str(), MG_EV_CLOSE, MG_EV_RECV, MG_EV_SSI_CALL, MG_EV_SSI_CALL_CTX, MG_F_CLOSE_IMMEDIATELY, MG_F_SEND_AND_CLOSE, MG_F_SSL, mg_forward(), MG_FREE, mg_get_errno(), mg_get_http_header(), mg_http_get_proto_data(), mg_http_get_request_len(), mg_http_parse_headers(), mg_http_send_error(), MG_INTERNAL, MG_MALLOC, mg_match_prefix(), MG_MAX_HTTP_REQUEST_SIZE, MG_MAX_PATH, mg_mk_str(), MG_MK_STR, mg_printf(), mg_register_http_endpoint_opt(), mg_send(), mg_send_response_line(), mg_set_close_on_exec(), MG_SOCK_STRINGIFY_IP, MG_SOCK_STRINGIFY_PORT, MG_SOCK_STRINGIFY_REMOTE, mg_sock_to_str(), mg_socketpair(), mg_time(), MG_UD_ARG, mg_url_encode(), mg_vcmp(), MG_VERSION, mg_connection::mgr, mg_str::p, http_message::query_string, mg_connection::recv_mbuf, mg_ssi_call_ctx::req, mg_connection::sock, http_message::uri, mg_connection::user_data, and mg_http_endpoint_opts::user_data.
mg_register_http_endpoint_opt()
void mg_register_http_endpoint_opt (struct mg_connection * nc, const char * uri_path, mg_event_handler_t handler, struct mg_http_endpoint_opts opts)
References mg_http_endpoint_opts::auth_domain, mg_http_endpoint::auth_domain, mg_http_endpoint_opts::auth_file, mg_http_endpoint::auth_file, mg_http_proto_data::endpoints, mg_http_endpoint::handler, MG_CALLOC, mg_http_get_proto_data(), mg_mk_str(), mg_strdup(), mg_http_endpoint::next, mg_http_endpoint::uri_pattern, and mg_http_endpoint_opts::user_data.
Referenced by mg_register_http_endpoint().
mg_remove_conn()
MG_INTERNAL void mg_remove_conn (struct mg_connection * c)
References mg_mgr::active_connections, mg_connection::iface, mg_connection::mgr, mg_connection::next, mg_connection::prev, mg_iface_vtable::remove_conn, and mg_iface::vtable.
Referenced by mg_close_conn().
mg_resolve_async()
int mg_resolve_async (struct mg_mgr * mgr, const char * name, int query, mg_resolve_callback_t cb, void * data)
References mg_resolve_async_opt().
mg_resolve_async_eh()
static void mg_resolve_async_eh (struct mg_connection * nc, int ev, void *data MG_UD_ARGvoid *user_data) [static]
References mbuf::buf, mg_resolve_async_request::callback, mg_resolve_async_request::data, DBG, mg_resolve_async_request::err, mg_connection::flags, mg_resolve_async_request::last_time, mbuf::len, LL_ERROR, LOG, mg_resolve_async_request::max_retries, mbuf_remove(), MG_EV_CLOSE, MG_EV_CONNECT, MG_EV_POLL, MG_EV_RECV, MG_EV_SEND, MG_EV_TIMER, MG_F_CLOSE_IMMEDIATELY, MG_FREE, MG_MALLOC, mg_parse_dns(), MG_RESOLVE_EXCEEDED_RETRY_COUNT, MG_RESOLVE_NO_ANSWERS, MG_RESOLVE_OK, MG_RESOLVE_TIMEOUT, mg_send_dns_query(), mg_sock_addr_to_str(), MG_SOCK_STRINGIFY_IP, mg_time(), mg_resolve_async_request::name, mg_dns_message::num_answers, mg_resolve_async_request::query, mg_connection::recv_mbuf, mg_resolve_async_request::retries, mg_connection::sa, mg_connection::send_mbuf, mg_resolve_async_request::timeout, and mg_connection::user_data.
Referenced by mg_resolve_async_opt().
mg_resolve_async_opt()
int mg_resolve_async_opt (struct mg_mgr * mgr, const char * name, int query, mg_resolve_callback_t cb, void * data, struct mg_resolve_async_opts opts)
References mg_resolve_async_request::callback, mg_resolve_async_request::data, DBG, mg_resolve_async_opts::dns_conn, mg_resolve_async_opts::max_retries, mg_resolve_async_request::max_retries, MG_CALLOC, MG_CB, mg_connect(), MG_DEFAULT_NAMESERVER, MG_FREE, mg_get_ip_address_of_nameserver(), mg_resolve_async_eh(), mg_resolve_async_request::name, mg_mgr::nameserver, mg_resolve_async_opts::nameserver, mg_resolve_async_request::query, mg_resolve_async_opts::timeout, mg_resolve_async_request::timeout, and mg_connection::user_data.
Referenced by mg_connect_opt(), and mg_resolve_async().
mg_resolve_from_hosts_file()
int mg_resolve_from_hosts_file (const char * name, union socket_address * usa)
References socket_address::sin.
Referenced by mg_parse_address().
mg_send()
void mg_send (struct mg_connection * nc, const void * buf, int len)
References mg_connection::flags, mg_connection::iface, mg_connection::last_io_time, MG_F_UDP, mg_time(), mg_iface_vtable::tcp_send, mg_iface_vtable::udp_send, and mg_iface::vtable.
Referenced by dns_handler(), mg_forward(), mg_get_http_header(), mg_http_send_error(), mg_http_send_redirect(), mg_mqtt_connack(), mg_mqtt_publish(), mg_mqtt_suback(), mg_mqtt_subscribe(), mg_mqtt_unsubscribe(), mg_parse_http_basic_auth(), mg_printf_html_escape(), mg_register_http_endpoint(), mg_send_dns_query(), mg_send_head(), mg_send_http_chunk(), mg_send_mqtt_handshake_opt(), mg_send_mqtt_short_command(), mg_send_websocket_frame(), mg_send_websocket_framev(), mg_send_ws_header(), mg_set_nameserver(), mg_set_protocol_dns(), mg_tun_send_frame(), and mg_vprintf().
mg_send_dns_query()
void mg_send_dns_query (struct mg_connection * nc, const char * name, int query_type)
References mbuf::buf, DBG, mg_connection::flags, mg_dns_message::flags, mg_dns_resource_record::kind, mbuf::len, mbuf_free(), mbuf_init(), mbuf_insert(), MG_CALLOC, mg_dns_encode_record(), mg_dns_insert_header(), MG_DNS_QUESTION, mg_dns_tid, MG_F_UDP, MG_FREE, mg_send(), mg_dns_message::num_questions, mg_dns_message::questions, mg_dns_resource_record::rclass, mg_dns_resource_record::rtype, and mg_dns_message::transaction_id.
Referenced by mg_resolve_async_eh().
mg_send_head()
void mg_send_head (struct mg_connection * c, int status_code, int64_t content_length, const char * extra_headers)
References mg_printf(), mg_send(), and mg_send_response_line().
Referenced by mg_http_send_error().
mg_send_http_chunk()
void mg_send_http_chunk (struct mg_connection * nc, const char * buf, size_t len)
References mg_send().
Referenced by mg_parse_http_basic_auth(), and mg_printf_http_chunk().
mg_send_mqtt_handshake()
void mg_send_mqtt_handshake (struct mg_connection * nc, const char * client_id)
References mg_send_mqtt_handshake_opt().
mg_send_mqtt_handshake_opt()
void mg_send_mqtt_handshake_opt (struct mg_connection * nc, const char * client_id, struct mg_send_mqtt_handshake_opts opts)
References mg_send_mqtt_handshake_opts::flags, mg_send_mqtt_handshake_opts::keep_alive, mg_mqtt_proto_data::keep_alive, MG_MQTT_CMD_CONNECT, MG_MQTT_HAS_PASSWORD, MG_MQTT_HAS_USER_NAME, MG_MQTT_HAS_WILL, mg_mqtt_prepend_header(), mg_send(), mg_send_mqtt_handshake_opts::password, mg_connection::proto_data, mg_send_mqtt_handshake_opts::user_name, mg_send_mqtt_handshake_opts::will_message, and mg_send_mqtt_handshake_opts::will_topic.
Referenced by mg_send_mqtt_handshake().
mg_send_mqtt_short_command()
static void mg_send_mqtt_short_command (struct mg_connection * nc, uint8_t cmd, uint16_t message_id) [static]
References MG_MQTT_CMD_PUBREL, mg_mqtt_prepend_header(), and mg_send().
Referenced by mg_mqtt_puback(), mg_mqtt_pubcomp(), mg_mqtt_pubrec(), mg_mqtt_pubrel(), and mg_mqtt_unsuback().
mg_send_response_line()
void mg_send_response_line (struct mg_connection * nc, int status_code, const char * extra_headers)
References mg_mk_str(), and mg_send_response_line_s().
Referenced by mg_http_send_redirect(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), and mg_send_head().
mg_send_response_line_s()
void mg_send_response_line_s (struct mg_connection * nc, int status_code, const struct mg_str extra_headers)
References mg_str::len, mg_printf(), mg_status_message(), and mg_str::p.
Referenced by mg_http_send_error(), and mg_send_response_line().
mg_send_websocket_frame()
void mg_send_websocket_frame (struct mg_connection * nc, int op, const void * data, size_t len)
References DBG, mg_connection::flags, MG_F_SEND_AND_CLOSE, mg_send(), mg_send_ws_header(), mg_ws_mask_frame(), mg_connection::send_mbuf, and WEBSOCKET_OP_CLOSE.
Referenced by TBT::ev_handler_StateChange(), mg_printf_websocket_frame(), and mg_ws_handler().
mg_send_websocket_framev()
void mg_send_websocket_framev (struct mg_connection * nc, int op, const struct mg_str * strv, int strvcnt)
References mg_connection::flags, mg_str::len, MG_F_SEND_AND_CLOSE, mg_send(), mg_send_ws_header(), mg_ws_mask_frame(), mg_connection::send_mbuf, and WEBSOCKET_OP_CLOSE.
Referenced by mg_tun_send_frame().
mg_send_websocket_handshake()
void mg_send_websocket_handshake (struct mg_connection * nc, const char * path, const char * extra_headers)
References mg_mk_str(), MG_NULL_STR, and mg_send_websocket_handshake3v().
mg_send_websocket_handshake2()
void mg_send_websocket_handshake2 (struct mg_connection * nc, const char * path, const char * host, const char * protocol, const char * extra_headers)
References mg_send_websocket_handshake3().
mg_send_websocket_handshake3()
void mg_send_websocket_handshake3 (struct mg_connection * nc, const char * path, const char * host, const char * protocol, const char * extra_headers, const char * user, const char * pass)
References mg_mk_str(), and mg_send_websocket_handshake3v().
Referenced by mg_send_websocket_handshake2().
mg_send_websocket_handshake3v()
void mg_send_websocket_handshake3v (struct mg_connection * nc, const struct mg_str path, const struct mg_str host, const struct mg_str protocol, const struct mg_str extra_headers, const struct mg_str user, const struct mg_str pass)
References mbuf::buf, mg_str::len, mbuf::len, mbuf_free(), mbuf_init(), mg_base64_encode(), mg_basic_auth_header(), mg_printf(), mg_ws_random_mask(), and mg_str::p.
Referenced by mg_connect_ws_opt(), mg_send_websocket_handshake(), and mg_send_websocket_handshake3().
mg_send_ws_header()
static void mg_send_ws_header (struct mg_connection * nc, int op, size_t len, struct ws_mask_ctx * ctx) [static]
References mbuf::len, mg_connection::listener, ws_mask_ctx::mask, mg_send(), mg_ws_random_mask(), ws_mask_ctx::pos, mg_connection::send_mbuf, and WEBSOCKET_DONT_FIN.
Referenced by mg_send_websocket_frame(), and mg_send_websocket_framev().
mg_set_close_on_exec()
void mg_set_close_on_exec (sock_t sock)
Referenced by mg_register_http_endpoint(), mg_socket_if_poll(), and mg_socket_if_sock_set().
mg_set_nameserver()
void mg_set_nameserver (struct mg_mgr * mgr, const char * nameserver)
References mbuf::buf, mg_connection::flags, mg_connection::handler, mbuf::len, mbuf_append(), mbuf_free(), mbuf_init(), mbuf_remove(), MG_CALLOC, MG_EV_RECV, MG_F_UDP, MG_FREE, mg_send(), mg_tun_reconnect(), MG_UD_ARG, mg_mgr::nameserver, mg_connection::proto_handler, and mg_connection::recv_mbuf.
mg_set_non_blocking_mode()
void mg_set_non_blocking_mode (sock_t sock)
Referenced by mg_open_listening_socket(), mg_socket_if_connect_tcp(), and mg_socket_if_sock_set().
mg_set_protocol_dns()
void mg_set_protocol_dns (struct mg_connection * nc)
References mg_dns_message::answers, dns_handler(), mg_connection::flags, mg_dns_resource_record::kind, mg_mqtt_message::len, mbuf_insert(), MG_DNS_ANSWER, mg_dns_copy_questions(), mg_dns_encode_record(), mg_dns_insert_header(), mg_dns_uncompress_name(), MG_F_UDP, MG_MAX_DNS_ANSWERS, mg_send(), mg_dns_resource_record::name, mg_dns_message::num_answers, mg_connection::proto_handler, and mg_connection::send_mbuf.
mg_set_protocol_http_websocket()
void mg_set_protocol_http_websocket (struct mg_connection * nc)
References mg_http_handler(), and mg_connection::proto_handler.
Referenced by mg_connect_http_base(), and TBT::WSClientInterface::threadFunc().
mg_set_protocol_mqtt()
void mg_set_protocol_mqtt (struct mg_connection * nc)
References MG_CALLOC, mg_mqtt_proto_data_destructor(), mqtt_handler(), mg_connection::proto_data, mg_connection::proto_data_destructor, and mg_connection::proto_handler.
Referenced by mg_mqtt_disconnect(), and mqtt_handler().
mg_set_timer()
double mg_set_timer (struct mg_connection * c, double timestamp)
References DBG, mg_connection::ev_timer_time, mg_connection::flags, MG_F_RESOLVING, and mg_connection::priv_2.
Referenced by mg_tun_send_frame().
mg_skip()
const char* mg_skip (const char * s, const char * end, const char * delims, struct mg_str * v)
References ARRAY_SIZE, DBG, mg_str::len, MG_MAX_PATH, and mg_str::p.
Referenced by mg_http_parse_headers(), and mg_parse_http().
mg_sock_addr_to_str()
int mg_sock_addr_to_str (const union socket_address * sa, char * buf, size_t len, int flags)
References MG_SOCK_STRINGIFY_IP, MG_SOCK_STRINGIFY_PORT, socket_address::sa, socket_address::sin, and socket_address::sin6.
Referenced by TBT::ev_handler(), mg_conn_addr_to_str(), mg_http_handler(), mg_resolve_async_eh(), and mg_sock_to_str().
mg_sock_get_addr()
static void mg_sock_get_addr (sock_t sock, int remote, union socket_address * sa) [static]
References socket_address::sa.
Referenced by mg_sock_to_str(), and mg_socket_if_get_conn_addr().
mg_sock_set()
void mg_sock_set (struct mg_connection * nc, sock_t sock)
References mg_connection::iface, mg_iface_vtable::sock_set, and mg_iface::vtable.
Referenced by mg_accept_conn(), mg_add_sock_opt(), mg_socket_if_listen_tcp(), and mg_socket_if_listen_udp().
mg_sock_to_str()
void mg_sock_to_str (sock_t sock, char * buf, size_t len, int flags)
References mg_sock_addr_to_str(), mg_sock_get_addr(), and MG_SOCK_STRINGIFY_REMOTE.
Referenced by mg_register_http_endpoint().
mg_socket_if_add_conn()
void mg_socket_if_add_conn (struct mg_connection * nc)
mg_socket_if_connect_tcp()
void mg_socket_if_connect_tcp (struct mg_connection * nc, const union socket_address * sa)
References DBG, mg_connection::err, mg_get_errno(), mg_is_error(), mg_set_non_blocking_mode(), socket_address::sa, socket_address::sin, and mg_connection::sock.
mg_socket_if_connect_udp()
void mg_socket_if_connect_udp (struct mg_connection * nc)
References mg_connection::err, mg_connection::flags, MG_F_ENABLE_BROADCAST, mg_get_errno(), and mg_connection::sock.
mg_socket_if_create_conn()
int mg_socket_if_create_conn (struct mg_connection * nc)
mg_socket_if_destroy_conn()
void mg_socket_if_destroy_conn (struct mg_connection * nc)
References mg_connection::flags, mg_connection::listener, MG_F_UDP, and mg_connection::sock.
mg_socket_if_free()
void mg_socket_if_free (struct mg_iface * iface)
mg_socket_if_get_conn_addr()
void mg_socket_if_get_conn_addr (struct mg_connection * nc, int remote, union socket_address * sa)
References mg_connection::flags, MG_F_UDP, mg_sock_get_addr(), mg_connection::sa, and mg_connection::sock.
mg_socket_if_init()
void mg_socket_if_init (struct mg_iface * iface)
References DBG, mg_socketpair(), and mg_iface::mgr.
mg_socket_if_listen_tcp()
int mg_socket_if_listen_tcp (struct mg_connection * nc, union socket_address * sa)
References mg_get_errno(), mg_open_listening_socket(), and mg_sock_set().
mg_socket_if_listen_udp()
int mg_socket_if_listen_udp (struct mg_connection * nc, union socket_address * sa)
References mg_get_errno(), mg_open_listening_socket(), and mg_sock_set().
mg_socket_if_poll()
time_t mg_socket_if_poll (struct mg_iface * iface, int timeout_ms)
References _MG_F_FD_CAN_READ, _MG_F_FD_CAN_WRITE, _MG_F_FD_ERROR, mg_mgr::active_connections, DBG, mg_connection::ev_timer_time, mg_connection::flags, mbuf::len, mg_connection::listener, mg_add_to_set(), mg_close_conn(), MG_F_CLOSE_IMMEDIATELY, MG_F_CONNECTING, MG_F_SEND_AND_CLOSE, MG_F_UDP, MG_F_WANT_READ, MG_F_WANT_WRITE, MG_INTERNAL, mg_mgr_handle_conn(), mg_set_close_on_exec(), mg_socketpair(), mg_time(), mg_iface::mgr, mg_connection::next, mg_connection::recv_mbuf, mg_connection::recv_mbuf_limit, socket_address::sa, mg_connection::send_mbuf, socket_address::sin, and mg_connection::sock.
mg_socket_if_recved()
void mg_socket_if_recved (struct mg_connection * nc, size_t len)
mg_socket_if_remove_conn()
void mg_socket_if_remove_conn (struct mg_connection * nc)
mg_socket_if_sock_set()
void mg_socket_if_sock_set (struct mg_connection * nc, sock_t sock)
References DBG, mg_set_close_on_exec(), mg_set_non_blocking_mode(), and mg_connection::sock.
mg_socket_if_tcp_send()
void mg_socket_if_tcp_send (struct mg_connection * nc, const void * buf, size_t len)
References mbuf_append(), and mg_connection::send_mbuf.
mg_socket_if_udp_send()
void mg_socket_if_udp_send (struct mg_connection * nc, const void * buf, size_t len)
References mbuf_append(), and mg_connection::send_mbuf.
mg_status_message()
const char* mg_status_message (int status_code)
Referenced by mg_http_send_error(), and mg_send_response_line_s().
mg_strchr()
const char * mg_strchr (const struct mg_str s, int c)
References mg_str::len, mg_strcmp(), mg_str::p, and WEAK.
Referenced by mg_next_comma_list_entry_n(), and mg_strdup_nul().
mg_strcmp()
int mg_strcmp (const struct mg_str str1, const struct mg_str str2)
References mg_str::len, mg_strncmp(), mg_str::p, and WEAK.
Referenced by mg_strchr(), and mg_strncmp().
mg_strdup()
struct mg_str mg_strdup (const struct mg_str s)
References mg_strdup_common().
Referenced by mg_assemble_uri(), and mg_register_http_endpoint_opt().
mg_strdup_common()
static struct mg_str mg_strdup_common (const struct mg_str s, int nul_terminate) [static]
References mg_str::len, MG_MALLOC, and mg_str::p.
Referenced by mg_strdup(), and mg_strdup_nul().
mg_strdup_nul()
struct mg_str mg_strdup_nul (const struct mg_str s)
References mg_strchr(), mg_strdup_common(), and WEAK.
mg_strncmp()
int mg_strncmp (const struct mg_str str1, const struct mg_str str2, size_t n)
References mg_str::len, mg_strcmp(), mg_strstr(), and WEAK.
Referenced by mg_bind_opt(), mg_parse_http_basic_auth(), and mg_strcmp().
mg_strstr()
const char * mg_strstr (const struct mg_str haystack, const struct mg_str needle)
References mg_str::len, and mg_str::p.
Referenced by mg_strncmp().
mg_time()
double mg_time (void)
References cs_time().
Referenced by mg_conn_addr_to_str(), mg_create_connection_base(), mg_http_send_error(), mg_mqtt_prepend_header(), mg_parse_http_basic_auth(), mg_recv_common(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_send(), mg_socket_if_poll(), mg_tun_reconnect(), mg_tun_send_frame(), mqtt_handler(), and resolve_cb().
mg_tun_bind_opt()
struct mg_connection * mg_tun_bind_opt (struct mg_mgr * mgr, const char * dispatcher, MG_CB(mg_event_handler_t handler, void *user_data) , struct mg_bind_opts opts)
References MG_CB, mg_tun_create_client(), and mg_tun_do_bind().
Referenced by mg_bind_opt().
mg_tun_client_handler()
static void mg_tun_client_handler (struct mg_connection * nc, int ev, void *ev_data MG_UD_ARGvoid *user_data) [static]
References mg_tun_frame::body, websocket_message::data, mg_tun_client::disp, mg_tun_frame::flags, mg_connection::flags, mg_str::len, LL_DEBUG, LL_ERROR, LL_INFO, LOG, mg_close_conn(), MG_EV_CLOSE, MG_EV_CONNECT, MG_EV_HTTP_REPLY, MG_EV_WEBSOCKET_FRAME, MG_EV_WEBSOCKET_HANDSHAKE_DONE, MG_F_CLOSE_IMMEDIATELY, mg_if_recv_tcp_cb(), mg_tun_close_all(), MG_TUN_F_END_STREAM, mg_tun_if_find_conn(), mg_tun_log_frame(), mg_tun_parse_frame(), mg_tun_reconnect(), MG_TUN_RECONNECT_INTERVAL, mg_str::p, http_message::resp_code, websocket_message::size, mg_tun_frame::stream_id, and mg_connection::user_data.
Referenced by mg_tun_do_reconnect().
mg_tun_close_all()
static void mg_tun_close_all (struct mg_tun_client * client) [static]
References mg_mgr::active_connections, mg_connection::flags, mg_tun_client::iface, mg_connection::iface, LL_DEBUG, LOG, MG_F_CLOSE_IMMEDIATELY, MG_F_LISTENING, mg_tun_client::mgr, and mg_connection::next.
Referenced by mg_tun_client_handler().
mg_tun_create_client()
static struct mg_tun_client* mg_tun_create_client (struct mg_mgr * mgr, const char * dispatcher, struct mg_tun_ssl_opts ssl) [static]
References mg_iface::data, LL_ERROR, LOG, mg_find_iface(), MG_MALLOC, mg_tun_init_client(), and mg_tun_reconnect().
Referenced by mg_tun_bind_opt().
mg_tun_destroy_client()
void mg_tun_destroy_client (struct mg_tun_client * client)
References mg_iface::data, mg_tun_client::disp, mg_connection::flags, mg_tun_client::iface, MG_F_CLOSE_IMMEDIATELY, MG_FREE, mg_tun_client::reconnect, and mg_connection::user_data.
Referenced by mg_tun_if_destroy_conn().
mg_tun_do_bind()
static struct mg_connection* mg_tun_do_bind (struct mg_tun_client * client, MG_CB(mg_event_handler_t handler, void *user_data) , struct mg_bind_opts opts) [static]
References mg_tun_client::iface, mg_bind_opts::iface, mg_tun_client::listener, mg_bind_opt(), MG_CB, and mg_tun_client::mgr.
Referenced by mg_tun_bind_opt().
mg_tun_do_reconnect()
static void mg_tun_do_reconnect (struct mg_tun_client * client) [static]
References mg_tun_client::disp, mg_tun_client::disp_url, LL_ERROR, LOG, MG_CB, mg_connect_ws_opt(), mg_tun_client_handler(), MG_TUN_PROTO_NAME, mg_tun_client::mgr, mg_tun_client::ssl, and mg_connection::user_data.
Referenced by mg_tun_reconnect_ev_handler().
mg_tun_if_add_conn()
void mg_tun_if_add_conn (struct mg_connection * nc)
References mg_connection::sock.
mg_tun_if_connect_tcp()
void mg_tun_if_connect_tcp (struct mg_connection * nc, const union socket_address * sa)
mg_tun_if_connect_udp()
void mg_tun_if_connect_udp (struct mg_connection * nc)
mg_tun_if_create_conn()
int mg_tun_if_create_conn (struct mg_connection * nc)
mg_tun_if_destroy_conn()
void mg_tun_if_destroy_conn (struct mg_connection * nc)
References mg_iface::data, mg_tun_client::disp, mg_connection::flags, mg_connection::iface, LL_DEBUG, LOG, MG_F_LISTENING, MG_TUN_DATA_FRAME, mg_tun_destroy_client(), MG_TUN_F_END_STREAM, mg_tun_send_frame(), and mg_connection::mgr_data.
mg_tun_if_find_conn()
struct mg_connection * mg_tun_if_find_conn (struct mg_tun_client * client, uint32_t stream_id)
References mg_mgr::active_connections, mg_connection::flags, mg_tun_client::iface, mg_connection::iface, mg_tun_client::last_stream_id, mg_tun_client::listener, LL_DEBUG, LOG, MG_F_LISTENING, mg_if_accept_new_conn(), mg_tun_client::mgr, mg_connection::mgr_data, and mg_connection::next.
Referenced by mg_tun_client_handler().
mg_tun_if_free()
void mg_tun_if_free (struct mg_iface * iface)
mg_tun_if_get_conn_addr()
void mg_tun_if_get_conn_addr (struct mg_connection * nc, int remote, union socket_address * sa)
mg_tun_if_init()
void mg_tun_if_init (struct mg_iface * iface)
mg_tun_if_listen_tcp()
int mg_tun_if_listen_tcp (struct mg_connection * nc, union socket_address * sa)
mg_tun_if_listen_udp()
int mg_tun_if_listen_udp (struct mg_connection * nc, union socket_address * sa)
mg_tun_if_poll()
time_t mg_tun_if_poll (struct mg_iface * iface, int timeout_ms)
References cs_time().
mg_tun_if_recved()
void mg_tun_if_recved (struct mg_connection * nc, size_t len)
mg_tun_if_remove_conn()
void mg_tun_if_remove_conn (struct mg_connection * nc)
mg_tun_if_sock_set()
void mg_tun_if_sock_set (struct mg_connection * nc, sock_t sock)
mg_tun_if_tcp_send()
void mg_tun_if_tcp_send (struct mg_connection * nc, const void * buf, size_t len)
References mg_iface::data, mg_connection::iface, LL_DEBUG, LOG, MG_TUN_DATA_FRAME, mg_tun_send_frame(), and mg_connection::mgr_data.
mg_tun_if_udp_send()
void mg_tun_if_udp_send (struct mg_connection * nc, const void * buf, size_t len)
mg_tun_init_client()
static void mg_tun_init_client (struct mg_tun_client * client, struct mg_mgr * mgr, struct mg_iface * iface, const char * dispatcher, struct mg_tun_ssl_opts ssl) [static]
References mg_tun_client::disp, mg_tun_client::disp_url, mg_tun_client::iface, mg_tun_client::last_stream_id, mg_tun_client::listener, mg_tun_client::mgr, mg_tun_client::reconnect, and mg_tun_client::ssl.
Referenced by mg_tun_create_client().
mg_tun_log_frame()
void mg_tun_log_frame (struct mg_tun_frame * frame)
References mg_tun_frame::body, mg_tun_frame::flags, mg_str::len, LL_DEBUG, LOG, mg_str::p, mg_tun_frame::stream_id, and mg_tun_frame::type.
Referenced by mg_tun_client_handler().
mg_tun_parse_frame()
int mg_tun_parse_frame (void * data, size_t len, struct mg_tun_frame * frame)
References mg_tun_frame::body, mg_tun_frame::flags, mg_str::len, mg_str::p, mg_tun_frame::stream_id, and mg_tun_frame::type.
Referenced by mg_tun_client_handler().
mg_tun_reconnect()
static void mg_tun_reconnect (struct mg_tun_client * client, int timeout) [static]
References mg_connection::ev_timer_time, mg_add_sock(), MG_CB, mg_time(), mg_tun_reconnect_ev_handler(), mg_tun_client::mgr, mg_tun_client::reconnect, and mg_connection::user_data.
Referenced by mg_set_nameserver(), mg_tun_client_handler(), mg_tun_create_client(), and mg_tun_reconnect_ev_handler().
mg_tun_reconnect_ev_handler()
void mg_tun_reconnect_ev_handler (struct mg_connection * nc, int ev, void *ev_data MG_UD_ARGvoid *user_data)
References mg_connection::flags, mg_tun_client::listener, MG_EV_TIMER, MG_F_TUN_DO_NOT_RECONNECT, mg_tun_do_reconnect(), mg_tun_reconnect(), and mg_connection::user_data.
Referenced by mg_tun_reconnect().
mg_tun_send_frame()
void mg_tun_send_frame (struct mg_connection * ws, uint32_t stream_id, uint8_t type, uint8_t flags, struct mg_str msg)
References mbuf::buf, DBG, mg_connection::flags, mg_connection::handler, mg_str::len, mbuf::len, LL_ERROR, LOG, mbuf_remove(), mg_asprintf(), mg_call(), MG_CALLOC, MG_CB, mg_connect(), MG_EV_CLOSE, MG_EV_CONNECT, MG_EV_RECV, MG_EV_TIMER, MG_F_CLOSE_IMMEDIATELY, MG_F_SEND_AND_CLOSE, MG_F_UDP, MG_FREE, MG_INTERNAL, MG_MALLOC, MG_REALLOC, mg_send(), mg_send_websocket_framev(), mg_set_timer(), mg_time(), MG_UD_ARG, mg_connection::mgr, mg_str::p, mg_connection::proto_handler, mg_connection::recv_mbuf, mg_connection::user_data, and WEBSOCKET_OP_BINARY.
Referenced by mg_tun_if_destroy_conn(), and mg_tun_if_tcp_send().
mg_url_decode()
int mg_url_decode (const char * src, int src_len, char * dst, int dst_len, int is_form_url_encoded)
References HEXTOI.
Referenced by mg_get_http_var(), and mg_parse_http_basic_auth().
mg_url_encode()
struct mg_str mg_url_encode (const struct mg_str src)
References mbuf::buf, mbuf::len, mbuf_append(), mbuf_init(), mbuf_trim(), and mg_mk_str_n().
Referenced by mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_vcasecmp()
int mg_vcasecmp (const struct mg_str * str1, const char * str2)
References mg_str::len, mg_ncasecmp(), and mg_str::p.
Referenced by mg_http_conn_destructor(), mg_http_handler(), mg_http_send_error(), mg_parse_http(), mg_parse_http_basic_auth(), and mg_vcmp().
mg_vcmp()
int mg_vcmp (const struct mg_str * str1, const char * str2)
References mg_str::len, mg_vcasecmp(), mg_str::p, and WEAK.
Referenced by mg_connect_http_base(), mg_http_send_error(), mg_mk_str_n(), mg_normalize_uri_path(), mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_vprintf()
int mg_vprintf (struct mg_connection * nc, const char * fmt, va_list ap)
References mg_avprintf(), MG_FREE, mg_send(), and MG_VPRINTF_BUFFER_SIZE.
Referenced by mg_printf().
mg_write_to_socket()
static void mg_write_to_socket (struct mg_connection * nc) [static]
References mbuf::buf, DBG, mg_connection::flags, mbuf::len, MG_F_CLOSE_IMMEDIATELY, MG_F_SSL, MG_F_SSL_HANDSHAKE_DONE, MG_F_UDP, MG_F_WANT_READ, MG_F_WANT_WRITE, mg_get_errno(), mg_if_sent_cb(), MG_SEND_FUNC, socket_address::sa, mg_connection::sa, mg_connection::send_mbuf, socket_address::sin, and mg_connection::sock.
Referenced by mg_mgr_handle_conn().
mg_ws_get_proto_data()
static struct mg_ws_proto_data* mg_ws_get_proto_data (struct mg_connection * nc) [static]
References mg_http_get_proto_data(), and mg_http_proto_data::ws_data.
Referenced by mg_deliver_websocket_data().
mg_ws_handler()
MG_INTERNAL void mg_ws_handler (struct mg_connection * nc, int ev, void *ev_data MG_UD_ARGvoid *user_data)
References mg_connection::flags, mg_connection::handler, mg_connection::last_io_time, mg_call(), mg_deliver_websocket_data(), MG_EV_POLL, MG_EV_RECV, MG_F_IS_WEBSOCKET, mg_send_websocket_frame(), MG_WEBSOCKET_PING_INTERVAL_SECONDS, mg_connection::user_data, and WEBSOCKET_OP_PING.
Referenced by mg_http_handler().
mg_ws_handshake()
MG_INTERNAL void mg_ws_handshake (struct mg_connection * nc, const struct mg_str * key, struct http_message * hm)
References DBG, mg_str::len, mg_base64_encode(), mg_get_http_header(), mg_hash_sha1_v(), mg_printf(), and mg_str::p.
Referenced by mg_http_handler().
mg_ws_mask_frame()
static void mg_ws_mask_frame (struct mbuf * mbuf, struct ws_mask_ctx * ctx) [static]
References mbuf::buf, mbuf::len, ws_mask_ctx::mask, and ws_mask_ctx::pos.
Referenced by mg_send_websocket_frame(), and mg_send_websocket_framev().
mg_ws_random_mask()
static uint32_t mg_ws_random_mask (void) [static]
Referenced by mg_send_websocket_handshake3v(), and mg_send_ws_header().
mqtt_handler()
static void mqtt_handler (struct mg_connection * nc, int ev, void *ev_data MG_UD_ARGvoid *user_data) [static]
References mg_mqtt_message::cmd, mg_connection::flags, mg_connection::handler, mg_mqtt_proto_data::keep_alive, mg_mqtt_proto_data::last_control_time, LL_DEBUG, LOG, mbuf_remove(), MG_EV_ACCEPT, MG_EV_POLL, MG_EV_RECV, MG_F_CLOSE_IMMEDIATELY, MG_MQTT_EVENT_BASE, mg_mqtt_ping(), mg_set_protocol_mqtt(), mg_time(), MG_UD_ARG, parse_mqtt(), mg_connection::proto_data, and mg_connection::recv_mbuf.
Referenced by mg_set_protocol_mqtt().
parse_mqtt()
MG_INTERNAL int parse_mqtt (struct mbuf * io, struct mg_mqtt_message * mm)
References mbuf::buf, mg_mqtt_message::client_id, mg_mqtt_message::cmd, mg_mqtt_message::connack_ret_code, mg_mqtt_message::connect_flags, getu16(), mg_mqtt_message::keep_alive_timer, mg_str::len, mbuf::len, mg_mqtt_message::len, LL_DEBUG, LOG, mg_mqtt_message::message_id, MG_MQTT_CMD_CONNACK, MG_MQTT_CMD_CONNECT, MG_MQTT_CMD_PUBACK, MG_MQTT_CMD_PUBCOMP, MG_MQTT_CMD_PUBLISH, MG_MQTT_CMD_PUBREC, MG_MQTT_CMD_PUBREL, MG_MQTT_CMD_SUBACK, MG_MQTT_CMD_SUBSCRIBE, MG_MQTT_GET_QOS, MG_MQTT_HAS_PASSWORD, MG_MQTT_HAS_USER_NAME, MG_MQTT_HAS_WILL, mg_str::p, mg_mqtt_message::password, mg_mqtt_message::payload, mg_mqtt_message::protocol_name, mg_mqtt_message::protocol_version, mg_mqtt_message::qos, scanto(), mg_mqtt_message::topic, mg_mqtt_message::user_name, mg_mqtt_message::will_message, and mg_mqtt_message::will_topic.
Referenced by mqtt_handler().
parse_net()
static int parse_net (const char * spec, uint32_t * net, uint32_t * mask) [static]
References isbyte().
Referenced by mg_check_ip_acl().
parse_uri_component()
static void parse_uri_component (const char ** p, const char * end, const char * seps, struct mg_str * res) [static]
References mg_str::len, and mg_str::p.
Referenced by mg_normalize_uri_path(), mg_parse_http_basic_auth(), and mg_parse_uri().
recv_avail_size()
MG_INTERNAL size_t recv_avail_size (struct mg_connection * conn, size_t max)
References mbuf::len, mg_connection::recv_mbuf, and mg_connection::recv_mbuf_limit.
Referenced by mg_handle_tcp_read().
resolve_cb()
static void resolve_cb (struct mg_dns_message * msg, void * data, enum mg_resolve_err e) [static]
References mg_dns_message::answers, mg_connection::flags, mg_call(), mg_destroy_conn(), MG_DNS_A_RECORD, mg_dns_parse_record_data(), mg_do_connect(), MG_EV_CLOSE, MG_EV_CONNECT, MG_EV_TIMER, MG_F_RESOLVING, MG_F_UDP, MG_RESOLVE_TIMEOUT, mg_time(), mg_dns_message::num_answers, mg_dns_resource_record::rtype, mg_connection::sa, socket_address::sin, and mg_connection::user_data.
Referenced by mg_connect_opt().
scanto()
static const char* scanto (const char * p, struct mg_str * s) [static]
References getu16(), mg_str::len, and mg_str::p.
Referenced by parse_mqtt().
str_util_lowercase()
static int str_util_lowercase (const char * s) [static]
References mg_ncasecmp(), and WEAK.
Referenced by mg_match_prefix_n(), and mg_ncasecmp().
Variable Documentation
cs_log_threshold
enum cs_log_level cs_log_threshold
mg_default_iface_vtable
const struct mg_iface_vtable mg_default_iface_vtable = MG_SOCKET_IFACE_VTABLE
mg_dns_tid
int mg_dns_tid = 0xa0 [static]
Referenced by mg_send_dns_query().
mg_ifaces
const struct mg_iface_vtable* mg_ifaces[]
Initial value:
= {
    &mg_default_iface_vtable,
    &mg_tun_iface_vtable,
}
Referenced by mg_mgr_init_opt().
mg_num_ifaces
int mg_num_ifaces = (int) (sizeof(mg_ifaces) / sizeof(mg_ifaces[0]))
Referenced by mg_mgr_init_opt().
mg_pic32_iface_vtable
const struct mg_iface_vtable mg_pic32_iface_vtable
mg_simplelink_iface_vtable
const struct mg_iface_vtable mg_simplelink_iface_vtable
mg_socket_iface_vtable
const struct mg_iface_vtable mg_socket_iface_vtable = MG_SOCKET_IFACE_VTABLE
mg_tun_iface_vtable
const struct mg_iface_vtable mg_tun_iface_vtable = MG_TUN_IFACE_VTABLE
mg_version_header
const char* mg_version_header = `Mongoose/` MG_VERSION [static]
s_filter_pattern
char* s_filter_pattern = NULL [static]
s_filter_pattern_len
size_t s_filter_pattern_len [static]
test_calloc
void*(* test_calloc) (size_t count, size_t size)
test_malloc
void*(* test_malloc) (size_t size)
WEAK
enum cs_log_level cs_log_threshold WEAK
Initial value:
=
    LL_ERROR
Referenced by c_itoa(), c_snprintf(), c_strnstr(), c_vsnprintf(), cs_from_hex(), cs_hmac_sha1(), fourbit(), mbuf_append(), mbuf_free(), mbuf_init(), mbuf_insert(), mbuf_remove(), mbuf_resize(), mbuf_trim(), mg_asprintf(), mg_casecmp(), mg_mk_str_n(), mg_ncasecmp(), mg_strchr(), mg_strcmp(), mg_strdup_nul(), mg_strncmp(), mg_vcmp(), and str_util_lowercase().