mongoose.h File Reference
#include <time.h>
#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
Classes
struct cs_md5_ctx
struct cs_sha1_ctx
struct mg_str
struct mbuf
struct cs_base64_ctx
struct mg_iface
struct mg_iface_vtable
union socket_address
struct mg_mgr
struct mg_connection
struct mg_mgr_init_opts
struct mg_add_sock_opts
struct mg_bind_opts
struct mg_connect_opts
struct http_message
struct websocket_message
struct mg_http_multipart_part
struct mg_ssi_call_ctx
struct mg_http_endpoint_opts
struct mg_mqtt_message
struct mg_mqtt_topic_expression
struct mg_send_mqtt_handshake_opts
struct mg_mqtt_proto_data
struct mg_dns_resource_record
struct mg_dns_message
struct mg_resolve_async_opts
Macros
#define CS_MONGOOSE_SRC_COMMON_H_
#define MG_VERSION `6.10`
#define CS_COMMON_PLATFORM_H_
#define CS_P_CUSTOM 0
#define CS_P_UNIX 1
#define CS_P_WINDOWS 2
#define CS_P_ESP32 15
#define CS_P_ESP8266 3
#define CS_P_CC3100 6
#define CS_P_CC3200 4
#define CS_P_CC3220 17
#define CS_P_MSP432 5
#define CS_P_TM4C129 14
#define CS_P_MBED 7
#define CS_P_WINCE 8
#define CS_P_NXP_LPC 13
#define CS_P_NXP_KINETIS 9
#define CS_P_NRF51 12
#define CS_P_NRF52 10
#define CS_P_PIC32 11
#define CS_P_STM32 16
#define MG_NET_IF_SOCKET 1
#define MG_NET_IF_SIMPLELINK 2
#define MG_NET_IF_LWIP_LOW_LEVEL 3
#define MG_NET_IF_PIC32 4
#define MG_SSL_IF_OPENSSL 1
#define MG_SSL_IF_MBEDTLS 2
#define MG_SSL_IF_SIMPLELINK 3
#define WEAK
#define NORETURN
#define NOINLINE
#define WARN_UNUSED_RESULT
#define NOINSTR
#define DO_NOT_WARN_UNUSED
#define ARRAY_SIZE(array) (sizeof(array) / sizeof(array[0]))
#define CS_COMMON_PLATFORMS_PLATFORM_WINDOWS_H_
#define CS_COMMON_PLATFORMS_PLATFORM_UNIX_H_
#define CS_COMMON_PLATFORMS_PLATFORM_ESP32_H_
#define CS_COMMON_PLATFORMS_PLATFORM_ESP8266_H_
#define CS_COMMON_PLATFORMS_PLATFORM_CC3100_H_
#define CS_COMMON_PLATFORMS_PLATFORM_CC3200_H_
#define CS_COMMON_PLATFORMS_PLATFORM_MSP432_H_
#define CS_COMMON_PLATFORMS_PLATFORM_TM4C129_H_
#define CS_COMMON_PLATFORMS_PLATFORM_MBED_H_
#define CS_COMMON_PLATFORMS_PLATFORM_NRF51_H_
#define CS_COMMON_PLATFORMS_PLATFORM_NRF52_H_
#define CS_COMMON_PLATFORMS_SIMPLELINK_CS_SIMPLELINK_H_
#define CS_COMMON_PLATFORMS_PLATFORM_WINCE_H_
#define CS_COMMON_PLATFORMS_PLATFORM_NXP_LPC_H_
#define CS_COMMON_PLATFORMS_PLATFORM_NXP_KINETIS_H_
#define CS_COMMON_PLATFORMS_PLATFORM_PIC32_H_
#define CS_COMMON_PLATFORMS_PLATFORM_STM32_H_
#define CS_COMMON_PLATFORMS_LWIP_MG_LWIP_H_
#define MG_LWIP 0
#define CS_COMMON_MD5_H_
#define CS_DISABLE_MD5 0
#define CS_COMMON_SHA1_H_
#define CS_DISABLE_SHA1 0
#define CS_COMMON_CS_TIME_H_
#define CS_COMMON_MG_STR_H_
#define MG_MK_STR(str_literal) { str_literal, sizeof(str_literal) - 1 }
#define MG_NULL_STR { NULL, 0 }
#define CS_COMMON_MBUF_H_
#define MBUF_SIZE_MULTIPLIER 1.5
#define CS_COMMON_BASE64_H_
#define DISABLE_BASE64 0
#define CS_COMMON_STR_UTIL_H_
#define CS_ENABLE_STRDUP 0
#define CS_ENABLE_TO64 0
#define CS_STRINGIFY_LIT(x) #x
#define CS_STRINGIFY_MACRO(x) CS_STRINGIFY_LIT(x)
#define _SYS_QUEUE_H_
#define QMD_TRACE_ELEM(elem)
#define QMD_TRACE_HEAD(head)
#define QMD_SAVELINK(name, link)
#define TRACEBUF
#define TRACEBUF_INITIALIZER
#define TRASHIT(x)
#define QUEUE_TYPEOF(type) struct type
#define SLIST_HEAD(name, type)
#define SLIST_CLASS_HEAD(name, type)
#define SLIST_HEAD_INITIALIZER(head) { NULL }
#define SLIST_ENTRY(type)
#define SLIST_CLASS_ENTRY(type)
#define SLIST_EMPTY(head) ((head)->slh_first == NULL)
#define SLIST_FIRST(head) ((head)->slh_first)
#define SLIST_FOREACH(var, head, field)
#define SLIST_FOREACH_FROM(var, head, field)
#define SLIST_FOREACH_SAFE(var, head, field, tvar)
#define SLIST_FOREACH_FROM_SAFE(var, head, field, tvar)
#define SLIST_FOREACH_PREVPTR(var, varp, head, field)
#define SLIST_INIT(head)
#define SLIST_INSERT_AFTER(slistelm, elm, field)
#define SLIST_INSERT_HEAD(head, elm, field)
#define SLIST_NEXT(elm, field) ((elm)->field.sle_next)
#define SLIST_REMOVE(head, elm, type, field)
#define SLIST_REMOVE_AFTER(elm, field)
#define SLIST_REMOVE_HEAD(head, field)
#define SLIST_SWAP(head1, head2, type)
#define STAILQ_HEAD(name, type)
#define STAILQ_CLASS_HEAD(name, type)
#define STAILQ_HEAD_INITIALIZER(head) { NULL, &(head).stqh_first }
#define STAILQ_ENTRY(type)
#define STAILQ_CLASS_ENTRY(type)
#define STAILQ_CONCAT(head1, head2)
#define STAILQ_EMPTY(head) ((head)->stqh_first == NULL)
#define STAILQ_FIRST(head) ((head)->stqh_first)
#define STAILQ_FOREACH(var, head, field)
#define STAILQ_FOREACH_FROM(var, head, field)
#define STAILQ_FOREACH_SAFE(var, head, field, tvar)
#define STAILQ_FOREACH_FROM_SAFE(var, head, field, tvar)
#define STAILQ_INIT(head)
#define STAILQ_INSERT_AFTER(head, tqelm, elm, field)
#define STAILQ_INSERT_HEAD(head, elm, field)
#define STAILQ_INSERT_TAIL(head, elm, field)
#define STAILQ_LAST(head, type, field)
#define STAILQ_NEXT(elm, field) ((elm)->field.stqe_next)
#define STAILQ_REMOVE(head, elm, type, field)
#define STAILQ_REMOVE_AFTER(head, elm, field)
#define STAILQ_REMOVE_HEAD(head, field)
#define STAILQ_SWAP(head1, head2, type)
#define LIST_HEAD(name, type)
#define LIST_CLASS_HEAD(name, type)
#define LIST_HEAD_INITIALIZER(head) { NULL }
#define LIST_ENTRY(type)
#define LIST_CLASS_ENTRY(type)
#define QMD_LIST_CHECK_HEAD(head, field)
#define QMD_LIST_CHECK_NEXT(elm, field)
#define QMD_LIST_CHECK_PREV(elm, field)
#define LIST_EMPTY(head) ((head)->lh_first == NULL)
#define LIST_FIRST(head) ((head)->lh_first)
#define LIST_FOREACH(var, head, field)
#define LIST_FOREACH_FROM(var, head, field)
#define LIST_FOREACH_SAFE(var, head, field, tvar)
#define LIST_FOREACH_FROM_SAFE(var, head, field, tvar)
#define LIST_INIT(head)
#define LIST_INSERT_AFTER(listelm, elm, field)
#define LIST_INSERT_BEFORE(listelm, elm, field)
#define LIST_INSERT_HEAD(head, elm, field)
#define LIST_NEXT(elm, field) ((elm)->field.le_next)
#define LIST_PREV(elm, head, type, field)
#define LIST_REMOVE(elm, field)
#define LIST_SWAP(head1, head2, type, field)
#define TAILQ_HEAD(name, type)
#define TAILQ_CLASS_HEAD(name, type)
#define TAILQ_HEAD_INITIALIZER(head) { NULL, &(head).tqh_first, TRACEBUF_INITIALIZER }
#define TAILQ_ENTRY(type)
#define TAILQ_CLASS_ENTRY(type)
#define QMD_TAILQ_CHECK_HEAD(head, field)
#define QMD_TAILQ_CHECK_TAIL(head, headname)
#define QMD_TAILQ_CHECK_NEXT(elm, field)
#define QMD_TAILQ_CHECK_PREV(elm, field)
#define TAILQ_CONCAT(head1, head2, field)
#define TAILQ_EMPTY(head) ((head)->tqh_first == NULL)
#define TAILQ_FIRST(head) ((head)->tqh_first)
#define TAILQ_FOREACH(var, head, field)
#define TAILQ_FOREACH_FROM(var, head, field)
#define TAILQ_FOREACH_SAFE(var, head, field, tvar)
#define TAILQ_FOREACH_FROM_SAFE(var, head, field, tvar)
#define TAILQ_FOREACH_REVERSE(var, head, headname, field)
#define TAILQ_FOREACH_REVERSE_FROM(var, head, headname, field)
#define TAILQ_FOREACH_REVERSE_SAFE(var, head, headname, field, tvar)
#define TAILQ_FOREACH_REVERSE_FROM_SAFE(var, head, headname, field, tvar)
#define TAILQ_INIT(head)
#define TAILQ_INSERT_AFTER(head, listelm, elm, field)
#define TAILQ_INSERT_BEFORE(listelm, elm, field)
#define TAILQ_INSERT_HEAD(head, elm, field)
#define TAILQ_INSERT_TAIL(head, elm, field)
#define TAILQ_LAST(head, headname) (*(((struct headname *)((head)->tqh_last))->tqh_last))
#define TAILQ_NEXT(elm, field) ((elm)->field.tqe_next)
#define TAILQ_PREV(elm, headname, field) (*(((struct headname *)((elm)->field.tqe_prev))->tqh_last))
#define TAILQ_REMOVE(head, elm, field)
#define TAILQ_SWAP(head1, head2, type, field)
#define CS_MONGOOSE_SRC_FEATURES_H_
#define MG_DISABLE_HTTP_DIGEST_AUTH 0
#define MG_DISABLE_HTTP_KEEP_ALIVE 0
#define MG_DISABLE_PFS 0
#define MG_DISABLE_WS_RANDOM_MASK 0
#define MG_ENABLE_ASYNC_RESOLVER 1
#define MG_ENABLE_BROADCAST 0
#define MG_ENABLE_COAP 0
#define MG_ENABLE_DEBUG 0
#define MG_ENABLE_DIRECTORY_LISTING 0
#define MG_ENABLE_DNS 1
#define MG_ENABLE_DNS_SERVER 0
#define MG_ENABLE_FAKE_DAVLOCK 0
#define MG_ENABLE_FILESYSTEM 0
#define MG_ENABLE_GETADDRINFO 0
#define MG_ENABLE_HEXDUMP CS_ENABLE_STDIO
#define MG_ENABLE_HTTP 1
#define MG_ENABLE_HTTP_CGI 0
#define MG_ENABLE_HTTP_SSI MG_ENABLE_FILESYSTEM
#define MG_ENABLE_HTTP_SSI_EXEC 0
#define MG_ENABLE_HTTP_STREAMING_MULTIPART 0
#define MG_ENABLE_HTTP_WEBDAV 0
#define MG_ENABLE_HTTP_WEBSOCKET MG_ENABLE_HTTP
#define MG_ENABLE_IPV6 0
#define MG_ENABLE_MQTT 1
#define MG_ENABLE_SOCKS 0
#define MG_ENABLE_MQTT_BROKER 0
#define MG_ENABLE_SSL 0
#define MG_ENABLE_SYNC_RESOLVER 0
#define MG_ENABLE_STDIO CS_ENABLE_STDIO
#define MG_NET_IF MG_NET_IF_SOCKET
#define MG_SSL_IF MG_SSL_IF_OPENSSL
#define MG_ENABLE_THREADS 0
#define MG_ENABLE_HTTP_URL_REWRITES (CS_PLATFORM == CS_P_WINDOWS || CS_PLATFORM == CS_P_UNIX)
#define MG_ENABLE_TUN MG_ENABLE_HTTP_WEBSOCKET
#define MG_ENABLE_SNTP 0
#define MG_ENABLE_EXTRA_ERRORS_DESC 0
#define MG_ENABLE_CALLBACK_USERDATA 0
#define MG_UD_ARG(ud)
#define MG_CB(cb, ud) cb
#define CS_MONGOOSE_SRC_NET_IF_H_
#define MG_MAIN_IFACE 0
#define CS_MONGOOSE_SRC_SSL_IF_H_
#define CS_MONGOOSE_SRC_NET_H_
#define MG_VPRINTF_BUFFER_SIZE 100
#define MG_RECV_FUNC(s, b, l, f) recv(s, b, l, f)
#define MG_SEND_FUNC(s, b, l, f) send(s, b, l, f)
#define MG_EV_POLL 0 /* Sent to each connection on each mg_mgr_poll() call */
#define MG_EV_ACCEPT 1 /* New connection accepted. union socket_address * */
#define MG_EV_CONNECT 2 /* connect() succeeded or failed. int * */
#define MG_EV_RECV 3 /* Data has been received. int *num_bytes */
#define MG_EV_SEND 4 /* Data has been written to a socket. int *num_bytes */
#define MG_EV_CLOSE 5 /* Connection is closed. NULL */
#define MG_EV_TIMER 6 /* now >= conn->ev_timer_time. double * */
#define MG_F_LISTENING (1 << 0) /* This connection is listening */
#define MG_F_UDP (1 << 1) /* This connection is UDP */
#define MG_F_RESOLVING (1 << 2) /* Waiting for async resolver */
#define MG_F_CONNECTING (1 << 3) /* connect() call in progress */
#define MG_F_SSL (1 << 4) /* SSL is enabled on the connection */
#define MG_F_SSL_HANDSHAKE_DONE (1 << 5) /* SSL hanshake has completed */
#define MG_F_WANT_READ (1 << 6) /* SSL specific */
#define MG_F_WANT_WRITE (1 << 7) /* SSL specific */
#define MG_F_IS_WEBSOCKET (1 << 8) /* Websocket specific */
#define MG_F_SEND_AND_CLOSE (1 << 10) /* Push remaining data and close */
#define MG_F_CLOSE_IMMEDIATELY (1 << 11) /* Disconnect */
#define MG_F_WEBSOCKET_NO_DEFRAG (1 << 12) /* Websocket specific */
#define MG_F_DELETE_CHUNK (1 << 13) /* HTTP specific */
#define MG_F_ENABLE_BROADCAST (1 << 14) /* Allow broadcast address usage */
#define MG_F_TUN_DO_NOT_RECONNECT (1 << 15) /* Don't reconnect tunnel */
#define MG_F_USER_1 (1 << 20) /* Flags left for application */
#define MG_F_USER_2 (1 << 21)
#define MG_F_USER_3 (1 << 22)
#define MG_F_USER_4 (1 << 23)
#define MG_F_USER_5 (1 << 24)
#define MG_F_USER_6 (1 << 25)
#define CS_MONGOOSE_SRC_URI_H_
#define CS_MONGOOSE_SRC_UTIL_H_
#define MG_MAX_PATH 256
#define MG_SOCK_STRINGIFY_IP 1
#define MG_SOCK_STRINGIFY_PORT 2
#define MG_SOCK_STRINGIFY_REMOTE 4
#define CS_MONGOOSE_SRC_HTTP_H_
#define MG_MAX_HTTP_HEADERS 20
#define MG_MAX_HTTP_REQUEST_SIZE 1024
#define MG_MAX_HTTP_SEND_MBUF 1024
#define MG_CGI_ENVIRONMENT_SIZE 8192
#define MG_EV_HTTP_REQUEST 100 /* struct http_message * */
#define MG_EV_HTTP_REPLY 101 /* struct http_message * */
#define MG_EV_HTTP_CHUNK 102 /* struct http_message * */
#define MG_EV_SSI_CALL 105 /* char * */
#define MG_EV_SSI_CALL_CTX 106 /* struct mg_ssi_call_ctx * */
#define MG_EV_WEBSOCKET_HANDSHAKE_REQUEST 111 /* struct http_message * */
#define MG_EV_WEBSOCKET_HANDSHAKE_DONE 112 /* NULL */
#define MG_EV_WEBSOCKET_FRAME 113 /* struct websocket_message * */
#define MG_EV_WEBSOCKET_CONTROL_FRAME 114 /* struct websocket_message * */
#define WEBSOCKET_OP_CONTINUE 0
#define WEBSOCKET_OP_TEXT 1
#define WEBSOCKET_OP_BINARY 2
#define WEBSOCKET_OP_CLOSE 8
#define WEBSOCKET_OP_PING 9
#define WEBSOCKET_OP_PONG 10
#define WEBSOCKET_DONT_FIN 0x100
#define CS_MONGOOSE_SRC_HTTP_SERVER_H_
#define CS_MONGOOSE_SRC_HTTP_CLIENT_H_
#define CS_MONGOOSE_SRC_MQTT_H_
#define MG_MQTT_CMD_CONNECT 1
#define MG_MQTT_CMD_CONNACK 2
#define MG_MQTT_CMD_PUBLISH 3
#define MG_MQTT_CMD_PUBACK 4
#define MG_MQTT_CMD_PUBREC 5
#define MG_MQTT_CMD_PUBREL 6
#define MG_MQTT_CMD_PUBCOMP 7
#define MG_MQTT_CMD_SUBSCRIBE 8
#define MG_MQTT_CMD_SUBACK 9
#define MG_MQTT_CMD_UNSUBSCRIBE 10
#define MG_MQTT_CMD_UNSUBACK 11
#define MG_MQTT_CMD_PINGREQ 12
#define MG_MQTT_CMD_PINGRESP 13
#define MG_MQTT_CMD_DISCONNECT 14
#define MG_MQTT_EVENT_BASE 200
#define MG_EV_MQTT_CONNECT (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_CONNECT)
#define MG_EV_MQTT_CONNACK (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_CONNACK)
#define MG_EV_MQTT_PUBLISH (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBLISH)
#define MG_EV_MQTT_PUBACK (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBACK)
#define MG_EV_MQTT_PUBREC (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBREC)
#define MG_EV_MQTT_PUBREL (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBREL)
#define MG_EV_MQTT_PUBCOMP (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBCOMP)
#define MG_EV_MQTT_SUBSCRIBE (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_SUBSCRIBE)
#define MG_EV_MQTT_SUBACK (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_SUBACK)
#define MG_EV_MQTT_UNSUBSCRIBE (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_UNSUBSCRIBE)
#define MG_EV_MQTT_UNSUBACK (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_UNSUBACK)
#define MG_EV_MQTT_PINGREQ (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PINGREQ)
#define MG_EV_MQTT_PINGRESP (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PINGRESP)
#define MG_EV_MQTT_DISCONNECT (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_DISCONNECT)
#define MG_MQTT_RETAIN 0x1
#define MG_MQTT_DUP 0x4
#define MG_MQTT_QOS(qos) ((qos) << 1)
#define MG_MQTT_GET_QOS(flags) (((flags) &0x6) >> 1)
#define MG_MQTT_SET_QOS(flags, qos) (flags) = ((flags) & ~0x6) | ((qos) << 1)
#define MG_MQTT_CLEAN_SESSION 0x02
#define MG_MQTT_HAS_WILL 0x04
#define MG_MQTT_WILL_RETAIN 0x20
#define MG_MQTT_HAS_PASSWORD 0x40
#define MG_MQTT_HAS_USER_NAME 0x80
#define MG_MQTT_GET_WILL_QOS(flags) (((flags) &0x18) >> 3)
#define MG_MQTT_SET_WILL_QOS(flags, qos) (flags) = ((flags) & ~0x18) | ((qos) << 3)
#define MG_EV_MQTT_CONNACK_ACCEPTED 0
#define MG_EV_MQTT_CONNACK_UNACCEPTABLE_VERSION 1
#define MG_EV_MQTT_CONNACK_IDENTIFIER_REJECTED 2
#define MG_EV_MQTT_CONNACK_SERVER_UNAVAILABLE 3
#define MG_EV_MQTT_CONNACK_BAD_AUTH 4
#define MG_EV_MQTT_CONNACK_NOT_AUTHORIZED 5
#define CS_MONGOOSE_SRC_MQTT_BROKER_H_
#define CS_MONGOOSE_SRC_DNS_H_
#define MG_DNS_A_RECORD 0x01 /* Lookup IP address */
#define MG_DNS_CNAME_RECORD 0x05 /* Lookup CNAME */
#define MG_DNS_PTR_RECORD 0x0c /* Lookup PTR */
#define MG_DNS_TXT_RECORD 0x10 /* Lookup TXT */
#define MG_DNS_AAAA_RECORD 0x1c /* Lookup IPv6 address */
#define MG_DNS_SRV_RECORD 0x21 /* Lookup SRV */
#define MG_DNS_MX_RECORD 0x0f /* Lookup mail server for domain */
#define MG_DNS_ANY_RECORD 0xff
#define MG_DNS_NSEC_RECORD 0x2f
#define MG_MAX_DNS_QUESTIONS 32
#define MG_MAX_DNS_ANSWERS 32
#define MG_DNS_MESSAGE 100 /* High-level DNS message event */
#define CS_MONGOOSE_SRC_DNS_SERVER_H_
#define CS_MONGOOSE_SRC_RESOLV_H_
#define CS_MONGOOSE_SRC_COAP_H_
#define CS_MONGOOSE_SRC_SNTP_H_
#define CS_MONGOOSE_SRC_SOCKS_H_
Typedefs
typedef void(* cs_base64_putc_t) (char, void *)
typedef void(* mg_event_handler_t) (struct mg_connection *nc, int ev, void *ev_data MG_UD_ARG(void *user_data))
typedef void(* mg_resolve_callback_t) (struct mg_dns_message *dns_message, void *user_data, enum mg_resolve_err)
Enumerations
enum mg_dns_resource_record_kind { MG_DNS_INVALID_RECORD = 0,
MG_DNS_QUESTION,
MG_DNS_ANSWER
 }
enum mg_resolve_err { MG_RESOLVE_OK = 0,
MG_RESOLVE_NO_ANSWERS = 1,
MG_RESOLVE_EXCEEDED_RETRY_COUNT = 2,
MG_RESOLVE_TIMEOUT = 3
 }
Functions
void cs_md5_init (cs_md5_ctx *c)
void cs_md5_update (cs_md5_ctx *c, const unsigned char *data, size_t len)
void cs_md5_final (unsigned char *md, cs_md5_ctx *c)
void cs_sha1_init (cs_sha1_ctx *)
void cs_sha1_update (cs_sha1_ctx *, const unsigned char *data, uint32_t len)
void cs_sha1_final (unsigned char digest[20], cs_sha1_ctx *)
void cs_hmac_sha1 (const unsigned char *key, size_t key_len, const unsigned char *text, size_t text_len, unsigned char out[20])
double cs_time (void)
double cs_timegm (const struct tm *tm)
struct mg_str mg_mk_str (const char *s)
struct mg_str mg_mk_str_n (const char *s, size_t len)
int mg_vcmp (const struct mg_str *str2, const char *str1)
int mg_vcasecmp (const struct mg_str *str2, const char *str1)
struct mg_str mg_strdup (const struct mg_str s)
struct mg_str mg_strdup_nul (const struct mg_str s)
const char * mg_strchr (const struct mg_str s, int c)
int mg_strcmp (const struct mg_str str1, const struct mg_str str2)
int mg_strncmp (const struct mg_str str1, const struct mg_str str2, size_t n)
const char * mg_strstr (const struct mg_str haystack, const struct mg_str needle)
void mbuf_init (struct mbuf *, size_t initial_capacity)
void mbuf_free (struct mbuf *)
size_t mbuf_append (struct mbuf *, const void *data, size_t data_size)
size_t mbuf_insert (struct mbuf *, size_t, const void *, size_t)
void mbuf_remove (struct mbuf *, size_t data_size)
void mbuf_resize (struct mbuf *, size_t new_size)
void mbuf_trim (struct mbuf *)
void cs_base64_init (struct cs_base64_ctx *ctx, cs_base64_putc_t putc, void *user_data)
void cs_base64_update (struct cs_base64_ctx *ctx, const char *str, size_t len)
void cs_base64_finish (struct cs_base64_ctx *ctx)
void cs_base64_encode (const unsigned char *src, int src_len, char *dst)
void cs_fprint_base64 (FILE *f, const unsigned char *src, int src_len)
int cs_base64_decode (const unsigned char *s, int len, char *dst, int *dec_len)
size_t c_strnlen (const char *s, size_t maxlen)
int c_snprintf (char *buf, size_t buf_size, const char *format,...)
int c_vsnprintf (char *buf, size_t buf_size, const char *format, va_list ap)
const char * c_strnstr (const char *s, const char *find, size_t slen)
void cs_to_hex (char *to, const unsigned char *p, size_t len)
void cs_from_hex (char *to, const char *p, size_t len)
int mg_ncasecmp (const char *s1, const char *s2, size_t len)
int mg_casecmp (const char *s1, const char *s2)
int mg_asprintf (char **buf, size_t size, const char *fmt,...)
int mg_avprintf (char **buf, size_t size, const char *fmt, va_list ap)
const char * mg_next_comma_list_entry (const char *list, struct mg_str *val, struct mg_str *eq_val)
struct mg_str mg_next_comma_list_entry_n (struct mg_str list, struct mg_str *val, struct mg_str *eq_val)
int mg_match_prefix (const char *pattern, int pattern_len, const char *str)
int mg_match_prefix_n (const struct mg_str pattern, const struct mg_str str)
struct mg_iface * mg_if_create_iface (const struct mg_iface_vtable *vtable, struct mg_mgr *mgr)
struct mg_iface * mg_find_iface (struct mg_mgr *mgr, const struct mg_iface_vtable *vtable, struct mg_iface *from)
struct mg_connection * mg_if_accept_new_conn (struct mg_connection *lc)
void mg_if_accept_tcp_cb (struct mg_connection *nc, union socket_address *sa, size_t sa_len)
void mg_if_connect_cb (struct mg_connection *nc, int err)
void mg_if_sent_cb (struct mg_connection *nc, int num_sent)
void mg_if_recv_tcp_cb (struct mg_connection *nc, void *buf, int len, int own)
void mg_if_recv_udp_cb (struct mg_connection *nc, void *buf, int len, union socket_address *sa, size_t sa_len)
void mg_if_poll (struct mg_connection *nc, time_t now)
void mg_if_timer (struct mg_connection *c, double now)
void mg_mgr_init (struct mg_mgr *mgr, void *user_data)
void mg_mgr_init_opt (struct mg_mgr *mgr, void *user_data, struct mg_mgr_init_opts opts)
void mg_mgr_free (struct mg_mgr *)
time_t mg_mgr_poll (struct mg_mgr *, int milli)
struct mg_connection * mg_next (struct mg_mgr *mgr, struct mg_connection *c)
struct mg_connection * mg_add_sock (struct mg_mgr *mgr, sock_t sock, MG_CB(mg_event_handler_t handler, void *user_data))
struct mg_connection * mg_add_sock_opt (struct mg_mgr *mgr, sock_t sock, MG_CB(mg_event_handler_t handler, void *user_data), struct mg_add_sock_opts opts)
struct mg_connection * mg_bind (struct mg_mgr *mgr, const char *address, MG_CB(mg_event_handler_t handler, void *user_data))
struct mg_connection * mg_bind_opt (struct mg_mgr *mgr, const char *address, MG_CB(mg_event_handler_t handler, void *user_data), struct mg_bind_opts opts)
struct mg_connection * mg_connect (struct mg_mgr *mgr, const char *address, MG_CB(mg_event_handler_t handler, void *user_data))
struct mg_connection * mg_connect_opt (struct mg_mgr *mgr, const char *address, MG_CB(mg_event_handler_t handler, void *user_data), struct mg_connect_opts opts)
void mg_send (struct mg_connection *, const void *buf, int len)
int mg_printf (struct mg_connection *, const char *fmt,...)
int mg_vprintf (struct mg_connection *, const char *fmt, va_list ap)
int mg_socketpair (sock_t[2], int sock_type)
int mg_check_ip_acl (const char *acl, uint32_t remote_ip)
double mg_set_timer (struct mg_connection *c, double timestamp)
double mg_time (void)
int mg_parse_uri (const struct mg_str uri, struct mg_str *scheme, struct mg_str *user_info, struct mg_str *host, unsigned int *port, struct mg_str *path, struct mg_str *query, struct mg_str *fragment)
int mg_assemble_uri (const struct mg_str *scheme, const struct mg_str *user_info, const struct mg_str *host, unsigned int port, const struct mg_str *path, const struct mg_str *query, const struct mg_str *fragment, int normalize_path, struct mg_str *uri)
int mg_normalize_uri_path (const struct mg_str *in, struct mg_str *out)
const char * mg_skip (const char *s, const char *end_string, const char *delimiters, struct mg_str *v)
int mg_base64_decode (const unsigned char *s, int len, char *dst)
void mg_base64_encode (const unsigned char *src, int src_len, char *dst)
void mg_set_close_on_exec (sock_t)
int mg_conn_addr_to_str (struct mg_connection *c, char *buf, size_t len, int flags)
void mg_sock_to_str (sock_t sock, char *buf, size_t len, int flags)
int mg_sock_addr_to_str (const union socket_address *sa, char *buf, size_t len, int flags)
int mg_is_big_endian (void)
void mg_mbuf_append_base64_putc (char ch, void *user_data)
void mg_mbuf_append_base64 (struct mbuf *mbuf, const void *data, size_t len)
void mg_basic_auth_header (const struct mg_str user, const struct mg_str pass, struct mbuf *buf)
struct mg_str mg_url_encode (const struct mg_str src)
void mg_set_protocol_http_websocket (struct mg_connection *nc)
void mg_send_websocket_handshake (struct mg_connection *nc, const char *uri, const char *extra_headers)
void mg_send_websocket_handshake2 (struct mg_connection *nc, const char *path, const char *host, const char *protocol, const char *extra_headers)
void mg_send_websocket_handshake3 (struct mg_connection *nc, const char *path, const char *host, const char *protocol, const char *extra_headers, const char *user, const char *pass)
void mg_send_websocket_handshake3v (struct mg_connection *nc, const struct mg_str path, const struct mg_str host, const struct mg_str protocol, const struct mg_str extra_headers, const struct mg_str user, const struct mg_str pass)
struct mg_connection * mg_connect_ws (struct mg_mgr *mgr, MG_CB(mg_event_handler_t event_handler, void *user_data), const char *url, const char *protocol, const char *extra_headers)
struct mg_connection * mg_connect_ws_opt (struct mg_mgr *mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data), struct mg_connect_opts opts, const char *url, const char *protocol, const char *extra_headers)
void mg_send_websocket_frame (struct mg_connection *nc, int op_and_flags, const void *data, size_t data_len)
void mg_send_websocket_framev (struct mg_connection *nc, int op_and_flags, const struct mg_str *strings, int num_strings)
void mg_printf_websocket_frame (struct mg_connection *nc, int op_and_flags, const char *fmt,...)
int mg_url_decode (const char *src, int src_len, char *dst, int dst_len, int is_form_url_encoded)
void mg_hash_md5_v (size_t num_msgs, const uint8_t *msgs[], const size_t *msg_lens, uint8_t *digest)
void mg_hash_sha1_v (size_t num_msgs, const uint8_t *msgs[], const size_t *msg_lens, uint8_t *digest)
int mg_parse_http (const char *s, int n, struct http_message *hm, int is_req)
struct mg_str * mg_get_http_header (struct http_message *hm, const char *name)
int mg_http_parse_header (struct mg_str *hdr, const char *var_name, char *buf, size_t buf_size)
int mg_get_http_basic_auth (struct http_message *hm, char *user, size_t user_len, char *pass, size_t pass_len)
int mg_parse_http_basic_auth (struct mg_str *hdr, char *user, size_t user_len, char *pass, size_t pass_len)
size_t mg_parse_multipart (const char *buf, size_t buf_len, char *var_name, size_t var_name_len, char *file_name, size_t file_name_len, const char **chunk, size_t *chunk_len)
int mg_get_http_var (const struct mg_str *buf, const char *name, char *dst, size_t dst_len)
void mg_register_http_endpoint (struct mg_connection *nc, const char *uri_path, MG_CB(mg_event_handler_t handler, void *user_data))
void mg_register_http_endpoint_opt (struct mg_connection *nc, const char *uri_path, mg_event_handler_t handler, struct mg_http_endpoint_opts opts)
int mg_http_check_digest_auth (struct http_message *hm, const char *auth_domain, FILE *fp)
int mg_check_digest_auth (struct mg_str method, struct mg_str uri, struct mg_str username, struct mg_str cnonce, struct mg_str response, struct mg_str qop, struct mg_str nc, struct mg_str nonce, struct mg_str auth_domain, FILE *fp)
void mg_send_http_chunk (struct mg_connection *nc, const char *buf, size_t len)
void mg_printf_http_chunk (struct mg_connection *nc, const char *fmt,...)
void mg_send_response_line (struct mg_connection *nc, int status_code, const char *extra_headers)
void mg_http_send_error (struct mg_connection *nc, int code, const char *reason)
void mg_http_send_redirect (struct mg_connection *nc, int status_code, const struct mg_str location, const struct mg_str extra_headers)
void mg_send_head (struct mg_connection *n, int status_code, int64_t content_length, const char *extra_headers)
void mg_printf_html_escape (struct mg_connection *nc, const char *fmt,...)
struct mg_connection * mg_connect_http (struct mg_mgr *mgr, MG_CB(mg_event_handler_t event_handler, void *user_data), const char *url, const char *extra_headers, const char *post_data)
struct mg_connection * mg_connect_http_opt (struct mg_mgr *mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data), struct mg_connect_opts opts, const char *url, const char *extra_headers, const char *post_data)
int mg_http_create_digest_auth_header (char *buf, size_t buf_len, const char *method, const char *uri, const char *auth_domain, const char *user, const char *passwd)
void mg_set_protocol_mqtt (struct mg_connection *nc)
void mg_send_mqtt_handshake (struct mg_connection *nc, const char *client_id)
void mg_send_mqtt_handshake_opt (struct mg_connection *nc, const char *client_id, struct mg_send_mqtt_handshake_opts)
void mg_mqtt_publish (struct mg_connection *nc, const char *topic, uint16_t message_id, int flags, const void *data, size_t len)
void mg_mqtt_subscribe (struct mg_connection *nc, const struct mg_mqtt_topic_expression *topics, size_t topics_len, uint16_t message_id)
void mg_mqtt_unsubscribe (struct mg_connection *nc, char **topics, size_t topics_len, uint16_t message_id)
void mg_mqtt_disconnect (struct mg_connection *nc)
void mg_mqtt_connack (struct mg_connection *nc, uint8_t return_code)
void mg_mqtt_puback (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_pubrec (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_pubrel (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_pubcomp (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_suback (struct mg_connection *nc, uint8_t *qoss, size_t qoss_len, uint16_t message_id)
void mg_mqtt_unsuback (struct mg_connection *nc, uint16_t message_id)
void mg_mqtt_ping (struct mg_connection *nc)
void mg_mqtt_pong (struct mg_connection *nc)
int mg_mqtt_next_subscribe_topic (struct mg_mqtt_message *msg, struct mg_str *topic, uint8_t *qos, int pos)
int mg_mqtt_match_topic_expression (struct mg_str exp, struct mg_str topic)
int mg_mqtt_vmatch_topic_expression (const char *exp, struct mg_str topic)
struct mg_dns_resource_record * mg_dns_next_record (struct mg_dns_message *msg, int query, struct mg_dns_resource_record *prev)
int mg_dns_parse_record_data (struct mg_dns_message *msg, struct mg_dns_resource_record *rr, void *data, size_t data_len)
void mg_send_dns_query (struct mg_connection *nc, const char *name, int query_type)
int mg_dns_insert_header (struct mbuf *io, size_t pos, struct mg_dns_message *msg)
int mg_dns_copy_questions (struct mbuf *io, struct mg_dns_message *msg)
int mg_dns_encode_record (struct mbuf *io, struct mg_dns_resource_record *rr, const char *name, size_t nlen, const void *rdata, size_t rlen)
int mg_dns_encode_name (struct mbuf *io, const char *name, size_t len)
int mg_parse_dns (const char *buf, int len, struct mg_dns_message *msg)
size_t mg_dns_uncompress_name (struct mg_dns_message *msg, struct mg_str *name, char *dst, int dst_len)
void mg_set_protocol_dns (struct mg_connection *nc)
int mg_resolve_async (struct mg_mgr *mgr, const char *name, int query, mg_resolve_callback_t cb, void *data)
void mg_set_nameserver (struct mg_mgr *mgr, const char *nameserver)
int mg_resolve_async_opt (struct mg_mgr *mgr, const char *name, int query, mg_resolve_callback_t cb, void *data, struct mg_resolve_async_opts opts)
int mg_resolve_from_hosts_file (const char *host, union socket_address *usa)
Variables
const struct mg_iface_vtable * mg_ifaces []
int mg_num_ifaces
Macro Definition Documentation
_SYS_QUEUE_H_
#define _SYS_QUEUE_H_
ARRAY_SIZE
#define ARRAY_SIZE(array) (sizeof(array) / sizeof(array[0]))
Referenced by mg_http_parse_headers(), mg_parse_dns(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), and mg_skip().
CS_COMMON_BASE64_H_
#define CS_COMMON_BASE64_H_
CS_COMMON_CS_TIME_H_
#define CS_COMMON_CS_TIME_H_
CS_COMMON_MBUF_H_
#define CS_COMMON_MBUF_H_
CS_COMMON_MD5_H_
#define CS_COMMON_MD5_H_
CS_COMMON_MG_STR_H_
#define CS_COMMON_MG_STR_H_
CS_COMMON_PLATFORM_H_
#define CS_COMMON_PLATFORM_H_
CS_COMMON_PLATFORMS_LWIP_MG_LWIP_H_
#define CS_COMMON_PLATFORMS_LWIP_MG_LWIP_H_
CS_COMMON_PLATFORMS_PLATFORM_CC3100_H_
#define CS_COMMON_PLATFORMS_PLATFORM_CC3100_H_
CS_COMMON_PLATFORMS_PLATFORM_CC3200_H_
#define CS_COMMON_PLATFORMS_PLATFORM_CC3200_H_
CS_COMMON_PLATFORMS_PLATFORM_ESP32_H_
#define CS_COMMON_PLATFORMS_PLATFORM_ESP32_H_
CS_COMMON_PLATFORMS_PLATFORM_ESP8266_H_
#define CS_COMMON_PLATFORMS_PLATFORM_ESP8266_H_
CS_COMMON_PLATFORMS_PLATFORM_MBED_H_
#define CS_COMMON_PLATFORMS_PLATFORM_MBED_H_
CS_COMMON_PLATFORMS_PLATFORM_MSP432_H_
#define CS_COMMON_PLATFORMS_PLATFORM_MSP432_H_
CS_COMMON_PLATFORMS_PLATFORM_NRF51_H_
#define CS_COMMON_PLATFORMS_PLATFORM_NRF51_H_
CS_COMMON_PLATFORMS_PLATFORM_NRF52_H_
#define CS_COMMON_PLATFORMS_PLATFORM_NRF52_H_
CS_COMMON_PLATFORMS_PLATFORM_NXP_KINETIS_H_
#define CS_COMMON_PLATFORMS_PLATFORM_NXP_KINETIS_H_
CS_COMMON_PLATFORMS_PLATFORM_NXP_LPC_H_
#define CS_COMMON_PLATFORMS_PLATFORM_NXP_LPC_H_
CS_COMMON_PLATFORMS_PLATFORM_PIC32_H_
#define CS_COMMON_PLATFORMS_PLATFORM_PIC32_H_
CS_COMMON_PLATFORMS_PLATFORM_STM32_H_
#define CS_COMMON_PLATFORMS_PLATFORM_STM32_H_
CS_COMMON_PLATFORMS_PLATFORM_TM4C129_H_
#define CS_COMMON_PLATFORMS_PLATFORM_TM4C129_H_
CS_COMMON_PLATFORMS_PLATFORM_UNIX_H_
#define CS_COMMON_PLATFORMS_PLATFORM_UNIX_H_
CS_COMMON_PLATFORMS_PLATFORM_WINCE_H_
#define CS_COMMON_PLATFORMS_PLATFORM_WINCE_H_
CS_COMMON_PLATFORMS_PLATFORM_WINDOWS_H_
#define CS_COMMON_PLATFORMS_PLATFORM_WINDOWS_H_
CS_COMMON_PLATFORMS_SIMPLELINK_CS_SIMPLELINK_H_
#define CS_COMMON_PLATFORMS_SIMPLELINK_CS_SIMPLELINK_H_
CS_COMMON_SHA1_H_
#define CS_COMMON_SHA1_H_
CS_COMMON_STR_UTIL_H_
#define CS_COMMON_STR_UTIL_H_
CS_DISABLE_MD5
#define CS_DISABLE_MD5 0
CS_DISABLE_SHA1
#define CS_DISABLE_SHA1 0
CS_ENABLE_STRDUP
#define CS_ENABLE_STRDUP 0
CS_ENABLE_TO64
#define CS_ENABLE_TO64 0
CS_MONGOOSE_SRC_COAP_H_
#define CS_MONGOOSE_SRC_COAP_H_
CS_MONGOOSE_SRC_COMMON_H_
#define CS_MONGOOSE_SRC_COMMON_H_
CS_MONGOOSE_SRC_DNS_H_
#define CS_MONGOOSE_SRC_DNS_H_
CS_MONGOOSE_SRC_DNS_SERVER_H_
#define CS_MONGOOSE_SRC_DNS_SERVER_H_
CS_MONGOOSE_SRC_FEATURES_H_
#define CS_MONGOOSE_SRC_FEATURES_H_
CS_MONGOOSE_SRC_HTTP_CLIENT_H_
#define CS_MONGOOSE_SRC_HTTP_CLIENT_H_
CS_MONGOOSE_SRC_HTTP_H_
#define CS_MONGOOSE_SRC_HTTP_H_
CS_MONGOOSE_SRC_HTTP_SERVER_H_
#define CS_MONGOOSE_SRC_HTTP_SERVER_H_
CS_MONGOOSE_SRC_MQTT_BROKER_H_
#define CS_MONGOOSE_SRC_MQTT_BROKER_H_
CS_MONGOOSE_SRC_MQTT_H_
#define CS_MONGOOSE_SRC_MQTT_H_
CS_MONGOOSE_SRC_NET_H_
#define CS_MONGOOSE_SRC_NET_H_
CS_MONGOOSE_SRC_NET_IF_H_
#define CS_MONGOOSE_SRC_NET_IF_H_
CS_MONGOOSE_SRC_RESOLV_H_
#define CS_MONGOOSE_SRC_RESOLV_H_
CS_MONGOOSE_SRC_SNTP_H_
#define CS_MONGOOSE_SRC_SNTP_H_
CS_MONGOOSE_SRC_SOCKS_H_
#define CS_MONGOOSE_SRC_SOCKS_H_
CS_MONGOOSE_SRC_SSL_IF_H_
#define CS_MONGOOSE_SRC_SSL_IF_H_
CS_MONGOOSE_SRC_URI_H_
#define CS_MONGOOSE_SRC_URI_H_
CS_MONGOOSE_SRC_UTIL_H_
#define CS_MONGOOSE_SRC_UTIL_H_
CS_P_CC3100
#define CS_P_CC3100 6
CS_P_CC3200
#define CS_P_CC3200 4
CS_P_CC3220
#define CS_P_CC3220 17
CS_P_CUSTOM
#define CS_P_CUSTOM 0
CS_P_ESP32
#define CS_P_ESP32 15
CS_P_ESP8266
#define CS_P_ESP8266 3
CS_P_MBED
#define CS_P_MBED 7
CS_P_MSP432
#define CS_P_MSP432 5
CS_P_NRF51
#define CS_P_NRF51 12
CS_P_NRF52
#define CS_P_NRF52 10
CS_P_NXP_KINETIS
#define CS_P_NXP_KINETIS 9
CS_P_NXP_LPC
#define CS_P_NXP_LPC 13
CS_P_PIC32
#define CS_P_PIC32 11
CS_P_STM32
#define CS_P_STM32 16
CS_P_TM4C129
#define CS_P_TM4C129 14
CS_P_UNIX
#define CS_P_UNIX 1
CS_P_WINCE
#define CS_P_WINCE 8
CS_P_WINDOWS
#define CS_P_WINDOWS 2
CS_STRINGIFY_LIT
#define CS_STRINGIFY_LIT(x) #x
CS_STRINGIFY_MACRO
#define CS_STRINGIFY_MACRO(x) CS_STRINGIFY_LIT(x)
DISABLE_BASE64
#define DISABLE_BASE64 0
DO_NOT_WARN_UNUSED
#define DO_NOT_WARN_UNUSED
LIST_CLASS_ENTRY
#define LIST_CLASS_ENTRY(type)
Value:
struct { \
    class type *le_next; /* next element */ \
    class type **le_prev; /* address of previous next element */ \
}
LIST_CLASS_HEAD
#define LIST_CLASS_HEAD(name, type)
Value:
struct name { \
    class type *lh_first; /* first element */ \
}
LIST_EMPTY
#define LIST_EMPTY(head) ((head)->lh_first == NULL)
LIST_ENTRY
#define LIST_ENTRY(type)
Value:
struct { \
    struct type *le_next; /* next element */ \
    struct type **le_prev; /* address of previous next element */ \
}
LIST_FIRST
#define LIST_FIRST(head) ((head)->lh_first)
Referenced by mg_mqtt_disconnect().
LIST_FOREACH
#define LIST_FOREACH(var, head, field)
Value:
for ((var) = LIST_FIRST((head)); \
        (var); \
        (var) = LIST_NEXT((var), field))
LIST_FOREACH_FROM
#define LIST_FOREACH_FROM(var, head, field)
Value:
for ((var) = ((var) ? (var) : LIST_FIRST((head))); \
        (var); \
        (var) = LIST_NEXT((var), field))
LIST_FOREACH_FROM_SAFE
#define LIST_FOREACH_FROM_SAFE(var, head, field, tvar)
Value:
for ((var) = ((var) ? (var) : LIST_FIRST((head))); \
        (var) && ((tvar) = LIST_NEXT((var), field), 1); \
        (var) = (tvar))
LIST_FOREACH_SAFE
#define LIST_FOREACH_SAFE(var, head, field, tvar)
Value:
for ((var) = LIST_FIRST((head)); \
        (var) && ((tvar) = LIST_NEXT((var), field), 1); \
        (var) = (tvar))
LIST_HEAD
#define LIST_HEAD(name, type)
Value:
struct name { \
    struct type *lh_first; /* first element */ \
}
LIST_HEAD_INITIALIZER
#define LIST_HEAD_INITIALIZER(head) { NULL }
LIST_INIT
#define LIST_INIT(head)
Value:
do { \
    LIST_FIRST((head)) = NULL; \
} while (0)
Referenced by mg_mqtt_disconnect().
LIST_INSERT_AFTER
#define LIST_INSERT_AFTER(listelm, elm, field)
Value:
do { \
    QMD_LIST_CHECK_NEXT(listelm, field); \
    if ((LIST_NEXT((elm), field) = LIST_NEXT((listelm), field)) != NULL)\
        LIST_NEXT((listelm), field)->field.le_prev = \
            &LIST_NEXT((elm), field); \
    LIST_NEXT((listelm), field) = (elm); \
    (elm)->field.le_prev = &LIST_NEXT((listelm), field); \
} while (0)
LIST_INSERT_BEFORE
#define LIST_INSERT_BEFORE(listelm, elm, field)
Value:
do { \
    QMD_LIST_CHECK_PREV(listelm, field); \
    (elm)->field.le_prev = (listelm)->field.le_prev; \
    LIST_NEXT((elm), field) = (listelm); \
    *(listelm)->field.le_prev = (elm); \
    (listelm)->field.le_prev = &LIST_NEXT((elm), field); \
} while (0)
LIST_INSERT_HEAD
#define LIST_INSERT_HEAD(head, elm, field)
Value:
do { \
    QMD_LIST_CHECK_HEAD((head), field); \
    if ((LIST_NEXT((elm), field) = LIST_FIRST((head))) != NULL) \
        LIST_FIRST((head))->field.le_prev = &LIST_NEXT((elm), field);\
    LIST_FIRST((head)) = (elm); \
    (elm)->field.le_prev = &LIST_FIRST((head)); \
} while (0)
Referenced by mg_mqtt_disconnect().
LIST_NEXT
#define LIST_NEXT(elm, field) ((elm)->field.le_next)
Referenced by mg_mqtt_disconnect().
LIST_PREV
#define LIST_PREV(elm, head, type, field)
Value:
((elm)->field.le_prev == &LIST_FIRST((head)) ? NULL : \
        __containerof((elm)->field.le_prev, \
        QUEUE_TYPEOF(type), field.le_next))
LIST_REMOVE
#define LIST_REMOVE(elm, field)
Value:
do { \
    QMD_SAVELINK(oldnext, (elm)->field.le_next); \
    QMD_SAVELINK(oldprev, (elm)->field.le_prev); \
    QMD_LIST_CHECK_NEXT(elm, field); \
    QMD_LIST_CHECK_PREV(elm, field); \
    if (LIST_NEXT((elm), field) != NULL) \
        LIST_NEXT((elm), field)->field.le_prev = \
            (elm)->field.le_prev; \
    *(elm)->field.le_prev = LIST_NEXT((elm), field); \
    TRASHIT(*oldnext); \
    TRASHIT(*oldprev); \
} while (0)
Referenced by mg_mqtt_disconnect().
LIST_SWAP
#define LIST_SWAP(head1, head2, type, field)
Value:
do { \
    QUEUE_TYPEOF(type) *swap_tmp = LIST_FIRST(head1); \
    LIST_FIRST((head1)) = LIST_FIRST((head2)); \
    LIST_FIRST((head2)) = swap_tmp; \
    if ((swap_tmp = LIST_FIRST((head1))) != NULL) \
        swap_tmp->field.le_prev = &LIST_FIRST((head1)); \
    if ((swap_tmp = LIST_FIRST((head2))) != NULL) \
        swap_tmp->field.le_prev = &LIST_FIRST((head2)); \
} while (0)
MBUF_SIZE_MULTIPLIER
#define MBUF_SIZE_MULTIPLIER 1.5
Referenced by mbuf_insert().
MG_CB
#define MG_CB(cb, ud) cb
Referenced by mg_add_sock(), mg_bind(), mg_bind_opt(), mg_connect(), mg_connect_http(), mg_connect_http_base(), mg_connect_http_opt(), mg_connect_ws(), mg_connect_ws_opt(), mg_parse_http_basic_auth(), mg_resolve_async_opt(), mg_tun_bind_opt(), mg_tun_do_bind(), mg_tun_do_reconnect(), mg_tun_reconnect(), and mg_tun_send_frame().
MG_CGI_ENVIRONMENT_SIZE
#define MG_CGI_ENVIRONMENT_SIZE 8192
Referenced by mg_register_http_endpoint().
MG_DISABLE_HTTP_DIGEST_AUTH
#define MG_DISABLE_HTTP_DIGEST_AUTH 0
MG_DISABLE_HTTP_KEEP_ALIVE
#define MG_DISABLE_HTTP_KEEP_ALIVE 0
MG_DISABLE_PFS
#define MG_DISABLE_PFS 0
MG_DISABLE_WS_RANDOM_MASK
#define MG_DISABLE_WS_RANDOM_MASK 0
MG_DNS_A_RECORD
#define MG_DNS_A_RECORD 0x01 /* Lookup IP address */
Referenced by mg_connect_opt(), mg_dns_parse_record_data(), and resolve_cb().
MG_DNS_AAAA_RECORD
#define MG_DNS_AAAA_RECORD 0x1c /* Lookup IPv6 address */
Referenced by mg_dns_parse_record_data().
MG_DNS_ANY_RECORD
#define MG_DNS_ANY_RECORD 0xff
MG_DNS_CNAME_RECORD
#define MG_DNS_CNAME_RECORD 0x05 /* Lookup CNAME */
Referenced by mg_dns_encode_record(), and mg_dns_parse_record_data().
MG_DNS_MESSAGE
#define MG_DNS_MESSAGE 100 /* High-level DNS message event */
Referenced by dns_handler().
MG_DNS_MX_RECORD
#define MG_DNS_MX_RECORD 0x0f /* Lookup mail server for domain */
MG_DNS_NSEC_RECORD
#define MG_DNS_NSEC_RECORD 0x2f
MG_DNS_PTR_RECORD
#define MG_DNS_PTR_RECORD 0x0c /* Lookup PTR */
MG_DNS_SRV_RECORD
#define MG_DNS_SRV_RECORD 0x21 /* Lookup SRV */
MG_DNS_TXT_RECORD
#define MG_DNS_TXT_RECORD 0x10 /* Lookup TXT */
MG_ENABLE_ASYNC_RESOLVER
#define MG_ENABLE_ASYNC_RESOLVER 1
MG_ENABLE_BROADCAST
#define MG_ENABLE_BROADCAST 0
MG_ENABLE_CALLBACK_USERDATA
#define MG_ENABLE_CALLBACK_USERDATA 0
MG_ENABLE_COAP
#define MG_ENABLE_COAP 0
MG_ENABLE_DEBUG
#define MG_ENABLE_DEBUG 0
MG_ENABLE_DIRECTORY_LISTING
#define MG_ENABLE_DIRECTORY_LISTING 0
MG_ENABLE_DNS
#define MG_ENABLE_DNS 1
MG_ENABLE_DNS_SERVER
#define MG_ENABLE_DNS_SERVER 0
MG_ENABLE_EXTRA_ERRORS_DESC
#define MG_ENABLE_EXTRA_ERRORS_DESC 0
MG_ENABLE_FAKE_DAVLOCK
#define MG_ENABLE_FAKE_DAVLOCK 0
MG_ENABLE_FILESYSTEM
#define MG_ENABLE_FILESYSTEM 0
MG_ENABLE_GETADDRINFO
#define MG_ENABLE_GETADDRINFO 0
MG_ENABLE_HEXDUMP
#define MG_ENABLE_HEXDUMP CS_ENABLE_STDIO
MG_ENABLE_HTTP
#define MG_ENABLE_HTTP 1
MG_ENABLE_HTTP_CGI
#define MG_ENABLE_HTTP_CGI 0
MG_ENABLE_HTTP_SSI
#define MG_ENABLE_HTTP_SSI MG_ENABLE_FILESYSTEM
MG_ENABLE_HTTP_SSI_EXEC
#define MG_ENABLE_HTTP_SSI_EXEC 0
MG_ENABLE_HTTP_STREAMING_MULTIPART
#define MG_ENABLE_HTTP_STREAMING_MULTIPART 0
Referenced by mg_http_call_endpoint_handler().
MG_ENABLE_HTTP_URL_REWRITES
#define MG_ENABLE_HTTP_URL_REWRITES (CS_PLATFORM == CS_P_WINDOWS || CS_PLATFORM == CS_P_UNIX)
MG_ENABLE_HTTP_WEBDAV
#define MG_ENABLE_HTTP_WEBDAV 0
Referenced by mg_parse_http_basic_auth().
MG_ENABLE_HTTP_WEBSOCKET
#define MG_ENABLE_HTTP_WEBSOCKET MG_ENABLE_HTTP
MG_ENABLE_IPV6
#define MG_ENABLE_IPV6 0
MG_ENABLE_MQTT
#define MG_ENABLE_MQTT 1
MG_ENABLE_MQTT_BROKER
#define MG_ENABLE_MQTT_BROKER 0
MG_ENABLE_SNTP
#define MG_ENABLE_SNTP 0
MG_ENABLE_SOCKS
#define MG_ENABLE_SOCKS 0
MG_ENABLE_SSL
#define MG_ENABLE_SSL 0
MG_ENABLE_STDIO
#define MG_ENABLE_STDIO CS_ENABLE_STDIO
MG_ENABLE_SYNC_RESOLVER
#define MG_ENABLE_SYNC_RESOLVER 0
MG_ENABLE_THREADS
#define MG_ENABLE_THREADS 0
MG_ENABLE_TUN
#define MG_ENABLE_TUN MG_ENABLE_HTTP_WEBSOCKET
MG_EV_ACCEPT
#define MG_EV_ACCEPT 1 /* New connection accepted. union socket_address * */
Referenced by mg_conn_addr_to_str(), mg_if_accept_tcp_cb(), mg_if_recv_udp_cb(), mg_mqtt_disconnect(), and mqtt_handler().
MG_EV_CLOSE
#define MG_EV_CLOSE 5 /* Connection is closed. NULL */
Referenced by mg_close_conn(), mg_conn_addr_to_str(), mg_http_handler(), mg_mqtt_disconnect(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_tun_client_handler(), mg_tun_send_frame(), and resolve_cb().
MG_EV_CONNECT
#define MG_EV_CONNECT 2 /* connect() succeeded or failed. int * */
Referenced by mg_conn_addr_to_str(), mg_if_connect_cb(), mg_parse_http_basic_auth(), mg_resolve_async_eh(), mg_tun_client_handler(), mg_tun_send_frame(), and resolve_cb().
MG_EV_HTTP_CHUNK
#define MG_EV_HTTP_CHUNK 102 /* struct http_message * */
Referenced by deliver_chunk(), and mg_handle_chunked().
MG_EV_HTTP_REPLY
#define MG_EV_HTTP_REPLY 101 /* struct http_message * */
Referenced by mg_http_handler(), mg_parse_http_basic_auth(), and mg_tun_client_handler().
MG_EV_HTTP_REQUEST
#define MG_EV_HTTP_REQUEST 100 /* struct http_message * */
Referenced by mg_http_call_endpoint_handler(), and mg_http_handler().
MG_EV_MQTT_CONNACK
#define MG_EV_MQTT_CONNACK (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_CONNACK)
MG_EV_MQTT_CONNACK_ACCEPTED
#define MG_EV_MQTT_CONNACK_ACCEPTED 0
Referenced by mg_mqtt_disconnect().
MG_EV_MQTT_CONNACK_BAD_AUTH
#define MG_EV_MQTT_CONNACK_BAD_AUTH 4
MG_EV_MQTT_CONNACK_IDENTIFIER_REJECTED
#define MG_EV_MQTT_CONNACK_IDENTIFIER_REJECTED 2
MG_EV_MQTT_CONNACK_NOT_AUTHORIZED
#define MG_EV_MQTT_CONNACK_NOT_AUTHORIZED 5
MG_EV_MQTT_CONNACK_SERVER_UNAVAILABLE
#define MG_EV_MQTT_CONNACK_SERVER_UNAVAILABLE 3
Referenced by mg_mqtt_disconnect().
MG_EV_MQTT_CONNACK_UNACCEPTABLE_VERSION
#define MG_EV_MQTT_CONNACK_UNACCEPTABLE_VERSION 1
MG_EV_MQTT_CONNECT
#define MG_EV_MQTT_CONNECT (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_CONNECT)
Referenced by mg_mqtt_disconnect().
MG_EV_MQTT_DISCONNECT
#define MG_EV_MQTT_DISCONNECT (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_DISCONNECT)
MG_EV_MQTT_PINGREQ
#define MG_EV_MQTT_PINGREQ (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PINGREQ)
MG_EV_MQTT_PINGRESP
#define MG_EV_MQTT_PINGRESP (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PINGRESP)
MG_EV_MQTT_PUBACK
#define MG_EV_MQTT_PUBACK (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBACK)
MG_EV_MQTT_PUBCOMP
#define MG_EV_MQTT_PUBCOMP (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBCOMP)
MG_EV_MQTT_PUBLISH
#define MG_EV_MQTT_PUBLISH (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBLISH)
Referenced by mg_mqtt_disconnect().
MG_EV_MQTT_PUBREC
#define MG_EV_MQTT_PUBREC (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBREC)
MG_EV_MQTT_PUBREL
#define MG_EV_MQTT_PUBREL (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_PUBREL)
MG_EV_MQTT_SUBACK
#define MG_EV_MQTT_SUBACK (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_SUBACK)
MG_EV_MQTT_SUBSCRIBE
#define MG_EV_MQTT_SUBSCRIBE (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_SUBSCRIBE)
Referenced by mg_mqtt_disconnect().
MG_EV_MQTT_UNSUBACK
#define MG_EV_MQTT_UNSUBACK (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_UNSUBACK)
MG_EV_MQTT_UNSUBSCRIBE
#define MG_EV_MQTT_UNSUBSCRIBE (MG_MQTT_EVENT_BASE + MG_MQTT_CMD_UNSUBSCRIBE)
MG_EV_POLL
#define MG_EV_POLL 0 /* Sent to each connection on each mg_mgr_poll() call */
Referenced by TBT::ev_handler_StateChange(), mg_call(), mg_if_poll(), mg_mgr_handle_conn(), mg_resolve_async_eh(), mg_ws_handler(), and mqtt_handler().
MG_EV_RECV
#define MG_EV_RECV 3 /* Data has been received. int *num_bytes */
Referenced by dns_handler(), mg_call(), mg_conn_addr_to_str(), mg_http_handler(), mg_recv_common(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_set_nameserver(), mg_tun_send_frame(), mg_ws_handler(), and mqtt_handler().
MG_EV_SEND
#define MG_EV_SEND 4 /* Data has been written to a socket. int *num_bytes */
Referenced by mg_call(), mg_conn_addr_to_str(), mg_if_sent_cb(), and mg_resolve_async_eh().
MG_EV_SSI_CALL
#define MG_EV_SSI_CALL 105 /* char * */
Referenced by mg_register_http_endpoint().
MG_EV_SSI_CALL_CTX
#define MG_EV_SSI_CALL_CTX 106 /* struct mg_ssi_call_ctx * */
Referenced by mg_register_http_endpoint().
MG_EV_TIMER
#define MG_EV_TIMER 6 /* now >= conn->ev_timer_time. double * */
Referenced by mg_if_timer(), mg_resolve_async_eh(), mg_tun_reconnect_ev_handler(), mg_tun_send_frame(), and resolve_cb().
MG_EV_WEBSOCKET_CONTROL_FRAME
#define MG_EV_WEBSOCKET_CONTROL_FRAME 114 /* struct websocket_message * */
Referenced by mg_handle_incoming_websocket_frame().
MG_EV_WEBSOCKET_FRAME
#define MG_EV_WEBSOCKET_FRAME 113 /* struct websocket_message * */
Referenced by TBT::ev_handler(), mg_handle_incoming_websocket_frame(), and mg_tun_client_handler().
MG_EV_WEBSOCKET_HANDSHAKE_DONE
#define MG_EV_WEBSOCKET_HANDSHAKE_DONE 112 /* NULL */
Referenced by mg_http_handler(), and mg_tun_client_handler().
MG_EV_WEBSOCKET_HANDSHAKE_REQUEST
#define MG_EV_WEBSOCKET_HANDSHAKE_REQUEST 111 /* struct http_message * */
Referenced by mg_http_handler().
MG_F_CLOSE_IMMEDIATELY
#define MG_F_CLOSE_IMMEDIATELY (1 << 11) /* Disconnect */
Referenced by mg_deliver_websocket_data(), mg_get_line_len(), mg_handle_tcp_read(), mg_handle_udp_read(), mg_http_handler(), mg_if_connect_cb(), mg_if_sent_cb(), mg_mgr_handle_conn(), mg_mqtt_disconnect(), mg_parse_http_basic_auth(), mg_recv_common(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_socket_if_poll(), mg_tun_client_handler(), mg_tun_close_all(), mg_tun_destroy_client(), mg_tun_send_frame(), mg_write_to_socket(), and mqtt_handler().
MG_F_CONNECTING
#define MG_F_CONNECTING (1 << 3) /* connect() call in progress */
Referenced by mg_do_connect(), mg_if_connect_cb(), mg_mgr_handle_conn(), and mg_socket_if_poll().
MG_F_DELETE_CHUNK
#define MG_F_DELETE_CHUNK (1 << 13) /* HTTP specific */
Referenced by deliver_chunk(), and mg_handle_chunked().
MG_F_ENABLE_BROADCAST
#define MG_F_ENABLE_BROADCAST (1 << 14) /* Allow broadcast address usage */
Referenced by mg_socket_if_connect_udp().
MG_F_IS_WEBSOCKET
#define MG_F_IS_WEBSOCKET (1 << 8) /* Websocket specific */
Referenced by mg_http_handler(), and mg_ws_handler().
MG_F_LISTENING
#define MG_F_LISTENING (1 << 0) /* This connection is listening */
Referenced by mg_bind_opt(), mg_if_recv_udp_cb(), mg_mgr_handle_conn(), mg_tun_close_all(), mg_tun_if_destroy_conn(), and mg_tun_if_find_conn().
MG_F_RESOLVING
#define MG_F_RESOLVING (1 << 2) /* Waiting for async resolver */
Referenced by mg_connect_opt(), mg_set_timer(), and resolve_cb().
MG_F_SEND_AND_CLOSE
#define MG_F_SEND_AND_CLOSE (1 << 10) /* Push remaining data and close */
Referenced by mg_deliver_websocket_data(), mg_get_http_header(), mg_handle_tcp_read(), mg_http_free_reverse_proxy_data(), mg_http_handler(), mg_http_send_error(), mg_if_recv_udp_cb(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_send_websocket_frame(), mg_send_websocket_framev(), mg_socket_if_poll(), and mg_tun_send_frame().
MG_F_SSL
#define MG_F_SSL (1 << 4) /* SSL is enabled on the connection */
Referenced by mg_accept_conn(), mg_bind_opt(), mg_connect_opt(), mg_handle_tcp_read(), mg_if_accept_new_conn(), mg_if_poll(), mg_mgr_handle_conn(), mg_register_http_endpoint(), and mg_write_to_socket().
MG_F_SSL_HANDSHAKE_DONE
#define MG_F_SSL_HANDSHAKE_DONE (1 << 5) /* SSL hanshake has completed */
Referenced by mg_close_conn(), mg_handle_tcp_read(), mg_handle_udp_read(), mg_if_poll(), and mg_write_to_socket().
MG_F_TUN_DO_NOT_RECONNECT
#define MG_F_TUN_DO_NOT_RECONNECT (1 << 15) /* Don't reconnect tunnel */
Referenced by mg_tun_reconnect_ev_handler().
MG_F_UDP
#define MG_F_UDP (1 << 1) /* This connection is UDP */
Referenced by dns_handler(), mg_bind_opt(), mg_call(), mg_connect_opt(), mg_if_recv_udp_cb(), mg_mgr_handle_conn(), mg_send(), mg_send_dns_query(), mg_set_nameserver(), mg_set_protocol_dns(), mg_socket_if_destroy_conn(), mg_socket_if_get_conn_addr(), mg_socket_if_poll(), mg_tun_send_frame(), mg_write_to_socket(), and resolve_cb().
MG_F_USER_1
#define MG_F_USER_1 (1 << 20) /* Flags left for application */
MG_F_USER_2
#define MG_F_USER_2 (1 << 21)
MG_F_USER_3
#define MG_F_USER_3 (1 << 22)
MG_F_USER_4
#define MG_F_USER_4 (1 << 23)
MG_F_USER_5
#define MG_F_USER_5 (1 << 24)
MG_F_USER_6
#define MG_F_USER_6 (1 << 25)
MG_F_WANT_READ
#define MG_F_WANT_READ (1 << 6) /* SSL specific */
Referenced by mg_handle_udp_read(), mg_mgr_handle_conn(), mg_socket_if_poll(), and mg_write_to_socket().
MG_F_WANT_WRITE
#define MG_F_WANT_WRITE (1 << 7) /* SSL specific */
Referenced by mg_handle_udp_read(), mg_mgr_handle_conn(), mg_socket_if_poll(), and mg_write_to_socket().
MG_F_WEBSOCKET_NO_DEFRAG
#define MG_F_WEBSOCKET_NO_DEFRAG (1 << 12) /* Websocket specific */
Referenced by mg_deliver_websocket_data().
MG_LWIP
#define MG_LWIP 0
Referenced by mg_open_listening_socket().
MG_MAIN_IFACE
#define MG_MAIN_IFACE 0
Referenced by mg_create_connection_base(), and mg_mgr_init_opt().
MG_MAX_DNS_ANSWERS
#define MG_MAX_DNS_ANSWERS 32
Referenced by mg_set_protocol_dns().
MG_MAX_DNS_QUESTIONS
#define MG_MAX_DNS_QUESTIONS 32
MG_MAX_HTTP_HEADERS
#define MG_MAX_HTTP_HEADERS 20
Referenced by mg_parse_http_basic_auth().
MG_MAX_HTTP_REQUEST_SIZE
#define MG_MAX_HTTP_REQUEST_SIZE 1024
Referenced by mg_http_handler(), and mg_register_http_endpoint().
MG_MAX_HTTP_SEND_MBUF
#define MG_MAX_HTTP_SEND_MBUF 1024
Referenced by mg_get_http_header().
MG_MAX_PATH
#define MG_MAX_PATH 256
Referenced by mg_parse_http_basic_auth(), mg_register_http_endpoint(), and mg_skip().
MG_MK_STR
#define MG_MK_STR(str_literal) { str_literal, sizeof(str_literal) - 1 }
Referenced by mg_parse_http_basic_auth(), and mg_register_http_endpoint().
MG_MQTT_CLEAN_SESSION
#define MG_MQTT_CLEAN_SESSION 0x02
MG_MQTT_CMD_CONNACK
#define MG_MQTT_CMD_CONNACK 2
Referenced by mg_mqtt_connack(), and parse_mqtt().
MG_MQTT_CMD_CONNECT
#define MG_MQTT_CMD_CONNECT 1
Referenced by mg_send_mqtt_handshake_opt(), and parse_mqtt().
MG_MQTT_CMD_DISCONNECT
#define MG_MQTT_CMD_DISCONNECT 14
Referenced by mg_mqtt_disconnect().
MG_MQTT_CMD_PINGREQ
#define MG_MQTT_CMD_PINGREQ 12
Referenced by mg_mqtt_ping().
MG_MQTT_CMD_PINGRESP
#define MG_MQTT_CMD_PINGRESP 13
Referenced by mg_mqtt_pong().
MG_MQTT_CMD_PUBACK
#define MG_MQTT_CMD_PUBACK 4
Referenced by mg_mqtt_puback(), and parse_mqtt().
MG_MQTT_CMD_PUBCOMP
#define MG_MQTT_CMD_PUBCOMP 7
Referenced by mg_mqtt_pubcomp(), and parse_mqtt().
MG_MQTT_CMD_PUBLISH
#define MG_MQTT_CMD_PUBLISH 3
Referenced by mg_mqtt_publish(), and parse_mqtt().
MG_MQTT_CMD_PUBREC
#define MG_MQTT_CMD_PUBREC 5
Referenced by mg_mqtt_pubrec(), and parse_mqtt().
MG_MQTT_CMD_PUBREL
#define MG_MQTT_CMD_PUBREL 6
Referenced by mg_mqtt_pubrel(), mg_send_mqtt_short_command(), and parse_mqtt().
MG_MQTT_CMD_SUBACK
#define MG_MQTT_CMD_SUBACK 9
Referenced by mg_mqtt_suback(), and parse_mqtt().
MG_MQTT_CMD_SUBSCRIBE
#define MG_MQTT_CMD_SUBSCRIBE 8
Referenced by mg_mqtt_subscribe(), and parse_mqtt().
MG_MQTT_CMD_UNSUBACK
#define MG_MQTT_CMD_UNSUBACK 11
Referenced by mg_mqtt_unsuback().
MG_MQTT_CMD_UNSUBSCRIBE
#define MG_MQTT_CMD_UNSUBSCRIBE 10
Referenced by mg_mqtt_unsubscribe().
MG_MQTT_DUP
#define MG_MQTT_DUP 0x4
MG_MQTT_EVENT_BASE
#define MG_MQTT_EVENT_BASE 200
Referenced by mqtt_handler().
MG_MQTT_GET_QOS
#define MG_MQTT_GET_QOS(flags) (((flags) &0x6) >> 1)
Referenced by mg_mqtt_publish(), and parse_mqtt().
MG_MQTT_GET_WILL_QOS
#define MG_MQTT_GET_WILL_QOS(flags) (((flags) &0x18) >> 3)
MG_MQTT_HAS_PASSWORD
#define MG_MQTT_HAS_PASSWORD 0x40
Referenced by mg_send_mqtt_handshake_opt(), and parse_mqtt().
MG_MQTT_HAS_USER_NAME
#define MG_MQTT_HAS_USER_NAME 0x80
Referenced by mg_send_mqtt_handshake_opt(), and parse_mqtt().
MG_MQTT_HAS_WILL
#define MG_MQTT_HAS_WILL 0x04
Referenced by mg_send_mqtt_handshake_opt(), and parse_mqtt().
MG_MQTT_QOS
#define MG_MQTT_QOS(qos) ((qos) << 1)
Referenced by mg_mqtt_suback(), mg_mqtt_subscribe(), and mg_mqtt_unsubscribe().
MG_MQTT_RETAIN
#define MG_MQTT_RETAIN 0x1
MG_MQTT_SET_QOS
#define MG_MQTT_SET_QOS(flags, qos) (flags) = ((flags) & ~0x6) | ((qos) << 1)
MG_MQTT_SET_WILL_QOS
#define MG_MQTT_SET_WILL_QOS(flags, qos) (flags) = ((flags) & ~0x18) | ((qos) << 3)
MG_MQTT_WILL_RETAIN
#define MG_MQTT_WILL_RETAIN 0x20
MG_NET_IF
#define MG_NET_IF MG_NET_IF_SOCKET
MG_NET_IF_LWIP_LOW_LEVEL
#define MG_NET_IF_LWIP_LOW_LEVEL 3
MG_NET_IF_PIC32
#define MG_NET_IF_PIC32 4
MG_NET_IF_SIMPLELINK
#define MG_NET_IF_SIMPLELINK 2
MG_NET_IF_SOCKET
#define MG_NET_IF_SOCKET 1
MG_NULL_STR
#define MG_NULL_STR { NULL, 0 }
Referenced by mg_connect_http_opt(), mg_connect_ws_opt(), mg_parse_http_basic_auth(), and mg_send_websocket_handshake().
MG_RECV_FUNC
#define MG_RECV_FUNC(s, b, l, f) recv(s, b, l, f)
Referenced by mg_handle_tcp_read(), mg_mgr_handle_conn(), and mg_next().
MG_SEND_FUNC
#define MG_SEND_FUNC(s, b, l, f) send(s, b, l, f)
Referenced by mg_mgr_handle_conn(), mg_next(), and mg_write_to_socket().
MG_SOCK_STRINGIFY_IP
#define MG_SOCK_STRINGIFY_IP 1
Referenced by TBT::ev_handler(), mg_conn_addr_to_str(), mg_http_handler(), mg_register_http_endpoint(), mg_resolve_async_eh(), and mg_sock_addr_to_str().
MG_SOCK_STRINGIFY_PORT
#define MG_SOCK_STRINGIFY_PORT 2
Referenced by TBT::ev_handler(), mg_conn_addr_to_str(), mg_http_handler(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), and mg_sock_addr_to_str().
MG_SOCK_STRINGIFY_REMOTE
#define MG_SOCK_STRINGIFY_REMOTE 4
Referenced by mg_conn_addr_to_str(), mg_register_http_endpoint(), and mg_sock_to_str().
MG_SSL_IF
#define MG_SSL_IF MG_SSL_IF_OPENSSL
MG_SSL_IF_MBEDTLS
#define MG_SSL_IF_MBEDTLS 2
MG_SSL_IF_OPENSSL
#define MG_SSL_IF_OPENSSL 1
MG_SSL_IF_SIMPLELINK
#define MG_SSL_IF_SIMPLELINK 3
MG_UD_ARG
#define MG_UD_ARG(ud)
Referenced by deliver_chunk(), dns_handler(), mg_call(), mg_http_handler(), mg_mgr_handle_conn(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_set_nameserver(), mg_tun_send_frame(), and mqtt_handler().
MG_VERSION
#define MG_VERSION `6.10`
Referenced by mg_register_http_endpoint().
MG_VPRINTF_BUFFER_SIZE
#define MG_VPRINTF_BUFFER_SIZE 100
Referenced by mg_printf_html_escape(), mg_printf_http_chunk(), mg_printf_websocket_frame(), and mg_vprintf().
NOINLINE
#define NOINLINE
NOINSTR
#define NOINSTR
NORETURN
#define NORETURN
QMD_LIST_CHECK_HEAD
#define QMD_LIST_CHECK_HEAD(head, field)
QMD_LIST_CHECK_NEXT
#define QMD_LIST_CHECK_NEXT(elm, field)
QMD_LIST_CHECK_PREV
#define QMD_LIST_CHECK_PREV(elm, field)
QMD_SAVELINK
#define QMD_SAVELINK(name, link)
QMD_TAILQ_CHECK_HEAD
#define QMD_TAILQ_CHECK_HEAD(head, field)
QMD_TAILQ_CHECK_NEXT
#define QMD_TAILQ_CHECK_NEXT(elm, field)
QMD_TAILQ_CHECK_PREV
#define QMD_TAILQ_CHECK_PREV(elm, field)
QMD_TAILQ_CHECK_TAIL
#define QMD_TAILQ_CHECK_TAIL(head, headname)
QMD_TRACE_ELEM
#define QMD_TRACE_ELEM(elem)
QMD_TRACE_HEAD
#define QMD_TRACE_HEAD(head)
QUEUE_TYPEOF
#define QUEUE_TYPEOF(type) struct type
SLIST_CLASS_ENTRY
#define SLIST_CLASS_ENTRY(type)
Value:
struct { \
    class type *sle_next; /* next element */ \
}
SLIST_CLASS_HEAD
#define SLIST_CLASS_HEAD(name, type)
Value:
struct name { \
    class type *slh_first; /* first element */ \
}
SLIST_EMPTY
#define SLIST_EMPTY(head) ((head)->slh_first == NULL)
SLIST_ENTRY
#define SLIST_ENTRY(type)
Value:
struct { \
    struct type *sle_next; /* next element */ \
}
SLIST_FIRST
#define SLIST_FIRST(head) ((head)->slh_first)
SLIST_FOREACH
#define SLIST_FOREACH(var, head, field)
Value:
for ((var) = SLIST_FIRST((head)); \
        (var); \
        (var) = SLIST_NEXT((var), field))
SLIST_FOREACH_FROM
#define SLIST_FOREACH_FROM(var, head, field)
Value:
for ((var) = ((var) ? (var) : SLIST_FIRST((head))); \
        (var); \
        (var) = SLIST_NEXT((var), field))
SLIST_FOREACH_FROM_SAFE
#define SLIST_FOREACH_FROM_SAFE(var, head, field, tvar)
Value:
for ((var) = ((var) ? (var) : SLIST_FIRST((head))); \
        (var) && ((tvar) = SLIST_NEXT((var), field), 1); \
        (var) = (tvar))
SLIST_FOREACH_PREVPTR
#define SLIST_FOREACH_PREVPTR(var, varp, head, field)
Value:
for ((varp) = &SLIST_FIRST((head)); \
        ((var) = *(varp)) != NULL; \
        (varp) = &SLIST_NEXT((var), field))
SLIST_FOREACH_SAFE
#define SLIST_FOREACH_SAFE(var, head, field, tvar)
Value:
for ((var) = SLIST_FIRST((head)); \
        (var) && ((tvar) = SLIST_NEXT((var), field), 1); \
        (var) = (tvar))
SLIST_HEAD
#define SLIST_HEAD(name, type)
Value:
struct name { \
    struct type *slh_first; /* first element */ \
}
SLIST_HEAD_INITIALIZER
#define SLIST_HEAD_INITIALIZER(head) { NULL }
SLIST_INIT
#define SLIST_INIT(head)
Value:
do { \
    SLIST_FIRST((head)) = NULL; \
} while (0)
SLIST_INSERT_AFTER
#define SLIST_INSERT_AFTER(slistelm, elm, field)
Value:
do { \
    SLIST_NEXT((elm), field) = SLIST_NEXT((slistelm), field); \
    SLIST_NEXT((slistelm), field) = (elm); \
} while (0)
SLIST_INSERT_HEAD
#define SLIST_INSERT_HEAD(head, elm, field)
Value:
do { \
    SLIST_NEXT((elm), field) = SLIST_FIRST((head)); \
    SLIST_FIRST((head)) = (elm); \
} while (0)
SLIST_NEXT
#define SLIST_NEXT(elm, field) ((elm)->field.sle_next)
SLIST_REMOVE
#define SLIST_REMOVE(head, elm, type, field)
Value:
do { \
    QMD_SAVELINK(oldnext, (elm)->field.sle_next); \
    if (SLIST_FIRST((head)) == (elm)) { \
        SLIST_REMOVE_HEAD((head), field); \
    } \
    else { \
        QUEUE_TYPEOF(type) *curelm = SLIST_FIRST(head); \
        while (SLIST_NEXT(curelm, field) != (elm)) \
            curelm = SLIST_NEXT(curelm, field); \
        SLIST_REMOVE_AFTER(curelm, field); \
    } \
    TRASHIT(*oldnext); \
} while (0)
SLIST_REMOVE_AFTER
#define SLIST_REMOVE_AFTER(elm, field)
Value:
do { \
    SLIST_NEXT(elm, field) = \
        SLIST_NEXT(SLIST_NEXT(elm, field), field); \
} while (0)
SLIST_REMOVE_HEAD
#define SLIST_REMOVE_HEAD(head, field)
Value:
do { \
    SLIST_FIRST((head)) = SLIST_NEXT(SLIST_FIRST((head)), field); \
} while (0)
SLIST_SWAP
#define SLIST_SWAP(head1, head2, type)
Value:
do { \
    QUEUE_TYPEOF(type) *swap_first = SLIST_FIRST(head1); \
    SLIST_FIRST(head1) = SLIST_FIRST(head2); \
    SLIST_FIRST(head2) = swap_first; \
} while (0)
STAILQ_CLASS_ENTRY
#define STAILQ_CLASS_ENTRY(type)
Value:
struct { \
    class type *stqe_next; /* next element */ \
}
STAILQ_CLASS_HEAD
#define STAILQ_CLASS_HEAD(name, type)
Value:
struct name { \
    class type *stqh_first; /* first element */ \
    class type **stqh_last; /* addr of last next element */ \
}
STAILQ_CONCAT
#define STAILQ_CONCAT(head1, head2)
Value:
do { \
    if (!STAILQ_EMPTY((head2))) { \
        *(head1)->stqh_last = (head2)->stqh_first; \
        (head1)->stqh_last = (head2)->stqh_last; \
        STAILQ_INIT((head2)); \
    } \
} while (0)
STAILQ_EMPTY
#define STAILQ_EMPTY(head) ((head)->stqh_first == NULL)
STAILQ_ENTRY
#define STAILQ_ENTRY(type)
Value:
struct { \
    struct type *stqe_next; /* next element */ \
}
STAILQ_FIRST
#define STAILQ_FIRST(head) ((head)->stqh_first)
STAILQ_FOREACH
#define STAILQ_FOREACH(var, head, field)
Value:
for((var) = STAILQ_FIRST((head)); \
       (var); \
       (var) = STAILQ_NEXT((var), field))
STAILQ_FOREACH_FROM
#define STAILQ_FOREACH_FROM(var, head, field)
Value:
for ((var) = ((var) ? (var) : STAILQ_FIRST((head))); \
       (var); \
       (var) = STAILQ_NEXT((var), field))
STAILQ_FOREACH_FROM_SAFE
#define STAILQ_FOREACH_FROM_SAFE(var, head, field, tvar)
Value:
for ((var) = ((var) ? (var) : STAILQ_FIRST((head))); \
        (var) && ((tvar) = STAILQ_NEXT((var), field), 1); \
        (var) = (tvar))
STAILQ_FOREACH_SAFE
#define STAILQ_FOREACH_SAFE(var, head, field, tvar)
Value:
for ((var) = STAILQ_FIRST((head)); \
        (var) && ((tvar) = STAILQ_NEXT((var), field), 1); \
        (var) = (tvar))
STAILQ_HEAD
#define STAILQ_HEAD(name, type)
Value:
struct name { \
    struct type *stqh_first;/* first element */ \
    struct type **stqh_last;/* addr of last next element */ \
}
STAILQ_HEAD_INITIALIZER
#define STAILQ_HEAD_INITIALIZER(head) { NULL, &(head).stqh_first }
STAILQ_INIT
#define STAILQ_INIT(head)
Value:
do { \
    STAILQ_FIRST((head)) = NULL; \
    (head)->stqh_last = &STAILQ_FIRST((head)); \
} while (0)
STAILQ_INSERT_AFTER
#define STAILQ_INSERT_AFTER(head, tqelm, elm, field)
Value:
do { \
    if ((STAILQ_NEXT((elm), field) = STAILQ_NEXT((tqelm), field)) == NULL)\
        (head)->stqh_last = &STAILQ_NEXT((elm), field); \
    STAILQ_NEXT((tqelm), field) = (elm); \
} while (0)
STAILQ_INSERT_HEAD
#define STAILQ_INSERT_HEAD(head, elm, field)
Value:
do { \
    if ((STAILQ_NEXT((elm), field) = STAILQ_FIRST((head))) == NULL) \
        (head)->stqh_last = &STAILQ_NEXT((elm), field); \
    STAILQ_FIRST((head)) = (elm); \
} while (0)
STAILQ_INSERT_TAIL
#define STAILQ_INSERT_TAIL(head, elm, field)
Value:
do { \
    STAILQ_NEXT((elm), field) = NULL; \
    *(head)->stqh_last = (elm); \
    (head)->stqh_last = &STAILQ_NEXT((elm), field); \
} while (0)
STAILQ_LAST
#define STAILQ_LAST(head, type, field)
Value:
(STAILQ_EMPTY((head)) ? NULL : \
        __containerof((head)->stqh_last, \
        QUEUE_TYPEOF(type), field.stqe_next))
STAILQ_NEXT
#define STAILQ_NEXT(elm, field) ((elm)->field.stqe_next)
STAILQ_REMOVE
#define STAILQ_REMOVE(head, elm, type, field)
Value:
do { \
    QMD_SAVELINK(oldnext, (elm)->field.stqe_next); \
    if (STAILQ_FIRST((head)) == (elm)) { \
        STAILQ_REMOVE_HEAD((head), field); \
    } \
    else { \
        QUEUE_TYPEOF(type) *curelm = STAILQ_FIRST(head); \
        while (STAILQ_NEXT(curelm, field) != (elm)) \
            curelm = STAILQ_NEXT(curelm, field); \
        STAILQ_REMOVE_AFTER(head, curelm, field); \
    } \
    TRASHIT(*oldnext); \
} while (0)
STAILQ_REMOVE_AFTER
#define STAILQ_REMOVE_AFTER(head, elm, field)
Value:
do { \
    if ((STAILQ_NEXT(elm, field) = \
         STAILQ_NEXT(STAILQ_NEXT(elm, field), field)) == NULL) \
        (head)->stqh_last = &STAILQ_NEXT((elm), field); \
} while (0)
STAILQ_REMOVE_HEAD
#define STAILQ_REMOVE_HEAD(head, field)
Value:
do { \
    if ((STAILQ_FIRST((head)) = \
         STAILQ_NEXT(STAILQ_FIRST((head)), field)) == NULL) \
        (head)->stqh_last = &STAILQ_FIRST((head)); \
} while (0)
STAILQ_SWAP
#define STAILQ_SWAP(head1, head2, type)
Value:
do { \
    QUEUE_TYPEOF(type) *swap_first = STAILQ_FIRST(head1); \
    QUEUE_TYPEOF(type) **swap_last = (head1)->stqh_last; \
    STAILQ_FIRST(head1) = STAILQ_FIRST(head2); \
    (head1)->stqh_last = (head2)->stqh_last; \
    STAILQ_FIRST(head2) = swap_first; \
    (head2)->stqh_last = swap_last; \
    if (STAILQ_EMPTY(head1)) \
        (head1)->stqh_last = &STAILQ_FIRST(head1); \
    if (STAILQ_EMPTY(head2)) \
        (head2)->stqh_last = &STAILQ_FIRST(head2); \
} while (0)
TAILQ_CLASS_ENTRY
#define TAILQ_CLASS_ENTRY(type)
Value:
struct { \
    class type *tqe_next; /* next element */ \
    class type **tqe_prev; /* address of previous next element */ \
    TRACEBUF \
}
TAILQ_CLASS_HEAD
#define TAILQ_CLASS_HEAD(name, type)
Value:
struct name { \
    class type *tqh_first; /* first element */ \
    class type **tqh_last; /* addr of last next element */ \
    TRACEBUF \
}
TAILQ_CONCAT
#define TAILQ_CONCAT(head1, head2, field)
Value:
do { \
    if (!TAILQ_EMPTY(head2)) { \
        *(head1)->tqh_last = (head2)->tqh_first; \
        (head2)->tqh_first->field.tqe_prev = (head1)->tqh_last; \
        (head1)->tqh_last = (head2)->tqh_last; \
        TAILQ_INIT((head2)); \
        QMD_TRACE_HEAD(head1); \
        QMD_TRACE_HEAD(head2); \
    } \
} while (0)
TAILQ_EMPTY
#define TAILQ_EMPTY(head) ((head)->tqh_first == NULL)
TAILQ_ENTRY
#define TAILQ_ENTRY(type)
Value:
struct { \
    struct type *tqe_next; /* next element */ \
    struct type **tqe_prev; /* address of previous next element */ \
    TRACEBUF \
}
TAILQ_FIRST
#define TAILQ_FIRST(head) ((head)->tqh_first)
TAILQ_FOREACH
#define TAILQ_FOREACH(var, head, field)
Value:
for ((var) = TAILQ_FIRST((head)); \
        (var); \
        (var) = TAILQ_NEXT((var), field))
TAILQ_FOREACH_FROM
#define TAILQ_FOREACH_FROM(var, head, field)
Value:
for ((var) = ((var) ? (var) : TAILQ_FIRST((head))); \
        (var); \
        (var) = TAILQ_NEXT((var), field))
TAILQ_FOREACH_FROM_SAFE
#define TAILQ_FOREACH_FROM_SAFE(var, head, field, tvar)
Value:
for ((var) = ((var) ? (var) : TAILQ_FIRST((head))); \
        (var) && ((tvar) = TAILQ_NEXT((var), field), 1); \
        (var) = (tvar))
TAILQ_FOREACH_REVERSE
#define TAILQ_FOREACH_REVERSE(var, head, headname, field)
Value:
for ((var) = TAILQ_LAST((head), headname); \
        (var); \
        (var) = TAILQ_PREV((var), headname, field))
TAILQ_FOREACH_REVERSE_FROM
#define TAILQ_FOREACH_REVERSE_FROM(var, head, headname, field)
Value:
for ((var) = ((var) ? (var) : TAILQ_LAST((head), headname)); \
        (var); \
        (var) = TAILQ_PREV((var), headname, field))
TAILQ_FOREACH_REVERSE_FROM_SAFE
#define TAILQ_FOREACH_REVERSE_FROM_SAFE(var, head, headname, field, tvar)
Value:
for ((var) = ((var) ? (var) : TAILQ_LAST((head), headname)); \
        (var) && ((tvar) = TAILQ_PREV((var), headname, field), 1); \
        (var) = (tvar))
TAILQ_FOREACH_REVERSE_SAFE
#define TAILQ_FOREACH_REVERSE_SAFE(var, head, headname, field, tvar)
Value:
for ((var) = TAILQ_LAST((head), headname); \
        (var) && ((tvar) = TAILQ_PREV((var), headname, field), 1); \
        (var) = (tvar))
TAILQ_FOREACH_SAFE
#define TAILQ_FOREACH_SAFE(var, head, field, tvar)
Value:
for ((var) = TAILQ_FIRST((head)); \
        (var) && ((tvar) = TAILQ_NEXT((var), field), 1); \
        (var) = (tvar))
TAILQ_HEAD
#define TAILQ_HEAD(name, type)
Value:
struct name { \
    struct type *tqh_first; /* first element */ \
    struct type **tqh_last; /* addr of last next element */ \
    TRACEBUF \
}
TAILQ_HEAD_INITIALIZER
#define TAILQ_HEAD_INITIALIZER(head) { NULL, &(head).tqh_first, TRACEBUF_INITIALIZER }
TAILQ_INIT
#define TAILQ_INIT(head)
Value:
do { \
    TAILQ_FIRST((head)) = NULL; \
    (head)->tqh_last = &TAILQ_FIRST((head)); \
    QMD_TRACE_HEAD(head); \
} while (0)
TAILQ_INSERT_AFTER
#define TAILQ_INSERT_AFTER(head, listelm, elm, field)
Value:
do { \
    QMD_TAILQ_CHECK_NEXT(listelm, field); \
    if ((TAILQ_NEXT((elm), field) = TAILQ_NEXT((listelm), field)) != NULL)\
        TAILQ_NEXT((elm), field)->field.tqe_prev = \
            &TAILQ_NEXT((elm), field); \
    else { \
        (head)->tqh_last = &TAILQ_NEXT((elm), field); \
        QMD_TRACE_HEAD(head); \
    } \
    TAILQ_NEXT((listelm), field) = (elm); \
    (elm)->field.tqe_prev = &TAILQ_NEXT((listelm), field); \
    QMD_TRACE_ELEM(&(elm)->field); \
    QMD_TRACE_ELEM(&(listelm)->field); \
} while (0)
TAILQ_INSERT_BEFORE
#define TAILQ_INSERT_BEFORE(listelm, elm, field)
Value:
do { \
    QMD_TAILQ_CHECK_PREV(listelm, field); \
    (elm)->field.tqe_prev = (listelm)->field.tqe_prev; \
    TAILQ_NEXT((elm), field) = (listelm); \
    *(listelm)->field.tqe_prev = (elm); \
    (listelm)->field.tqe_prev = &TAILQ_NEXT((elm), field); \
    QMD_TRACE_ELEM(&(elm)->field); \
    QMD_TRACE_ELEM(&(listelm)->field); \
} while (0)
TAILQ_INSERT_HEAD
#define TAILQ_INSERT_HEAD(head, elm, field)
Value:
do { \
    QMD_TAILQ_CHECK_HEAD(head, field); \
    if ((TAILQ_NEXT((elm), field) = TAILQ_FIRST((head))) != NULL) \
        TAILQ_FIRST((head))->field.tqe_prev = \
            &TAILQ_NEXT((elm), field); \
    else \
        (head)->tqh_last = &TAILQ_NEXT((elm), field); \
    TAILQ_FIRST((head)) = (elm); \
    (elm)->field.tqe_prev = &TAILQ_FIRST((head)); \
    QMD_TRACE_HEAD(head); \
    QMD_TRACE_ELEM(&(elm)->field); \
} while (0)
TAILQ_INSERT_TAIL
#define TAILQ_INSERT_TAIL(head, elm, field)
Value:
do { \
    QMD_TAILQ_CHECK_TAIL(head, field); \
    TAILQ_NEXT((elm), field) = NULL; \
    (elm)->field.tqe_prev = (head)->tqh_last; \
    *(head)->tqh_last = (elm); \
    (head)->tqh_last = &TAILQ_NEXT((elm), field); \
    QMD_TRACE_HEAD(head); \
    QMD_TRACE_ELEM(&(elm)->field); \
} while (0)
TAILQ_LAST
#define TAILQ_LAST(head, headname) (*(((struct headname *)((head)->tqh_last))->tqh_last))
TAILQ_NEXT
#define TAILQ_NEXT(elm, field) ((elm)->field.tqe_next)
TAILQ_PREV
#define TAILQ_PREV(elm, headname, field) (*(((struct headname *)((elm)->field.tqe_prev))->tqh_last))
TAILQ_REMOVE
#define TAILQ_REMOVE(head, elm, field)
Value:
do { \
    QMD_SAVELINK(oldnext, (elm)->field.tqe_next); \
    QMD_SAVELINK(oldprev, (elm)->field.tqe_prev); \
    QMD_TAILQ_CHECK_NEXT(elm, field); \
    QMD_TAILQ_CHECK_PREV(elm, field); \
    if ((TAILQ_NEXT((elm), field)) != NULL) \
        TAILQ_NEXT((elm), field)->field.tqe_prev = \
            (elm)->field.tqe_prev; \
    else { \
        (head)->tqh_last = (elm)->field.tqe_prev; \
        QMD_TRACE_HEAD(head); \
    } \
    *(elm)->field.tqe_prev = TAILQ_NEXT((elm), field); \
    TRASHIT(*oldnext); \
    TRASHIT(*oldprev); \
    QMD_TRACE_ELEM(&(elm)->field); \
} while (0)
TAILQ_SWAP
#define TAILQ_SWAP(head1, head2, type, field)
Value:
do { \
    QUEUE_TYPEOF(type) *swap_first = (head1)->tqh_first; \
    QUEUE_TYPEOF(type) **swap_last = (head1)->tqh_last; \
    (head1)->tqh_first = (head2)->tqh_first; \
    (head1)->tqh_last = (head2)->tqh_last; \
    (head2)->tqh_first = swap_first; \
    (head2)->tqh_last = swap_last; \
    if ((swap_first = (head1)->tqh_first) != NULL) \
        swap_first->field.tqe_prev = &(head1)->tqh_first; \
    else \
        (head1)->tqh_last = &(head1)->tqh_first; \
    if ((swap_first = (head2)->tqh_first) != NULL) \
        swap_first->field.tqe_prev = &(head2)->tqh_first; \
    else \
        (head2)->tqh_last = &(head2)->tqh_first; \
} while (0)
TRACEBUF
#define TRACEBUF
TRACEBUF_INITIALIZER
#define TRACEBUF_INITIALIZER
TRASHIT
#define TRASHIT(x)
WARN_UNUSED_RESULT
#define WARN_UNUSED_RESULT
WEAK
#define WEAK
WEBSOCKET_DONT_FIN
#define WEBSOCKET_DONT_FIN 0x100
Referenced by mg_send_ws_header().
WEBSOCKET_OP_BINARY
#define WEBSOCKET_OP_BINARY 2
Referenced by mg_tun_send_frame().
WEBSOCKET_OP_CLOSE
#define WEBSOCKET_OP_CLOSE 8
Referenced by mg_deliver_websocket_data(), mg_send_websocket_frame(), and mg_send_websocket_framev().
WEBSOCKET_OP_CONTINUE
#define WEBSOCKET_OP_CONTINUE 0
WEBSOCKET_OP_PING
#define WEBSOCKET_OP_PING 9
Referenced by mg_ws_handler().
WEBSOCKET_OP_PONG
#define WEBSOCKET_OP_PONG 10
WEBSOCKET_OP_TEXT
#define WEBSOCKET_OP_TEXT 1
Referenced by TBT::ev_handler_StateChange().
Typedef Documentation
cs_base64_putc_t
typedef void(* cs_base64_putc_t) (char, void *)
mg_event_handler_t
typedef void(* mg_event_handler_t) (struct mg_connection *nc, int ev, void *ev_data MG_UD_ARG(void *user_data))
mg_resolve_callback_t
typedef void(* mg_resolve_callback_t) (struct mg_dns_message *dns_message, void *user_data, enum mg_resolve_err)
Enumeration Type Documentation
mg_dns_resource_record_kind
enum mg_dns_resource_record_kind
Enumerator
MG_DNS_INVALID_RECORD
MG_DNS_QUESTION
MG_DNS_ANSWER
mg_resolve_err
enum mg_resolve_err
Enumerator
MG_RESOLVE_OK
MG_RESOLVE_NO_ANSWERS
MG_RESOLVE_EXCEEDED_RETRY_COUNT
MG_RESOLVE_TIMEOUT
Function Documentation
c_snprintf()
int c_snprintf (char * buf, size_t buf_size, const char * format, ...)
References c_strnstr(), c_vsnprintf(), mg_str::p, and WEAK.
Referenced by c_vsnprintf().
c_strnlen()
size_t c_strnlen (const char * s, size_t maxlen)
Referenced by c_vsnprintf().
c_strnstr()
const char* c_strnstr (const char * s, const char * find, size_t slen)
References cs_to_hex(), MG_MALLOC, mg_str::p, and WEAK.
Referenced by c_snprintf(), and mg_get_line_len().
c_vsnprintf()
int c_vsnprintf (char * buf, size_t buf_size, const char * format, va_list ap)
References c_itoa(), c_snprintf(), C_SNPRINTF_APPEND_CHAR, C_SNPRINTF_FLAG_ZERO, c_strnlen(), and WEAK.
Referenced by c_itoa(), and c_snprintf().
cs_base64_decode()
int cs_base64_decode (const unsigned char * s, int len, char * dst, int * dec_len)
References from_b64().
Referenced by mg_base64_decode(), and mg_parse_http_basic_auth().
cs_base64_encode()
void cs_base64_encode (const unsigned char * src, int src_len, char * dst)
References BASE64_ENCODE_BODY, and cs_fprint_base64().
Referenced by mg_base64_encode().
cs_base64_finish()
void cs_base64_finish (struct cs_base64_ctx * ctx)
References cs_base64_ctx::b64_putc, cs_base64_ctx::chunk, cs_base64_ctx::chunk_size, cs_base64_emit_chunk(), and cs_base64_ctx::user_data.
Referenced by mg_basic_auth_header(), and mg_mbuf_append_base64().
cs_base64_init()
void cs_base64_init (struct cs_base64_ctx * ctx, cs_base64_putc_t putc, void * user_data)
References cs_base64_ctx::b64_putc, cs_base64_ctx::chunk_size, and cs_base64_ctx::user_data.
Referenced by mg_basic_auth_header(), and mg_mbuf_append_base64().
cs_base64_update()
void cs_base64_update (struct cs_base64_ctx * ctx, const char * str, size_t len)
References cs_base64_ctx::chunk, cs_base64_ctx::chunk_size, and cs_base64_emit_chunk().
Referenced by mg_basic_auth_header(), and mg_mbuf_append_base64().
cs_fprint_base64()
void cs_fprint_base64 (FILE * f, const unsigned char * src, int src_len)
Referenced by cs_base64_encode().
cs_from_hex()
void cs_from_hex (char * to, const char * p, size_t len)
References fourbit(), mg_str::len, and WEAK.
Referenced by fourbit().
cs_hmac_sha1()
void cs_hmac_sha1 (const unsigned char * key, size_t key_len, const unsigned char * text, size_t text_len, unsigned char out[20])
References cs_sha1_final(), cs_sha1_init(), cs_sha1_update(), mbuf_init(), and WEAK.
cs_md5_final()
void cs_md5_final (unsigned char * md, cs_md5_ctx * c)
cs_md5_init()
void cs_md5_init (cs_md5_ctx * c)
References cs_md5_ctx::bits, and cs_md5_ctx::buf.
Referenced by mg_parse_http_basic_auth().
cs_md5_update()
void cs_md5_update (cs_md5_ctx * c, const unsigned char * data, size_t len)
References cs_md5_ctx::bits, cs_md5_ctx::buf, byteReverse(), cs_md5_transform(), and cs_md5_ctx::in.
Referenced by mg_parse_http_basic_auth().
cs_sha1_final()
void cs_sha1_final (unsigned char digest[20], cs_sha1_ctx *)
References char64long16::c, cs_sha1_ctx::count, cs_sha1_update(), and cs_sha1_ctx::state.
Referenced by cs_hmac_sha1(), and mg_hash_sha1_v().
cs_sha1_init()
void cs_sha1_init (cs_sha1_ctx *)
References cs_sha1_ctx::count, and cs_sha1_ctx::state.
Referenced by cs_hmac_sha1(), and mg_hash_sha1_v().
cs_sha1_update()
void cs_sha1_update (cs_sha1_ctx * , const unsigned char * data, uint32_t len)
References cs_sha1_ctx::buffer, cs_sha1_ctx::count, cs_sha1_transform(), and cs_sha1_ctx::state.
Referenced by cs_hmac_sha1(), cs_sha1_final(), and mg_hash_sha1_v().
cs_time()
double cs_time (void)
Referenced by cs_log_set_level(), mg_time(), and mg_tun_if_poll().
cs_timegm()
double cs_timegm (const struct tm * tm)
cs_to_hex()
void cs_to_hex (char * to, const unsigned char * p, size_t len)
Referenced by c_strnstr(), and mg_parse_http_basic_auth().
mbuf_append()
size_t mbuf_append (struct mbuf * , const void * data, size_t data_size)
References mbuf::len, mbuf_insert(), mbuf_remove(), and WEAK.
Referenced by mbuf_insert(), mg_assemble_uri(), mg_basic_auth_header(), mg_dns_copy_questions(), mg_dns_encode_name(), mg_dns_encode_record(), mg_mbuf_append_base64_putc(), mg_recv_common(), mg_set_nameserver(), mg_socket_if_tcp_send(), mg_socket_if_udp_send(), and mg_url_encode().
mbuf_free()
void mbuf_free (struct mbuf *)
References mbuf::buf, MBUF_FREE, mbuf_init(), mbuf_resize(), and WEAK.
Referenced by mbuf_init(), mg_assemble_uri(), mg_connect_http_opt(), mg_destroy_conn(), mg_recv_common(), mg_send_dns_query(), mg_send_websocket_handshake3v(), and mg_set_nameserver().
mbuf_init()
void mbuf_init (struct mbuf * , size_t initial_capacity)
References mbuf::buf, mbuf::len, mbuf_free(), mbuf_resize(), mbuf::size, and WEAK.
Referenced by cs_hmac_sha1(), mbuf_free(), mg_assemble_uri(), mg_connect_http_opt(), mg_send_dns_query(), mg_send_websocket_handshake3v(), mg_set_nameserver(), and mg_url_encode().
mbuf_insert()
size_t mbuf_insert (struct mbuf * , size_t , const void * , size_t)
References mbuf::buf, mbuf::len, mbuf_append(), MBUF_REALLOC, MBUF_SIZE_MULTIPLIER, mbuf::size, and WEAK.
Referenced by dns_handler(), mbuf_append(), mbuf_trim(), mg_dns_insert_header(), mg_mqtt_prepend_header(), mg_send_dns_query(), and mg_set_protocol_dns().
mbuf_remove()
void mbuf_remove (struct mbuf * , size_t data_size)
References mbuf::buf, mbuf::len, mg_ncasecmp(), and WEAK.
Referenced by dns_handler(), mbuf_append(), mg_deliver_websocket_data(), mg_forward(), mg_get_http_header(), mg_get_line_len(), mg_http_handler(), mg_if_sent_cb(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_set_nameserver(), mg_tun_send_frame(), and mqtt_handler().
mbuf_resize()
void mbuf_resize (struct mbuf * , size_t new_size)
References mbuf::buf, mbuf::len, MBUF_REALLOC, mbuf_trim(), mbuf::size, and WEAK.
Referenced by mbuf_free(), mbuf_init(), and mbuf_trim().
mbuf_trim()
void mbuf_trim (struct mbuf *)
References mbuf::len, mbuf_insert(), mbuf_resize(), and WEAK.
Referenced by mbuf_resize(), mg_if_sent_cb(), and mg_url_encode().
mg_add_sock()
struct mg_connection* mg_add_sock (struct mg_mgr * mgr, sock_t sock, MG_CB(mg_event_handler_t handler, void *user_data))
mg_add_sock_opt()
struct mg_connection* mg_add_sock_opt (struct mg_mgr * mgr, sock_t sock, MG_CB(mg_event_handler_t handler, void *user_data) , struct mg_add_sock_opts opts)
mg_asprintf()
int mg_asprintf (char ** buf, size_t size, const char * fmt, ...)
References mg_avprintf(), and WEAK.
Referenced by mg_casecmp(), mg_connect_http_base(), mg_http_send_redirect(), mg_mqtt_disconnect(), mg_parse_http_basic_auth(), and mg_tun_send_frame().
mg_assemble_uri()
int mg_assemble_uri (const struct mg_str * scheme, const struct mg_str * user_info, const struct mg_str * host, unsigned int port, const struct mg_str * path, const struct mg_str * query, const struct mg_str * fragment, int normalize_path, struct mg_str * uri)
References mbuf::buf, mg_str::len, mbuf::len, mbuf_append(), mbuf_free(), mbuf_init(), mg_normalize_uri_path(), mg_strdup(), and mg_str::p.
mg_avprintf()
int mg_avprintf (char ** buf, size_t size, const char * fmt, va_list ap)
References mg_str::len, MG_FREE, and MG_MALLOC.
Referenced by mg_asprintf(), mg_printf_html_escape(), mg_printf_http_chunk(), mg_printf_websocket_frame(), and mg_vprintf().
mg_base64_decode()
int mg_base64_decode (const unsigned char * s, int len, char * dst)
References cs_base64_decode().
mg_base64_encode()
void mg_base64_encode (const unsigned char * src, int src_len, char * dst)
References cs_base64_encode().
Referenced by mg_send_websocket_handshake3v(), and mg_ws_handshake().
mg_basic_auth_header()
void mg_basic_auth_header (const struct mg_str user, const struct mg_str pass, struct mbuf * buf)
References cs_base64_finish(), cs_base64_init(), cs_base64_update(), mg_str::len, mbuf_append(), mg_mbuf_append_base64_putc(), and mg_str::p.
Referenced by mg_connect_http_opt(), and mg_send_websocket_handshake3v().
mg_bind()
struct mg_connection* mg_bind (struct mg_mgr * mgr, const char * address, MG_CB(mg_event_handler_t handler, void *user_data))
mg_bind_opt()
struct mg_connection* mg_bind_opt (struct mg_mgr * mgr, const char * address, MG_CB(mg_event_handler_t handler, void *user_data) , struct mg_bind_opts opts)
mg_casecmp()
int mg_casecmp (const char * s1, const char * s2)
References mg_asprintf(), mg_ncasecmp(), and WEAK.
Referenced by mg_http_conn_destructor(), and mg_ncasecmp().
mg_check_digest_auth()
int mg_check_digest_auth (struct mg_str method, struct mg_str uri, struct mg_str username, struct mg_str cnonce, struct mg_str response, struct mg_str qop, struct mg_str nc, struct mg_str nonce, struct mg_str auth_domain, FILE * fp)
Referenced by mg_parse_http_basic_auth().
mg_check_ip_acl()
int mg_check_ip_acl (const char * acl, uint32_t remote_ip)
References DBG, mg_next_comma_list_entry(), mg_str::p, and parse_net().
Referenced by mg_parse_http_basic_auth().
mg_conn_addr_to_str()
int mg_conn_addr_to_str (struct mg_connection * c, char * buf, size_t len, int flags)
References MAX, mg_conn_addr_to_str(), MG_EV_ACCEPT, MG_EV_CLOSE, MG_EV_CONNECT, MG_EV_RECV, MG_EV_SEND, mg_if_get_conn_addr(), mg_sock_addr_to_str(), MG_SOCK_STRINGIFY_IP, MG_SOCK_STRINGIFY_PORT, MG_SOCK_STRINGIFY_REMOTE, and mg_time().
Referenced by mg_conn_addr_to_str(), mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_connect()
struct mg_connection* mg_connect (struct mg_mgr * mgr, const char * address, MG_CB(mg_event_handler_t handler, void *user_data))
mg_connect_http()
struct mg_connection* mg_connect_http (struct mg_mgr * mgr, MG_CB(mg_event_handler_t event_handler, void *user_data) , const char * url, const char * extra_headers, const char * post_data)
mg_connect_http_opt()
struct mg_connection* mg_connect_http_opt (struct mg_mgr * mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data) , struct mg_connect_opts opts, const char * url, const char * extra_headers, const char * post_data)
References mbuf::buf, mg_str::len, mbuf::len, mbuf_free(), mbuf_init(), mg_basic_auth_header(), MG_CB, mg_connect_http_base(), mg_mk_str(), MG_NULL_STR, mg_printf(), and mg_str::p.
Referenced by mg_connect_http().
mg_connect_opt()
struct mg_connection* mg_connect_opt (struct mg_mgr * mgr, const char * address, MG_CB(mg_event_handler_t handler, void *user_data) , struct mg_connect_opts opts)
mg_connect_ws()
struct mg_connection* mg_connect_ws (struct mg_mgr * mgr, MG_CB(mg_event_handler_t event_handler, void *user_data) , const char * url, const char * protocol, const char * extra_headers)
mg_connect_ws_opt()
struct mg_connection* mg_connect_ws_opt (struct mg_mgr * mgr, MG_CB(mg_event_handler_t ev_handler, void *user_data) , struct mg_connect_opts opts, const char * url, const char * protocol, const char * extra_headers)
References MG_CB, mg_connect_http_base(), mg_mk_str(), MG_NULL_STR, and mg_send_websocket_handshake3v().
Referenced by mg_connect_ws(), and mg_tun_do_reconnect().
mg_dns_copy_questions()
int mg_dns_copy_questions (struct mbuf * io, struct mg_dns_message * msg)
References mg_str::len, mbuf_append(), mg_dns_resource_record::name, mg_dns_message::num_questions, mg_str::p, mg_dns_message::pkt, and mg_dns_message::questions.
Referenced by mg_set_protocol_dns().
mg_dns_encode_name()
int mg_dns_encode_name (struct mbuf * io, const char * name, size_t len)
References mbuf::len, mbuf_append(), and mg_dns_resource_record::name.
Referenced by mg_dns_encode_record().
mg_dns_encode_record()
int mg_dns_encode_record (struct mbuf * io, struct mg_dns_resource_record * rr, const char * name, size_t nlen, const void * rdata, size_t rlen)
References mbuf::buf, mg_dns_resource_record::kind, mbuf::len, mbuf_append(), MG_DNS_ANSWER, MG_DNS_CNAME_RECORD, mg_dns_encode_name(), MG_DNS_INVALID_RECORD, mg_dns_resource_record::rclass, mg_dns_resource_record::rtype, and mg_dns_resource_record::ttl.
Referenced by mg_send_dns_query(), and mg_set_protocol_dns().
mg_dns_insert_header()
int mg_dns_insert_header (struct mbuf * io, size_t pos, struct mg_dns_message * msg)
References mg_dns_message::flags, mg_dns_header::flags, mbuf_insert(), mg_dns_message::num_answers, mg_dns_header::num_answers, mg_dns_message::num_questions, mg_dns_header::num_questions, mg_dns_message::transaction_id, and mg_dns_header::transaction_id.
Referenced by dns_handler(), mg_send_dns_query(), and mg_set_protocol_dns().
mg_dns_next_record()
struct mg_dns_resource_record* mg_dns_next_record (struct mg_dns_message * msg, int query, struct mg_dns_resource_record * prev)
References mg_dns_message::answers, mg_dns_message::num_answers, and mg_dns_resource_record::rtype.
mg_dns_parse_record_data()
int mg_dns_parse_record_data (struct mg_dns_message * msg, struct mg_dns_resource_record * rr, void * data, size_t data_len)
References mg_str::len, MG_DNS_A_RECORD, MG_DNS_AAAA_RECORD, MG_DNS_CNAME_RECORD, mg_dns_uncompress_name(), mg_str::p, mg_dns_message::pkt, mg_dns_resource_record::rdata, and mg_dns_resource_record::rtype.
Referenced by resolve_cb().
mg_dns_uncompress_name()
size_t mg_dns_uncompress_name (struct mg_dns_message * msg, struct mg_str * name, char * dst, int dst_len)
References mg_str::len, mg_str::p, and mg_dns_message::pkt.
Referenced by mg_dns_parse_record_data(), and mg_set_protocol_dns().
mg_find_iface()
struct mg_iface* mg_find_iface (struct mg_mgr * mgr, const struct mg_iface_vtable * vtable, struct mg_iface * from)
References mg_mgr::ifaces, mg_open_listening_socket(), mg_mgr::num_ifaces, and mg_iface::vtable.
Referenced by mg_tun_create_client().
mg_get_http_basic_auth()
int mg_get_http_basic_auth (struct http_message * hm, char * user, size_t user_len, char * pass, size_t pass_len)
References mg_get_http_header(), and mg_parse_http_basic_auth().
mg_get_http_header()
struct mg_str* mg_get_http_header (struct http_message * hm, const char * name)
References mbuf::buf, DATA_FILE, DBG, mg_connection::flags, http_message::header_names, http_message::header_values, mg_str::len, mbuf::len, LL_DEBUG, LOG, mbuf_remove(), MG_F_SEND_AND_CLOSE, mg_forward(), mg_http_get_proto_data(), MG_MAX_HTTP_SEND_MBUF, mg_ncasecmp(), mg_send(), mg_str::p, mg_connection::recv_mbuf, and mg_connection::send_mbuf.
Referenced by mg_get_http_basic_auth(), mg_get_line_len(), mg_http_handler(), mg_http_send_error(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), and mg_ws_handshake().
mg_get_http_var()
int mg_get_http_var (const struct mg_str * buf, const char * name, char * dst, size_t dst_len)
References mg_str::len, mg_ncasecmp(), mg_url_decode(), and mg_str::p.
mg_hash_md5_v()
void mg_hash_md5_v (size_t num_msgs, const uint8_t * msgs[], const size_t * msg_lens, uint8_t * digest)
Referenced by mg_parse_http_basic_auth().
mg_hash_sha1_v()
void mg_hash_sha1_v (size_t num_msgs, const uint8_t * msgs[], const size_t * msg_lens, uint8_t * digest)
References cs_sha1_final(), cs_sha1_init(), cs_sha1_update(), and mg_hash_sha1_v().
Referenced by mg_hash_sha1_v(), and mg_ws_handshake().
mg_http_check_digest_auth()
int mg_http_check_digest_auth (struct http_message * hm, const char * auth_domain, FILE * fp)
Referenced by mg_parse_http_basic_auth().
mg_http_create_digest_auth_header()
int mg_http_create_digest_auth_header (char * buf, size_t buf_len, const char * method, const char * uri, const char * auth_domain, const char * user, const char * passwd)
Referenced by mg_parse_http_basic_auth().
mg_http_parse_header()
int mg_http_parse_header (struct mg_str * hdr, const char * var_name, char * buf, size_t buf_size)
References mg_str::len, and mg_str::p.
Referenced by mg_get_line_len(), mg_parse_http_basic_auth(), and mg_parse_multipart().
mg_http_send_error()
void mg_http_send_error (struct mg_connection * nc, int code, const char * reason)
References DATA_FILE, mg_connection::flags, mg_str::len, LL_DEBUG, LOG, MG_F_SEND_AND_CLOSE, MG_FREE, mg_get_errno(), mg_get_http_header(), mg_http_get_proto_data(), mg_http_send_error(), MG_MALLOC, mg_match_prefix(), mg_mk_str(), mg_printf(), mg_send(), mg_send_head(), mg_send_response_line_s(), mg_status_message(), mg_time(), mg_vcasecmp(), mg_vcmp(), mg_str::p, and http_message::proto.
Referenced by mg_http_send_error(), mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_http_send_redirect()
void mg_http_send_redirect (struct mg_connection * nc, int status_code, const struct mg_str location, const struct mg_str extra_headers)
References mg_str::len, mg_asprintf(), MG_FREE, mg_send(), mg_send_response_line(), and mg_str::p.
mg_if_accept_new_conn()
struct mg_connection* mg_if_accept_new_conn (struct mg_connection * lc)
References DBG, mg_connection::flags, mg_connection::handler, mg_connection::iface, mg_connection::listener, mg_add_conn(), mg_create_connection(), MG_F_SSL, mg_connection::mgr, mg_connection::proto_handler, mg_connection::recv_mbuf_limit, mg_connection::sock, and mg_connection::user_data.
Referenced by mg_accept_conn(), and mg_tun_if_find_conn().
mg_if_accept_tcp_cb()
void mg_if_accept_tcp_cb (struct mg_connection * nc, union socket_address * sa, size_t sa_len)
References mg_call(), MG_EV_ACCEPT, mg_connection::sa, and mg_connection::user_data.
Referenced by mg_accept_conn(), and mg_handle_udp_read().
mg_if_connect_cb()
void mg_if_connect_cb (struct mg_connection * nc, int err)
References DBG, mg_connection::flags, mg_call(), MG_EV_CONNECT, MG_F_CLOSE_IMMEDIATELY, MG_F_CONNECTING, and mg_connection::user_data.
Referenced by mg_handle_udp_read(), and mg_mgr_handle_conn().
mg_if_create_iface()
struct mg_iface* mg_if_create_iface (const struct mg_iface_vtable * vtable, struct mg_mgr * mgr)
References mg_iface::data, MG_CALLOC, mg_iface::mgr, and mg_iface::vtable.
Referenced by mg_mgr_init_opt().
mg_if_poll()
void mg_if_poll (struct mg_connection * nc, time_t now)
References mg_connection::flags, mg_call(), MG_EV_POLL, MG_F_SSL, MG_F_SSL_HANDSHAKE_DONE, and mg_connection::user_data.
Referenced by mg_mgr_handle_conn().
mg_if_recv_tcp_cb()
void mg_if_recv_tcp_cb (struct mg_connection * nc, void * buf, int len, int own)
References mg_recv_common().
Referenced by mg_handle_tcp_read(), and mg_tun_client_handler().
mg_if_recv_udp_cb()
void mg_if_recv_udp_cb (struct mg_connection * nc, void * buf, int len, union socket_address * sa, size_t sa_len)
References DBG, mg_connection::flags, mg_connection::handler, mg_connection::iface, mg_connection::listener, mg_add_conn(), mg_call(), mg_create_connection_base(), MG_EV_ACCEPT, MG_F_LISTENING, MG_F_SEND_AND_CLOSE, MG_F_UDP, MG_FREE, mg_next(), mg_recv_common(), mg_connection::mgr, mg_connection::proto_handler, mg_connection::recv_mbuf_limit, mg_iface_vtable::recved, socket_address::sa, mg_connection::sa, mg_connection::sock, mg_connection::user_data, and mg_iface::vtable.
Referenced by mg_handle_udp_read().
mg_if_sent_cb()
void mg_if_sent_cb (struct mg_connection * nc, int num_sent)
References mbuf::buf, DBG, mg_connection::flags, mbuf_remove(), mbuf_trim(), mg_call(), MG_EV_SEND, MG_F_CLOSE_IMMEDIATELY, mg_connection::mgr, mg_connection::send_mbuf, and mg_connection::user_data.
Referenced by mg_write_to_socket().
mg_if_timer()
void mg_if_timer (struct mg_connection * c, double now)
References mg_connection::ev_timer_time, mg_call(), MG_EV_TIMER, and mg_connection::user_data.
Referenced by mg_mgr_handle_conn().
mg_is_big_endian()
int mg_is_big_endian (void)
mg_match_prefix()
int mg_match_prefix (const char * pattern, int pattern_len, const char * str)
References mg_str::len, and mg_match_prefix_n().
Referenced by mg_http_send_error(), mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_match_prefix_n()
int mg_match_prefix_n (const struct mg_str pattern, const struct mg_str str)
References mg_str::len, mg_match_prefix_n(), mg_str::p, and str_util_lowercase().
Referenced by mg_http_get_endpoint_handler(), mg_match_prefix(), mg_match_prefix_n(), and mg_parse_http_basic_auth().
mg_mbuf_append_base64()
void mg_mbuf_append_base64 (struct mbuf * mbuf, const void * data, size_t len)
References cs_base64_finish(), cs_base64_init(), cs_base64_update(), and mg_mbuf_append_base64_putc().
mg_mbuf_append_base64_putc()
void mg_mbuf_append_base64_putc (char ch, void * user_data)
References mbuf_append().
Referenced by mg_basic_auth_header(), and mg_mbuf_append_base64().
mg_mgr_free()
void mg_mgr_free (struct mg_mgr *)
References mg_mgr::active_connections, DBG, mg_iface_vtable::free, mg_mgr::ifaces, mg_close_conn(), MG_FREE, mg_mgr_poll(), mg_mgr::nameserver, mg_connection::next, mg_mgr::num_ifaces, and mg_iface::vtable.
Referenced by TBT::WSClientInterface::threadFunc().
mg_mgr_init()
void mg_mgr_init (struct mg_mgr * mgr, void * user_data)
References mg_mgr_init_opt().
Referenced by TBT::WSClientInterface::threadFunc().
mg_mgr_init_opt()
void mg_mgr_init_opt (struct mg_mgr * mgr, void * user_data, struct mg_mgr_init_opts opts)
References DBG, mg_mgr::ifaces, mg_mgr_init_opts::ifaces, mg_iface_vtable::init, mg_mgr_init_opts::main_iface, mg_if_create_iface(), mg_ifaces, MG_MAIN_IFACE, MG_MALLOC, mg_num_ifaces, mg_mgr::nameserver, mg_mgr_init_opts::nameserver, mg_mgr::num_ifaces, mg_mgr_init_opts::num_ifaces, mg_mgr::user_data, and mg_iface::vtable.
Referenced by mg_mgr_init().
mg_mgr_poll()
time_t mg_mgr_poll (struct mg_mgr * , int milli)
References mg_mgr::ifaces, LL_ERROR, LOG, mg_mgr::num_ifaces, mg_iface_vtable::poll, and mg_iface::vtable.
Referenced by mg_mgr_free(), and TBT::WSClientInterface::threadFunc().
mg_mk_str()
struct mg_str mg_mk_str (const char * s)
References mg_str::len.
Referenced by mg_bind_opt(), mg_connect_http_base(), mg_connect_http_opt(), mg_connect_ws_opt(), mg_http_send_error(), mg_mqtt_vmatch_topic_expression(), mg_next_comma_list_entry(), mg_next_comma_list_entry_n(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_register_http_endpoint_opt(), mg_send_response_line(), mg_send_websocket_handshake(), and mg_send_websocket_handshake3().
mg_mk_str_n()
struct mg_str mg_mk_str_n (const char * s, size_t len)
References mg_vcmp(), and WEAK.
Referenced by mg_next_comma_list_entry_n(), and mg_url_encode().
mg_mqtt_connack()
void mg_mqtt_connack (struct mg_connection * nc, uint8_t return_code)
References MG_MQTT_CMD_CONNACK, mg_mqtt_prepend_header(), and mg_send().
Referenced by mg_mqtt_disconnect().
mg_mqtt_disconnect()
void mg_mqtt_disconnect (struct mg_connection * nc)
References mg_connection::flags, mg_str::len, LIST_FIRST, LIST_INIT, LIST_INSERT_HEAD, LIST_NEXT, LIST_REMOVE, mg_connection::listener, mg_mqtt_message::message_id, mg_asprintf(), MG_CALLOC, MG_EV_ACCEPT, MG_EV_CLOSE, MG_EV_MQTT_CONNACK_ACCEPTED, MG_EV_MQTT_CONNACK_SERVER_UNAVAILABLE, MG_EV_MQTT_CONNECT, MG_EV_MQTT_PUBLISH, MG_EV_MQTT_SUBSCRIBE, MG_F_CLOSE_IMMEDIATELY, MG_FREE, MG_MALLOC, MG_MQTT_CMD_DISCONNECT, mg_mqtt_connack(), mg_mqtt_next_subscribe_topic(), mg_mqtt_prepend_header(), mg_mqtt_publish(), mg_mqtt_suback(), mg_mqtt_vmatch_topic_expression(), MG_REALLOC, mg_set_protocol_mqtt(), mg_str::p, mg_mqtt_message::payload, mg_connection::proto_data, mg_mqtt_topic_expression::qos, mg_mqtt_message::topic, mg_mqtt_topic_expression::topic, and mg_connection::user_data.
mg_mqtt_match_topic_expression()
int mg_mqtt_match_topic_expression (struct mg_str exp, struct mg_str topic)
References mg_str::len, and mg_str::p.
Referenced by mg_mqtt_vmatch_topic_expression().
mg_mqtt_next_subscribe_topic()
int mg_mqtt_next_subscribe_topic (struct mg_mqtt_message * msg, struct mg_str * topic, uint8_t * qos, int pos)
References mg_str::len, mg_str::p, and mg_mqtt_message::payload.
Referenced by mg_mqtt_disconnect().
mg_mqtt_ping()
void mg_mqtt_ping (struct mg_connection * nc)
References MG_MQTT_CMD_PINGREQ, and mg_mqtt_prepend_header().
Referenced by mqtt_handler().
mg_mqtt_pong()
void mg_mqtt_pong (struct mg_connection * nc)
References MG_MQTT_CMD_PINGRESP, and mg_mqtt_prepend_header().
mg_mqtt_puback()
void mg_mqtt_puback (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_PUBACK, and mg_send_mqtt_short_command().
mg_mqtt_pubcomp()
void mg_mqtt_pubcomp (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_PUBCOMP, and mg_send_mqtt_short_command().
mg_mqtt_publish()
void mg_mqtt_publish (struct mg_connection * nc, const char * topic, uint16_t message_id, int flags, const void * data, size_t len)
References mbuf::len, MG_MQTT_CMD_PUBLISH, MG_MQTT_GET_QOS, mg_mqtt_prepend_header(), mg_send(), and mg_connection::send_mbuf.
Referenced by mg_mqtt_disconnect().
mg_mqtt_pubrec()
void mg_mqtt_pubrec (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_PUBREC, and mg_send_mqtt_short_command().
mg_mqtt_pubrel()
void mg_mqtt_pubrel (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_PUBREL, and mg_send_mqtt_short_command().
mg_mqtt_suback()
void mg_mqtt_suback (struct mg_connection * nc, uint8_t * qoss, size_t qoss_len, uint16_t message_id)
References MG_MQTT_CMD_SUBACK, mg_mqtt_prepend_header(), MG_MQTT_QOS, and mg_send().
Referenced by mg_mqtt_disconnect().
mg_mqtt_subscribe()
void mg_mqtt_subscribe (struct mg_connection * nc, const struct mg_mqtt_topic_expression * topics, size_t topics_len, uint16_t message_id)
References mbuf::len, MG_MQTT_CMD_SUBSCRIBE, mg_mqtt_prepend_header(), MG_MQTT_QOS, mg_send(), and mg_connection::send_mbuf.
mg_mqtt_unsuback()
void mg_mqtt_unsuback (struct mg_connection * nc, uint16_t message_id)
References MG_MQTT_CMD_UNSUBACK, and mg_send_mqtt_short_command().
mg_mqtt_unsubscribe()
void mg_mqtt_unsubscribe (struct mg_connection * nc, char ** topics, size_t topics_len, uint16_t message_id)
References mbuf::len, MG_MQTT_CMD_UNSUBSCRIBE, mg_mqtt_prepend_header(), MG_MQTT_QOS, mg_send(), and mg_connection::send_mbuf.
mg_mqtt_vmatch_topic_expression()
int mg_mqtt_vmatch_topic_expression (const char * exp, struct mg_str topic)
References mg_mk_str(), and mg_mqtt_match_topic_expression().
Referenced by mg_mqtt_disconnect().
mg_ncasecmp()
int mg_ncasecmp (const char * s1, const char * s2, size_t len)
References mg_casecmp(), str_util_lowercase(), and WEAK.
Referenced by mbuf_remove(), mg_casecmp(), mg_get_http_header(), mg_get_http_var(), mg_get_line_len(), mg_http_parse_headers(), mg_parse_address(), mg_parse_http_basic_auth(), mg_parse_multipart(), mg_vcasecmp(), and str_util_lowercase().
mg_next()
struct mg_connection* mg_next (struct mg_mgr * mgr, struct mg_connection * c)
References mg_mgr::active_connections, ctl_msg::callback, ctl_msg::message, MG_RECV_FUNC, MG_SEND_FUNC, and mg_connection::next.
Referenced by mg_if_recv_udp_cb(), and mg_mgr_handle_conn().
mg_next_comma_list_entry()
const char* mg_next_comma_list_entry (const char * list, struct mg_str * val, struct mg_str * eq_val)
References mg_mk_str(), mg_next_comma_list_entry_n(), and mg_str::p.
Referenced by mg_check_ip_acl(), mg_http_conn_destructor(), and mg_parse_http_basic_auth().
mg_next_comma_list_entry_n()
struct mg_str mg_next_comma_list_entry_n (struct mg_str list, struct mg_str * val, struct mg_str * eq_val)
References mg_str::len, mg_mk_str(), mg_mk_str_n(), mg_strchr(), and mg_str::p.
Referenced by mg_next_comma_list_entry().
mg_normalize_uri_path()
int mg_normalize_uri_path (const struct mg_str * in, struct mg_str * out)
References mg_str::len, mg_vcmp(), mg_str::p, and parse_uri_component().
Referenced by mg_assemble_uri(), and mg_parse_http_basic_auth().
mg_parse_dns()
int mg_parse_dns (const char * buf, int len, struct mg_dns_message * msg)
References mg_dns_message::answers, ARRAY_SIZE, mg_dns_message::flags, mg_dns_header::flags, mg_str::len, mg_parse_dns_resource_record(), mg_dns_message::num_answers, mg_dns_header::num_answers, mg_dns_message::num_questions, mg_dns_header::num_questions, mg_str::p, mg_dns_message::pkt, mg_dns_message::questions, mg_dns_message::transaction_id, and mg_dns_header::transaction_id.
Referenced by dns_handler(), and mg_resolve_async_eh().
mg_parse_http()
int mg_parse_http (const char * s, int n, struct http_message * hm, int is_req)
References http_message::body, mg_str::len, http_message::message, http_message::method, mg_http_get_request_len(), mg_http_parse_headers(), mg_skip(), mg_vcasecmp(), mg_str::p, http_message::proto, http_message::query_string, http_message::resp_code, http_message::resp_status_msg, and http_message::uri.
Referenced by mg_http_handler().
mg_parse_http_basic_auth()
int mg_parse_http_basic_auth (struct mg_str * hdr, char * user, size_t user_len, char * pass, size_t pass_len)
References ARRAY_SIZE, http_message::body, cs_base64_decode(), cs_md5_final(), cs_md5_init(), cs_md5_update(), cs_to_hex(), mg_http_multipart_part::data, DBG, mg_connect_opts::error_string, mg_http_multipart_part::file_name, mg_connection::flags, http_message::header_names, http_message::header_values, mg_str::len, mg_reverse_proxy_data::linked_conn, LL_DEBUG, LL_ERROR, LOG, http_message::message, http_message::method, mg_asprintf(), MG_CALLOC, MG_CB, mg_check_digest_auth(), mg_check_ip_acl(), mg_conn_addr_to_str(), mg_connect_http_base(), MG_ENABLE_HTTP_WEBDAV, MG_EV_CLOSE, MG_EV_CONNECT, MG_EV_HTTP_REPLY, MG_F_CLOSE_IMMEDIATELY, MG_F_SEND_AND_CLOSE, MG_FREE, mg_get_errno(), mg_get_http_header(), mg_hash_md5_v(), mg_http_check_digest_auth(), mg_http_create_digest_auth_header(), mg_http_get_proto_data(), mg_http_parse_header(), mg_http_send_error(), MG_INTERNAL, MG_MALLOC, mg_match_prefix(), mg_match_prefix_n(), MG_MAX_HTTP_HEADERS, MG_MAX_PATH, mg_mk_str(), MG_MK_STR, mg_ncasecmp(), mg_next_comma_list_entry(), mg_normalize_uri_path(), MG_NULL_STR, mg_printf(), mg_printf_http_chunk(), MG_REALLOC, mg_send(), mg_send_http_chunk(), mg_send_response_line(), MG_SOCK_STRINGIFY_PORT, mg_strncmp(), mg_time(), MG_UD_ARG, mg_url_decode(), mg_url_encode(), mg_vcasecmp(), mg_vcmp(), mg_connection::mgr, mg_str::p, parse_uri_component(), http_message::proto, http_message::query_string, mg_http_proto_data::reverse_proxy_data, mg_connection::sa, socket_address::sin, mg_http_multipart_part::status, http_message::uri, and mg_http_multipart_part::user_data.
Referenced by mg_get_http_basic_auth().
mg_parse_multipart()
size_t mg_parse_multipart (const char * buf, size_t buf_len, char * var_name, size_t var_name_len, char * file_name, size_t file_name_len, const char ** chunk, size_t * chunk_len)
References mg_str::len, mg_get_line_len(), mg_http_get_request_len(), mg_http_parse_header(), mg_ncasecmp(), and mg_str::p.
mg_parse_uri()
int mg_parse_uri (const struct mg_str uri, struct mg_str * scheme, struct mg_str * user_info, struct mg_str * host, unsigned int * port, struct mg_str * path, struct mg_str * query, struct mg_str * fragment)
References mg_str::len, mg_str::p, and parse_uri_component().
Referenced by mg_connect_http_base().
mg_printf()
int mg_printf (struct mg_connection * , const char * fmt, ...)
References DBG, mg_get_errno(), and mg_vprintf().
Referenced by mg_connect_http_opt(), mg_http_send_error(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), mg_send_head(), mg_send_response_line_s(), mg_send_websocket_handshake3v(), and mg_ws_handshake().
mg_printf_html_escape()
void mg_printf_html_escape (struct mg_connection * nc, const char * fmt, ...)
References mg_str::len, mg_avprintf(), MG_FREE, mg_send(), and MG_VPRINTF_BUFFER_SIZE.
mg_printf_http_chunk()
void mg_printf_http_chunk (struct mg_connection * nc, const char * fmt, ...)
References mg_str::len, mg_avprintf(), MG_FREE, mg_send_http_chunk(), and MG_VPRINTF_BUFFER_SIZE.
Referenced by mg_parse_http_basic_auth().
mg_printf_websocket_frame()
void mg_printf_websocket_frame (struct mg_connection * nc, int op_and_flags, const char * fmt, ...)
References mg_avprintf(), MG_FREE, mg_send_websocket_frame(), and MG_VPRINTF_BUFFER_SIZE.
mg_register_http_endpoint()
void mg_register_http_endpoint (struct mg_connection * nc, const char * uri_path, MG_CB(mg_event_handler_t handler, void *user_data))
References mg_ssi_call_ctx::arg, ARRAY_SIZE, blk, http_message::body, mbuf::buf, DATA_PUT, DBG, mg_ssi_call_ctx::file, mg_connection::flags, http_message::header_names, http_message::header_values, mg_str::len, mbuf::len, mbuf_remove(), http_message::message, http_message::method, mg_add_sock(), mg_call(), MG_CGI_ENVIRONMENT_SIZE, mg_conn_addr_to_str(), MG_EV_CLOSE, MG_EV_RECV, MG_EV_SSI_CALL, MG_EV_SSI_CALL_CTX, MG_F_CLOSE_IMMEDIATELY, MG_F_SEND_AND_CLOSE, MG_F_SSL, mg_forward(), MG_FREE, mg_get_errno(), mg_get_http_header(), mg_http_get_proto_data(), mg_http_get_request_len(), mg_http_parse_headers(), mg_http_send_error(), MG_INTERNAL, MG_MALLOC, mg_match_prefix(), MG_MAX_HTTP_REQUEST_SIZE, MG_MAX_PATH, mg_mk_str(), MG_MK_STR, mg_printf(), mg_register_http_endpoint_opt(), mg_send(), mg_send_response_line(), mg_set_close_on_exec(), MG_SOCK_STRINGIFY_IP, MG_SOCK_STRINGIFY_PORT, MG_SOCK_STRINGIFY_REMOTE, mg_sock_to_str(), mg_socketpair(), mg_time(), MG_UD_ARG, mg_url_encode(), mg_vcmp(), MG_VERSION, mg_connection::mgr, mg_str::p, http_message::query_string, mg_connection::recv_mbuf, mg_ssi_call_ctx::req, mg_connection::sock, http_message::uri, mg_connection::user_data, and mg_http_endpoint_opts::user_data.
mg_register_http_endpoint_opt()
void mg_register_http_endpoint_opt (struct mg_connection * nc, const char * uri_path, mg_event_handler_t handler, struct mg_http_endpoint_opts opts)
References mg_http_endpoint_opts::auth_domain, mg_http_endpoint::auth_domain, mg_http_endpoint_opts::auth_file, mg_http_endpoint::auth_file, mg_http_proto_data::endpoints, mg_http_endpoint::handler, MG_CALLOC, mg_http_get_proto_data(), mg_mk_str(), mg_strdup(), mg_http_endpoint::next, mg_http_endpoint::uri_pattern, and mg_http_endpoint_opts::user_data.
Referenced by mg_register_http_endpoint().
mg_resolve_async()
int mg_resolve_async (struct mg_mgr * mgr, const char * name, int query, mg_resolve_callback_t cb, void * data)
References mg_resolve_async_opt().
mg_resolve_async_opt()
int mg_resolve_async_opt (struct mg_mgr * mgr, const char * name, int query, mg_resolve_callback_t cb, void * data, struct mg_resolve_async_opts opts)
References mg_resolve_async_request::callback, mg_resolve_async_request::data, DBG, mg_resolve_async_opts::dns_conn, mg_resolve_async_opts::max_retries, mg_resolve_async_request::max_retries, MG_CALLOC, MG_CB, mg_connect(), MG_DEFAULT_NAMESERVER, MG_FREE, mg_get_ip_address_of_nameserver(), mg_resolve_async_eh(), mg_resolve_async_request::name, mg_mgr::nameserver, mg_resolve_async_opts::nameserver, mg_resolve_async_request::query, mg_resolve_async_opts::timeout, mg_resolve_async_request::timeout, and mg_connection::user_data.
Referenced by mg_connect_opt(), and mg_resolve_async().
mg_resolve_from_hosts_file()
int mg_resolve_from_hosts_file (const char * host, union socket_address * usa)
References socket_address::sin.
Referenced by mg_parse_address().
mg_send()
void mg_send (struct mg_connection * , const void * buf, int len)
References mg_connection::flags, mg_connection::iface, mg_connection::last_io_time, MG_F_UDP, mg_time(), mg_iface_vtable::tcp_send, mg_iface_vtable::udp_send, and mg_iface::vtable.
Referenced by dns_handler(), mg_forward(), mg_get_http_header(), mg_http_send_error(), mg_http_send_redirect(), mg_mqtt_connack(), mg_mqtt_publish(), mg_mqtt_suback(), mg_mqtt_subscribe(), mg_mqtt_unsubscribe(), mg_parse_http_basic_auth(), mg_printf_html_escape(), mg_register_http_endpoint(), mg_send_dns_query(), mg_send_head(), mg_send_http_chunk(), mg_send_mqtt_handshake_opt(), mg_send_mqtt_short_command(), mg_send_websocket_frame(), mg_send_websocket_framev(), mg_send_ws_header(), mg_set_nameserver(), mg_set_protocol_dns(), mg_tun_send_frame(), and mg_vprintf().
mg_send_dns_query()
void mg_send_dns_query (struct mg_connection * nc, const char * name, int query_type)
References mbuf::buf, DBG, mg_connection::flags, mg_dns_message::flags, mg_dns_resource_record::kind, mbuf::len, mbuf_free(), mbuf_init(), mbuf_insert(), MG_CALLOC, mg_dns_encode_record(), mg_dns_insert_header(), MG_DNS_QUESTION, mg_dns_tid, MG_F_UDP, MG_FREE, mg_send(), mg_dns_message::num_questions, mg_dns_message::questions, mg_dns_resource_record::rclass, mg_dns_resource_record::rtype, and mg_dns_message::transaction_id.
Referenced by mg_resolve_async_eh().
mg_send_head()
void mg_send_head (struct mg_connection * n, int status_code, int64_t content_length, const char * extra_headers)
References mg_printf(), mg_send(), and mg_send_response_line().
Referenced by mg_http_send_error().
mg_send_http_chunk()
void mg_send_http_chunk (struct mg_connection * nc, const char * buf, size_t len)
References mg_send().
Referenced by mg_parse_http_basic_auth(), and mg_printf_http_chunk().
mg_send_mqtt_handshake()
void mg_send_mqtt_handshake (struct mg_connection * nc, const char * client_id)
References mg_send_mqtt_handshake_opt().
mg_send_mqtt_handshake_opt()
void mg_send_mqtt_handshake_opt (struct mg_connection * nc, const char * client_id, struct mg_send_mqtt_handshake_opts)
References mg_send_mqtt_handshake_opts::flags, mg_send_mqtt_handshake_opts::keep_alive, mg_mqtt_proto_data::keep_alive, MG_MQTT_CMD_CONNECT, MG_MQTT_HAS_PASSWORD, MG_MQTT_HAS_USER_NAME, MG_MQTT_HAS_WILL, mg_mqtt_prepend_header(), mg_send(), mg_send_mqtt_handshake_opts::password, mg_connection::proto_data, mg_send_mqtt_handshake_opts::user_name, mg_send_mqtt_handshake_opts::will_message, and mg_send_mqtt_handshake_opts::will_topic.
Referenced by mg_send_mqtt_handshake().
mg_send_response_line()
void mg_send_response_line (struct mg_connection * nc, int status_code, const char * extra_headers)
References mg_mk_str(), and mg_send_response_line_s().
Referenced by mg_http_send_redirect(), mg_parse_http_basic_auth(), mg_register_http_endpoint(), and mg_send_head().
mg_send_websocket_frame()
void mg_send_websocket_frame (struct mg_connection * nc, int op_and_flags, const void * data, size_t data_len)
References DBG, mg_connection::flags, MG_F_SEND_AND_CLOSE, mg_send(), mg_send_ws_header(), mg_ws_mask_frame(), mg_connection::send_mbuf, and WEBSOCKET_OP_CLOSE.
Referenced by TBT::ev_handler_StateChange(), mg_printf_websocket_frame(), and mg_ws_handler().
mg_send_websocket_framev()
void mg_send_websocket_framev (struct mg_connection * nc, int op_and_flags, const struct mg_str * strings, int num_strings)
References mg_connection::flags, mg_str::len, MG_F_SEND_AND_CLOSE, mg_send(), mg_send_ws_header(), mg_ws_mask_frame(), mg_connection::send_mbuf, and WEBSOCKET_OP_CLOSE.
Referenced by mg_tun_send_frame().
mg_send_websocket_handshake()
void mg_send_websocket_handshake (struct mg_connection * nc, const char * uri, const char * extra_headers)
References mg_mk_str(), MG_NULL_STR, and mg_send_websocket_handshake3v().
mg_send_websocket_handshake2()
void mg_send_websocket_handshake2 (struct mg_connection * nc, const char * path, const char * host, const char * protocol, const char * extra_headers)
References mg_send_websocket_handshake3().
mg_send_websocket_handshake3()
void mg_send_websocket_handshake3 (struct mg_connection * nc, const char * path, const char * host, const char * protocol, const char * extra_headers, const char * user, const char * pass)
References mg_mk_str(), and mg_send_websocket_handshake3v().
Referenced by mg_send_websocket_handshake2().
mg_send_websocket_handshake3v()
void mg_send_websocket_handshake3v (struct mg_connection * nc, const struct mg_str path, const struct mg_str host, const struct mg_str protocol, const struct mg_str extra_headers, const struct mg_str user, const struct mg_str pass)
References mbuf::buf, mg_str::len, mbuf::len, mbuf_free(), mbuf_init(), mg_base64_encode(), mg_basic_auth_header(), mg_printf(), mg_ws_random_mask(), and mg_str::p.
Referenced by mg_connect_ws_opt(), mg_send_websocket_handshake(), and mg_send_websocket_handshake3().
mg_set_close_on_exec()
void mg_set_close_on_exec (sock_t)
Referenced by mg_register_http_endpoint(), mg_socket_if_poll(), and mg_socket_if_sock_set().
mg_set_nameserver()
void mg_set_nameserver (struct mg_mgr * mgr, const char * nameserver)
References mbuf::buf, mg_connection::flags, mg_connection::handler, mbuf::len, mbuf_append(), mbuf_free(), mbuf_init(), mbuf_remove(), MG_CALLOC, MG_EV_RECV, MG_F_UDP, MG_FREE, mg_send(), mg_tun_reconnect(), MG_UD_ARG, mg_mgr::nameserver, mg_connection::proto_handler, and mg_connection::recv_mbuf.
mg_set_protocol_dns()
void mg_set_protocol_dns (struct mg_connection * nc)
References mg_dns_message::answers, dns_handler(), mg_connection::flags, mg_dns_resource_record::kind, mg_mqtt_message::len, mbuf_insert(), MG_DNS_ANSWER, mg_dns_copy_questions(), mg_dns_encode_record(), mg_dns_insert_header(), mg_dns_uncompress_name(), MG_F_UDP, MG_MAX_DNS_ANSWERS, mg_send(), mg_dns_resource_record::name, mg_dns_message::num_answers, mg_connection::proto_handler, and mg_connection::send_mbuf.
mg_set_protocol_http_websocket()
void mg_set_protocol_http_websocket (struct mg_connection * nc)
References mg_http_handler(), and mg_connection::proto_handler.
Referenced by mg_connect_http_base(), and TBT::WSClientInterface::threadFunc().
mg_set_protocol_mqtt()
void mg_set_protocol_mqtt (struct mg_connection * nc)
References MG_CALLOC, mg_mqtt_proto_data_destructor(), mqtt_handler(), mg_connection::proto_data, mg_connection::proto_data_destructor, and mg_connection::proto_handler.
Referenced by mg_mqtt_disconnect(), and mqtt_handler().
mg_set_timer()
double mg_set_timer (struct mg_connection * c, double timestamp)
References DBG, mg_connection::ev_timer_time, mg_connection::flags, MG_F_RESOLVING, and mg_connection::priv_2.
Referenced by mg_tun_send_frame().
mg_skip()
const char* mg_skip (const char * s, const char * end_string, const char * delimiters, struct mg_str * v)
References ARRAY_SIZE, DBG, mg_str::len, MG_MAX_PATH, and mg_str::p.
Referenced by mg_http_parse_headers(), and mg_parse_http().
mg_sock_addr_to_str()
int mg_sock_addr_to_str (const union socket_address * sa, char * buf, size_t len, int flags)
References MG_SOCK_STRINGIFY_IP, MG_SOCK_STRINGIFY_PORT, socket_address::sa, socket_address::sin, and socket_address::sin6.
Referenced by TBT::ev_handler(), mg_conn_addr_to_str(), mg_http_handler(), mg_resolve_async_eh(), and mg_sock_to_str().
mg_sock_to_str()
void mg_sock_to_str (sock_t sock, char * buf, size_t len, int flags)
References mg_sock_addr_to_str(), mg_sock_get_addr(), and MG_SOCK_STRINGIFY_REMOTE.
Referenced by mg_register_http_endpoint().
mg_socketpair()
int mg_socketpair (sock_t [2], int sock_type)
Referenced by mg_register_http_endpoint(), mg_socket_if_init(), and mg_socket_if_poll().
mg_strchr()
const char* mg_strchr (const struct mg_str s, int c)
References mg_str::len, mg_strcmp(), mg_str::p, and WEAK.
Referenced by mg_next_comma_list_entry_n(), and mg_strdup_nul().
mg_strcmp()
int mg_strcmp (const struct mg_str str1, const struct mg_str str2)
References mg_str::len, mg_strncmp(), mg_str::p, and WEAK.
Referenced by mg_strchr(), and mg_strncmp().
mg_strdup()
struct mg_str mg_strdup (const struct mg_str s)
References mg_strdup_common().
Referenced by mg_assemble_uri(), and mg_register_http_endpoint_opt().
mg_strdup_nul()
struct mg_str mg_strdup_nul (const struct mg_str s)
References mg_strchr(), mg_strdup_common(), and WEAK.
mg_strncmp()
int mg_strncmp (const struct mg_str str1, const struct mg_str str2, size_t n)
References mg_str::len, mg_strcmp(), mg_strstr(), and WEAK.
Referenced by mg_bind_opt(), mg_parse_http_basic_auth(), and mg_strcmp().
mg_strstr()
const char* mg_strstr (const struct mg_str haystack, const struct mg_str needle)
References mg_str::len, and mg_str::p.
Referenced by mg_strncmp().
mg_time()
double mg_time (void)
References cs_time().
Referenced by mg_conn_addr_to_str(), mg_create_connection_base(), mg_http_send_error(), mg_mqtt_prepend_header(), mg_parse_http_basic_auth(), mg_recv_common(), mg_register_http_endpoint(), mg_resolve_async_eh(), mg_send(), mg_socket_if_poll(), mg_tun_reconnect(), mg_tun_send_frame(), mqtt_handler(), and resolve_cb().
mg_url_decode()
int mg_url_decode (const char * src, int src_len, char * dst, int dst_len, int is_form_url_encoded)
References HEXTOI.
Referenced by mg_get_http_var(), and mg_parse_http_basic_auth().
mg_url_encode()
struct mg_str mg_url_encode (const struct mg_str src)
References mbuf::buf, mbuf::len, mbuf_append(), mbuf_init(), mbuf_trim(), and mg_mk_str_n().
Referenced by mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_vcasecmp()
int mg_vcasecmp (const struct mg_str * str2, const char * str1)
References mg_str::len, mg_ncasecmp(), and mg_str::p.
Referenced by mg_http_conn_destructor(), mg_http_handler(), mg_http_send_error(), mg_parse_http(), mg_parse_http_basic_auth(), and mg_vcmp().
mg_vcmp()
int mg_vcmp (const struct mg_str * str2, const char * str1)
References mg_str::len, mg_vcasecmp(), mg_str::p, and WEAK.
Referenced by mg_connect_http_base(), mg_http_send_error(), mg_mk_str_n(), mg_normalize_uri_path(), mg_parse_http_basic_auth(), and mg_register_http_endpoint().
mg_vprintf()
int mg_vprintf (struct mg_connection * , const char * fmt, va_list ap)
References mg_avprintf(), MG_FREE, mg_send(), and MG_VPRINTF_BUFFER_SIZE.
Referenced by mg_printf().
Variable Documentation
mg_ifaces
const struct mg_iface_vtable* mg_ifaces[]
Referenced by mg_mgr_init_opt().
mg_num_ifaces
int mg_num_ifaces
Referenced by mg_mgr_init_opt().