TBT Namespace Reference
Classes
class Client
class ClientInterface
class DccGenerator
class Decoder
class LocDecoder
struct LocInfo
class Manager
Class Manager represents 'the Boss' in the system.
struct SystemState
class UDPClient
class UDPClientInterface
class WSClientInterface
class XpressNetClient
class XpressNetClientInterface
Enumerations
enum PowerState { PowerOn,
PowerOff
 }
Functions
struct TBT::SystemState __attribute__ ((packed))
void ev_handler (mg_connection *nc, int ev, void *ev_data)
void ev_handler_StateChange (mg_connection *nc, int ev, void *ev_data)
Variables
TBT::UDPClient __attribute__
Enumeration Type Documentation
PowerState
enum TBT::PowerState
Enumerator
PowerOn
PowerOff
Function Documentation
__attribute__()
struct TBT::SystemState TBT::__attribute__ ((packed))
ev_handler()
void TBT::ev_handler (mg_connection * nc, int ev, void * ev_data)
References websocket_message::data, MG_EV_WEBSOCKET_FRAME, mg_sock_addr_to_str(), MG_SOCK_STRINGIFY_IP, MG_SOCK_STRINGIFY_PORT, mg_connection::sa, and websocket_message::size.
Referenced by mg_call(), and TBT::WSClientInterface::threadFunc().
ev_handler_StateChange()
void TBT::ev_handler_StateChange (mg_connection * nc, int ev, void * ev_data)
References MG_EV_POLL, mg_send_websocket_frame(), and WEBSOCKET_OP_TEXT.
Referenced by TBT::WSClientInterface::broadcastEmergencyStop(), and TBT::WSClientInterface::broadcastPowerStateChange().
Variable Documentation
__attribute__
struct TBT::LocInfo TBT::__attribute__
Referenced by deliver_chunk().